### ISSUE TITLE
Plan for Load-Testing MapStory Platform at Scale

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1027]
## Investigate Load Testing Strategies

The platform needs to be able to function at scale (hundreds of concurrent users) and fail gracefully when overloaded. This spike will help determine the tools and requirements for testing the platform in this way. Areas of interest are: 

- How our current technologies handle concurrency and current capacity 
- Assessment of current AWS configurations
- Best practices for development with scalability in mind (GeoNode/GeoServer)
- Tools to automate testing of many concurrent users. 

## Deliverables 

This spike will be completed upon: 

- Summary of capacity bottlenecks
- Suggested changes (if any) to AWS configurations. 
- Suggestions of tools to use for testing, with reasoning for selection
- Creation of ticket(s) to address current deficiencies 

All responses can be posted as comments in this issue thread. 

## Timeline

This spike should be completed within 1 week of starting (research, not implementation). If additional time is required, summary of work completed so far should be added to the comment thread.

**Comment by jonpmarino** [comment]
closing - reverted to being a milestone item, https://github.com/MapStory/mapstory/milestone/11
