### ISSUE TITLE
Legend in MapStory viewer is not displaying layer title (unless it is 'masked')

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#1037]
<img width="502" alt="screen shot 2017-10-06 at 2 33 33 pm" src="https://user-images.githubusercontent.com/15912063/31299816-e97d56f8-aab5-11e7-949e-784e9b2844ee.png">

**Comment by trepagnier** [comment]
Resolved: https://github.com/MapStory/story-tools/pull/278

**Comment by jonpmarino** [comment]
closing based on testing.
