### ISSUE TITLE
Document the `date_xd` field in preparation for UX considerations on layer editing

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#1047]

**Comment by lhcramer** [comment]
When testing `create` modal, several questions arose regarding the lack of timeline and `date_xd` field. 

- when is the time attribute generated/parsed into the `date_xd` format?
- is there a way we can recalculate upon exiting the layer editor?
- more generally, what processes that are part of importing should we re-run upon updates to layers? 
- Do we need to make `date_xd` a pre-defined field in the `create` modal?
- is the naming convention of `date_xd` a requirement for time in the data model? 
- every time a feature is added or updated, is it going to need to run through the date_xd conversion?

**Comment by lhcramer** [comment]
Reference issue #419 when researching

**Comment by Coop56** [comment]
Some answers based on what I know.

During the import process, date_xd is generated from the date the user gives.  We do not currently calculate this any other time outside of the import process.  We should not expose date_xd to the user (even though we currently do) and we should instead convert the date they enter to a date_xd every time a feature is modified.  That's currently not happening, so it will be new code we'll need to write and add.
