### ISSUE TITLE
"Featured" story selection is not persisting on the home page when we update the site.

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#1049]
As noted yesterday, it seems that featuring content via the django admin panel will display on the homepage as intended, but doesn't persist on the homepage display after the site has been updated 

p.s. you can use `/api/base/search/?featured=true&is_published=true&limit=6` for a quick json view of the same query the homepage makes

**Comment by cuttlefish** [comment]
The featured attribute is properly being stored in the base_resourcebase table in the DB.

**Comment by lhcramer** [comment]
Has this been resolved?
