### ISSUE TITLE
Site notifications don't dismiss/close upon clicking 'x'

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#1053]
![screen shot 2017-10-17 at 2 34 55 pm](https://user-images.githubusercontent.com/15912063/31685404-77f8f8b6-b348-11e7-8f29-aacbb0db34c0.png)
![screen shot 2017-10-17 at 2 34 33 pm](https://user-images.githubusercontent.com/15912063/31685405-780d5b1c-b348-11e7-8474-9fed41527f47.png)

**Comment by jonpmarino** [comment]
this is still a valid issue that would be good to fix

**Comment by Coop56** [comment]
Already covered in an issue that's in the current sprint, #1760, closing.
