### ISSUE TITLE
Animated GIF thumbnails uploaded are mis-sized when featured on homepage

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1064]
Users have the ability to upload Animated GIFs as thumbnails for layers and stories. These seem to work fine on the Explore page, but if a layer or story is featured on HOME with a GIF thumbnail, the sizing is wrong. See screenshot:

![screen_shot_2017-10-20_at_10 21 20_am_720](https://user-images.githubusercontent.com/2573761/31899141-8162bd32-b7e0-11e7-99d6-1eca98be146c.jpg)

**Comment by lhcramer** [comment]
@jonpmarino , see #1060 for this issue
