### ISSUE TITLE
Clicking "zoom to feature" for a new Feature POINT in edit-mode results in a Type Error

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1071]
Issue identified using Chrome browser. Layer used doing testing: https://mapstory.org/layers/windfarms_3ae30c73, and reproduced with several other layers

To reproduce:

1. Click "Edit Features" on a layer from the detail page

![screen shot 2017-10-23 at 3 31 57 pm](https://user-images.githubusercontent.com/2573761/31911775-63871840-b807-11e7-8531-428f0c20d32e.jpg)

2. Go to the Edit History in the layer, click zoom to feature

![screen shot 2017-10-23 at 3 31 38 pm](https://user-images.githubusercontent.com/2573761/31911791-6f21568e-b807-11e7-81f7-7b376bc323d4.jpg)

3. Receive a Type Error

![screen shot 2017-10-23 at 3 19 43 pm](https://user-images.githubusercontent.com/2573761/31911803-7a6bf170-b807-11e7-824e-b061c0c51892.jpg)

**Acceptance Criteria**

When a user zooms to a feature edit, they should be zoomed to that feature without a Type Error message

**Comment by emilyashley** [comment]
hmmm, has anyone checked if this is also the case for Polygon or Line datasets? @jonpmarino @lhcramer

Changing the scope of the issue to new feature, Point-type data (as opposed to a diff change set) since that seems to be the scope of what I can test for in the short term on Editor.

**Comment by lhcramer** [comment]
that is correct. I haven't checked lines recently, but it _seems_ like the points are not "large enough" to select, whereas polygons have an internal area
