### ISSUE TITLE
"Default Chapter View" should be the default view, not the required view

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1072]
**Issue**

When a storyteller creates a mapstory, they define a "default chapter view" zoom level for the story in composer:

![screen shot 2017-10-23 at 4 25 20 pm](https://user-images.githubusercontent.com/2573761/31914317-d49d681a-b80f-11e7-801a-0b75be662a4c.jpg)

The purpose of this default view is to determine the zoom level the chapter will begin at and remain at _unless the viewer zooms in or out when viewing the story_. If the viewer of the story changes the zoom level, the story should remain there, as the viewer has specified, until a new StoryBox is arrived at, or unless the viewer changes the zoom level again. Each time the chapter is started over, the chapter always begins at the "default chapter view".

Currently, however, the "default chapter view" is behaving as a _required_ chapter view. Even if the viewer clicks the zoom controls, the story view is brought back to the default chapter view, overriding the zoom action taken by a viewer.

See this video for an example of this behavior (which uses this story as an example: https://mapstory.org/story/scramble-for-africa/): https://www.dropbox.com/s/5lo3hjcdo2ekrr8/zoom.mov?dl=0

Perhaps when new composer is live and we have some kind of "interactive" versus "view-only" modes for stories this type of required view makes sense. But until then, and as long as we expose zoom controls to the viewer of the story, we should honor the zoom actions they take when viewing a story.

**Acceptance Criteria**

Change behavior of story viewing so that:

- Each time a chapter or story play _begins_ the zoom level is set to the "Default Chapter View"
- If the viewer of the story zooms in and out, let that new zoom level persist until either a preset StoryBox is reached, or the viewer sets a new zoom level
- Each time the chapter or story begins again, or the browser is refreshed, the story or chapter should begin from the Default Chapter View

**Comment by emilyashley** [comment]
We can make this part of the StoryTools feature requirements for composer and viewer.

I want to note that this differs from previous feature requirements given over the past year that the storyteller (not the viewer) have utmost control over the zoom experience on stories --- so it is neither  a bug nor a regression.


> as long as we expose zoom controls to the viewer of the story, we should honor the zoom actions they take when viewing a story. 

^ one way to address this sentiment is reflected in the decision to remove the zoom buttons and mouse wheel functionality in the next iteration of storyViewer. If I recall correctly, we were not to do this until the default zoom/ frame/ boxes were more stable with this next composer. Should we be pivoting on this plan?

**Comment by emilyashley** [comment]
However, to change this now, I think we could toggle the `returnToExtent` here https://github.com/MapStory/mapstory/blob/fc5416d56dc3d1a59764940781404034ef9a7072/mapstory/templates/viewer/story_viewer.js#L52



As for acceptance requirements, toggling this above code will **not** inherently meet 

- reseting to default zoom on "repeat chapter" loop (however it will meet acceptance requirements for a page refresh or repeat story)

- reseting to default view after a storyframe has completed. 

Seems that storyframes aren't currently built to signal when their end date has passed. What they do is check if there is a current storyframe in the timeline and, if there is, it centers on that. If there isn't a current frame, it'll `returnToExtent` via `updateCenterAndZoom` just like on any other timeline tick i.e. `rangeChange`. 

So by turning off the return to extent in this way, the view will stay on the storyframe until a) another storyframe appears, b) the user zooms, or c) the story starts over.
