### ISSUE TITLE
Thumbnails are not persisting after user uploads custom icon or gif  and layer is featured

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1074]
See Layer https://mapstory.org/layers/eu_expansion_69c547e2 for logs 

- 20:40 PST 2017-10-23 Starting Image 

![image](https://user-images.githubusercontent.com/5894255/31923862-315174da-b832-11e7-8f67-aa792eb391cb.png)

- Uploaded Image 

![download](https://user-images.githubusercontent.com/5894255/31924085-af3c4194-b833-11e7-9e22-d684930de675.png)

- 20:47 PST 2017-10-23 Uploaded Image on MapStory

![image](https://user-images.githubusercontent.com/5894255/31924051-8136641e-b833-11e7-9efa-01778980cfd0.png)

- Date and Time of Image no longer there 

Image of Thumbnail no longer on site

**Comment by jonpmarino** [comment]
More datapoints (captured at 13:00 PST, 10/26):

1. If you feature a LAYER on the homepage that has an animated GIF thumbnail, the GIF will be reverted back to the original machine-generated thumbnail. 

Example: this layer had an animated GIF thumbnail. When it was featured on HOME, the GIF thumbnail was lost, https://mapstory.org/layers/revolutionary_war_dad63251.

2. Thumbnails of Layers are changing when featured on HOME even if they don't have an animated GIF. For example, this layer had a thumbnail that showed orange styled features on a white background. It was featured, and now only a blank white background appears on the thumbnail:

![screen shot 2017-10-26 at 3 02 02 pm](https://user-images.githubusercontent.com/2573761/32075225-c70ddc1c-ba61-11e7-9e7c-adab3f831b21.jpg)

**Comment by lhcramer** [comment]
furthermore, the solution @Coop56 is implementing might also deal with [#521](https://github.com/MapStory/mapstory/issues/521). Close if resolved with this solution

@davisc also brought up [PR 414](https://github.com/boundlessgeo/exchange/pull/414) in the Exchange Repo that may be relevent
