### ISSUE TITLE
Add searchable Organizations and Initiatives section in Explore.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1077]
**Background**

Organization and Initiative pages should have cards and be discoverable in `Explore > Groups` alongside individual profiles.
Organization and Initiative pages are group types, similar to individual profiles but representing collectives. 

**Acceptance criteria**
- [ ] In Explore page: A new tab section for 'Groups'
- [ ] Once created, org and initiative pages should have a 'card' in Explore much like individual profile cards.
- [ ] Under the 'Groups' tab of Explore, there should be a Group Type filter options to only see cards for Organizations, or Initiatives. This filtering parallels the filters that already for "Content Type > StoryLayers, MapStories" in the Content Tab of Explore
- [ ] Typing into the search box will filter Groups by name.

![screen shot 2017-10-25 at 10 29 31 pm](https://user-images.githubusercontent.com/2573761/32033836-978dc1ec-b9d4-11e7-9287-0c8556c16969.jpg)

![screen shot 2017-10-25 at 10 31 27 pm](https://user-images.githubusercontent.com/2573761/32033839-9d773296-b9d4-11e7-99a7-00afff40e061.jpg)

**Comment by josellausas** [comment]
![Screen Shot 2017-12-12 at 2.24.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58751224caea2f0f003a52f0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f16b7191a37af1102f4f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ee5d6695e73c03d40abbd804dbb02eb208b4d86beb4de1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df748e04c55a6163362e0742431.png)
