### ISSUE TITLE
Add Support for UTF-8 Encoded Shapefiles 

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1079]
When uploading shapefiles, UTF-8 Encoded files are not imported correctly and produce "empty" databases. 

This poses an issue for ArcGIS and windows datasets.

**Comment by Coop56** [comment]
To add some context.  The layer says that it imported properly.  But none of the features are actually there and there's a runtime error in the logs.

`Exception RuntimeError: 'COPY statement failed.\nERROR:  invalid byte sequence for encoding "UTF8": 0xc9 0x63\nCONTEXT:  COPY canadaterritories_f46c7859, line 4\n' in <built-in function delete_DataSource> ignored`

**Comment by Coop56** [comment]
This is already done, closing.
