### ISSUE TITLE
Installer defaults pulls in storytools

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#1083]
Clean machine, following install process dies at:

Status: Image is up to date for quay.io/mapstory/django:master
Pulling story-tools-build (quay.io/mapstory/story-tools-build:latest)...
ERROR: unauthorized: access to the requested resource is not authorized

**Comment by cuttlefish** [comment]
I believe this has been resolved. Let me know if it happens again, it won't appear on my machine or and of the deployments.
