### ISSUE TITLE
Setup Initiatives app

### ISSUE THREAD

**Issue by josellausas** [MapStory/mapstory#1091]
Create a new app for Initiatives and setup with basic:

- [x] Models
- [x] Views
- [x] Namespaced URLs
- [x] Templates
- [x] Tests

**Comment by rob-metalinkage** [comment]
Hi Jose,

as you are setting up a new module - can I get your input into documenting the process:
first - check to see if this is correct  #786 and then update #791 with what it takes to inject a new module into a docker build - I've been waiting for months now for this info, but its been less important than getting beta out.  Also if you have a development process that actually works to allow you to update the docker build with module changes (and hopefully without blowing away everything and waiting 30 mins to restart containers), lets add this to https://github.com/MapStory/mapstory/blob/master/docker/README.md

Cheers
Rob
