### ISSUE TITLE
Refactor naming conventions for pins/frames to sotrypins/storyframes

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1118]
Refactor all relevant codebases to use the naming convention `storypins` for pins / annotations and update databases where necessary 

Do the same for `storyframes` regarding boxes / frames

**Comment by josellausas** [comment]
Taking this into considerationf for new Composer Pins.

**Comment by Coop56** [comment]
Annotations has been refactored to StoryPins, moving onto Boxes into StoryFrames.

**Comment by Coop56** [comment]
This was completed, closing.
