### ISSUE TITLE
Social media and hyperlinks in Org Pages should launch a new tab

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1124]
When clicking the social media links or hyperlinks on an Org Page, users are taken out of MapStory.org and sent to the linked page.

It would be better to instead launch the link in a new browser tab  so they don't lose their MapStory.org visit.

![screen shot 2017-11-20 at 10 46 32 pm](https://user-images.githubusercontent.com/2573761/33055418-2a327bda-ce45-11e7-99a9-d44fe0fcca80.jpg)

**Comment by jonpmarino** [comment]
Also, same behavior change to 'sharing' options for layers and stories from the detail pages. Instead of taking user out of mapstory platform, should open new browser tab. This the behavior that occurs when you click the "metadata" button inside the layer editor, so its copying the way that behavior is triggered.

**Comment by Coop56** [comment]
Resolved by https://github.com/MapStory/mapstory/pull/1763
