### ISSUE TITLE
Replace Haystack

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#1127]
Haystack doesn't handle Elasticsearch very well. We should replace it.

@travislbrundage has done some work on this for Exchange. We should examine porting that over or getting it pushed upstream, since the current GeoNode/Haystack integration doesn't actually work.

**Comment by cuttlefish** [comment]
The core problem is that Haystack is using a single key space for all of the models. They're all using the auto-incremented `id` column. So if a user has an id of 3 and a MapLayer has an id of 3, then only one of them will get indexed.

**Comment by Coop56** [comment]
Working this issue now.  The first step is figuring out if we can just not use elasticsearch, with an ideal goal of search working with or without elasticsearch enabled.

**Comment by cuttlefish** [comment]
Exchange has been working on separating their new ES work into a module.
https://github.com/boundlessgeo/geonode-elasticsearch

**Comment by Coop56** [comment]
This is much more than a single issue - it should likely be placed inside of an Epic.
