### ISSUE TITLE
Interests are not displayed on user profile

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1145]
**Expected Behavior**

The individual user profile has a space for users to list their "interests". On the profile, these interests function similarly to tags. When clicked they activate an Explore>Storytellers search w/ interest tag activated. In the Explore, one can also filter for users based on their interests.

**Issue**

The current user profile has no area to display Interests in the lefthand area where all user profile information is presented.

**Example**

In the Edit Profile area "interests" are entered.

![screen shot 2017-12-26 at 3 30 35 pm](https://user-images.githubusercontent.com/2573761/34365192-24bbfc6a-ea53-11e7-9054-3cf16b353a96.jpg)

On the published user profile, "interests" don't appear anywhere.

![screen shot 2017-12-26 at 3 24 12 pm](https://user-images.githubusercontent.com/2573761/34365214-759f150e-ea53-11e7-9907-41cb4fce0ce9.jpg)

But, on the Explore page, there _is_ a filter for Interests, and the search field does seem to work. For example, when I filter for the interest "education", the jonpmarino profile which has that interest entered does appear in search results.

![screen shot 2017-12-26 at 3 24 43 pm](https://user-images.githubusercontent.com/2573761/34365218-7b436028-ea53-11e7-9bf9-9203c71671bd.jpg)

**Comment by emilyashley** [comment]
Yep. This is already addressed in the profile upgrade work.

**Comment by emilyashley** [comment]
Does this need to be addressed before that work is incorporated?

**Comment by emilyashley** [comment]
@goudine 

angular material unstyled chips should be okay for the display https://material.angular.io/components/chips/overview#unstyled-chips

the interests should come from the mapstory profile model [here](https://github.com/MapStory/mapstory/blob/master/mapstory/mapstory_profile/models.py) and already be accessible in the html thru the django context dictionary made [here](https://github.com/MapStory/mapstory/blob/master/mapstory/views.py#L155)

Check around in the profile sidebar [template](https://github.com/MapStory/mapstory/blob/master/mapstory/templates/people/_sidebar.html) to see how the other values (and conditional sub-headers) are displayed thru django template rendering [docs here](https://docs.djangoproject.com/en/1.7/topics/templates/)

a more complex/interactive example of using angular material chips can be found here on the [layer detail page](https://github.com/MapStory/mapstory/blob/master/mapstory/templates/layers/_details.html#L92), but the profile interest chips have no need to be interactive at the moment, so simply displaying them should be great!

((unsure if I linked to the correct version of each of the docs above, so double check that if something isn't working as expected))

Welcome to writing djangular 😅

**Comment by emilyashley** [comment]
Interest view: 
<img width="387" alt="screen shot 2018-01-26 at 5 03 31 pm" src="https://user-images.githubusercontent.com/15912063/35464323-e1ba100c-02ba-11e8-9d09-bed0aa335388.png">


No interest view:
<img width="356" alt="screen shot 2018-01-26 at 4 50 20 pm" src="https://user-images.githubusercontent.com/15912063/35464301-c99defca-02ba-11e8-9e83-b440f4836bc4.png">

**Comment by goudine** [comment]
Verified, everything looks good to me @emilyashley 

Interests appear when they should and are no longer visible when profile is edited accordingly
![interest_provided](https://user-images.githubusercontent.com/17364268/35529216-3c5e7d6e-04e5-11e8-86fe-7466e234b7d7.png)
![interest_not_provided](https://user-images.githubusercontent.com/17364268/35529223-41483e96-04e5-11e8-9770-e641ad1cc1b8.png)
