### ISSUE TITLE
Enable Admins to change layer-owner in django-admin the same way we can for stories

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1159]
Issue:

In django-admin, an Admin (someone with Superuser status) needs to be able to change the layer-owner via the same procedure as we can for stories.

Right now when an Admin tries to change the layer-owner, the username links to the user account rather than opening a toggle to change the owner. Example:

![screen shot 2018-01-04 at 3 01 07 pm](https://user-images.githubusercontent.com/2573761/34584138-2f9a9614-f160-11e7-84e9-ade1716e2890.jpg)

For stories, however, there s a row in the table for story owners, and the story owner can be easily changed via a drop down. Example:

![screen shot 2018-01-04 at 2 59 37 pm](https://user-images.githubusercontent.com/2573761/34584106-06503494-f160-11e7-8a34-391a211e54a3.jpg)

**Comment by Coop56** [comment]
This issue was completed a long time ago, this functionality exists.  Closing.
