### ISSUE TITLE
Get geomType and features into layer metadata

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#1168]

**Comment by darinacosta** [comment]
NTS: use this: https://github.com/MapStory/story-tools-composer/blob/styling/app/layers/layerSvc.js#L108

You first have to make sure the layer has the `metadata` that the method is expecting otherwise it may fail silently. This will require some refactoring of layer adding.

**Comment by darinacosta** [comment]
NTS: check `WFSDescribeFeatureType`. It isn't parsing XML. Why?

**Comment by darinacosta** [comment]
NTS: the unmarshaller isnt working in WFSDescribeFeatureType L11. Reading up on this: https://github.com/highsource/jsonix/wiki/Using-Jsonix-in-Your-JavaScript-Program

**Comment by trepagnier** [comment]
Figure out how to get geomType in here: https://github.com/MapStory/story-tools-composer/blob/dja-styling-sidebar/app/layers/layerOptionsSvc.js#L43

**Comment by trepagnier** [comment]
Gotta add a getFeatureType method to get geometry:
https://github.com/MapStory/MapLoom/blob/feature/composer-wip/src/common/geogig/GeoGigService.js#L291

**Comment by trepagnier** [comment]
Resolved: https://github.com/MapStory/story-tools/commit/d0579621c200f7287de61573c99da682a9e6d76d
