### ISSUE TITLE
Prevent Import from failing if a __MACOSX directory exists

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#1174]
Also verify that the existence of .DS_Store doesn't cause problems (we can probably just ignore all `.*` files).

Using the Finder's contextual menu to compress a shapefile's directory should reproduce this scenario.

**Comment by DBlasby** [comment]
Likely issue is when you zip a directory containing the shape files.

Underlying exception has to do with not finding the extention separator (.) In a filename in the zip.
