### ISSUE TITLE
Layer Editor History Sidebar only displays the 10 most recent edits

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#1179]
If a layer has more than 10 edits, the remaining history is unavailable for viewing to the user in layer editor (even tho it is visible in the log on the layer detail contribution tab)

will come back and fill out this ticket more with possible solutions, but wanted to save the issue.

**Comment by emilyashley** [comment]
closed with https://github.com/MapStory/MapLoom/commit/512d094feef0d34c4144cb552a0a4707b2aefbbb

should cover +95% of our user layers for a while

**Comment by jonpmarino** [comment]
sweet!
