### ISSUE TITLE
Thumbnails - PhantomJS implementation

### ISSUE THREAD

**Issue by DBlasby** [MapStory/mapstory#1188]
Add thumbnails for StoryLayers and Story.

See details;
https://docs.google.com/document/d/1XlnTWRkHwshren2-jsLmTQWYulo34Z7SHNfyaJkwH84

**Comment by lhcramer** [comment]
Validate that the PhantomJS implementation works with geonode-2.8.  (specifically around naming convention of `geonode:layername` vs `layername`. Additionally, use `MapStory_Generic` styles to generate thumbnails.
