### ISSUE TITLE
Troubleshoot Missing Style Name 

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#1190]

**Comment by trepagnier** [comment]
NTS: wrote a temp solution to this in this gist: https://gist.github.com/darinacosta/37dc537f1b8156b8cc217277251213de

Make it a permanent fix

**Comment by trepagnier** [comment]
Pick it up here: https://github.com/MapStory/story-tools/blob/composer/lib/ng/core/ogc/module.js#L541

**Comment by trepagnier** [comment]
Get geomType and set it here: https://github.com/MapStory/story-tools-composer/blob/master/app/layers/layerOptionsSvc.js#L25

**Comment by darinacosta** [comment]
NTS: why is style undefined here? https://github.com/MapStory/story-tools/blob/master/lib/ng/edit/style/controllers/controllers.js#L94

**Comment by trepagnier** [comment]
NTS: why isn't this being called when the style is changed from the modal?: https://github.com/MapStory/story-tools/blob/master/lib/ng/edit/style/controllers/controllers.js#L92

**Comment by trepagnier** [comment]
Resolved: https://github.com/MapStory/story-tools-composer/commit/8ca995e7ba2c6aeaa4de4af23e603e46fe5266f3
