### ISSUE TITLE
Layer views remains at 0

### ISSUE THREAD

**Issue by goudine** [MapStory/mapstory#1207]
Each layer has a “views” count, however it often remains at 0

<img width="178" alt="incorrect_views" src="https://user-images.githubusercontent.com/17364268/35361797-920e51a2-0117-11e8-92c9-a1af09ec29eb.png">

**Comment by emilyashley** [comment]
@goudine layer views are counted if you are non-admin and non-owner of a resource. Do you have more than 2 users in your local deployment?

**Comment by goudine** [comment]
Okay that explains it.
I knew i have seen views tallied, but (above) was using `admin` account therefore views weren't being tallied
