### ISSUE TITLE
Importer fails if there is an `ogc_fid` attribute field in data schema. 

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1211]
When attempting to upload a zipped shapefile (which was a subset of data from a downloaded StoryLayer),  an empty schema was generated. After further investigation this was caused by a runtime error cuased by the presence of an `ogc_fid` attribute field. 

Reference issue #1079

**Comment by copaskevin** [comment]
@lhcramer what is the solution to fix this?  If I assigned it to a developer what do they need to get it to function correctly?

**Comment by lhcramer** [comment]
having some check at the upload stage of importer to check if the `ogc_fid` field is present and then use a python library like `shapely` or `geopandas` to remove the attribute field before proceeding with the import stage

**Comment by Coop56** [comment]
The version of importer we use is behind - changes have been made recently.  So I'll have to bump our version of importer before I do this just FYI.  That will add to the storypoints.
