### ISSUE TITLE
Add default Mapstory styles to dev

### ISSUE THREAD

**Issue by goudine** [MapStory/mapstory#1222]
Please upload these default SLD styles to dev geoserver instance:
[Mapstory_styles.zip](https://github.com/MapStory/mapstory/files/1679538/Mapstory_styles.zip)

**Comment by cuttlefish** [comment]
Apparently the styles exist in `$DATA_DIR/styles/` but GeoServer doesn't acknowledge them.

**Comment by lhcramer** [comment]
is it a problem with the original SLDs? they were created in QGIS and i uploaded them to Prod GeoServer manually. Maybe export them from prod directly?

**Comment by cuttlefish** [comment]
It seems that the SLDs are fine, there just need to be XML files associated with them. There seem to be some, but they don't start with `default_`. I'll try just duplicating those and seeing if that works.

**Comment by goudine** [comment]
Would it be possible to keep the naming scheme as `Generic_Mapstory_[Line/Point/Polygon]`?
If not its okay, i will need to change PR as it checks for that specific SLD and if not present uses the `generic` SLD in Geoserver

**Comment by cuttlefish** [comment]
Building GeoServer takes _forever_

**Comment by goudine** [comment]
SLDs are now present in Geoserver `styles` directory, thanks @cuttlefish
