### ISSUE TITLE
Geogig History text needs updating for agnostic branding and product changes. (i.e. {{application_name}})

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#1267]
<img width="957" alt="screen shot 2018-03-12 at 1 47 05 pm" src="https://user-images.githubusercontent.com/15912063/37303259-ea7273f6-25fb-11e8-81bc-d68c5443fc5c.png">

- Address use of `application_name` in MapLoom (might scope OUTSIDE of this LayerHistory context/ticket as well) [here](https://github.com/MapStory/MapLoom/blob/feature/composer-wip/src/app/locales/en.js#L3)

- Editing no longer occurs in Composer. Update to something like "Layer Editor" [here](https://github.com/MapStory/MapLoom/blob/feature/composer-wip/src/app/locales/en.js#L70)
```
    'added_1_feature': 'Added 1 feature to \'{{layer}}\' via {{ application_name }} Composer.',

    'modified_1_feature': 'Modified 1 feature in \'{{layer}}\' via {{ application_name }} Composer.',

    'modified_x_features': 'Modified {{num}} features in \'{{layer}}\' via {{ application_name }} Composer.',

    'removed_1_feature': 'Removed 1 feature from \'{{layer}}\' via {{ application_name }} Composer.',

    'applied_via_maploom': 'Applied via {{ application_name }} Composer.',
```

- Make sure to do so for both the en & es files for translation.

**Comment by lhcramer** [comment]
"Layer Editor" or simply "Editor" are good. Layer Editor is probably the better of the two.

**Comment by emilyashley** [comment]
Closed with https://github.com/MapStory/MapLoom/commit/17ea08b84e4681acbdd20cb3b3f935fda957b7f7

similarly to the other issue I'm closing today (#1266 ) I want to note that the solutions affect _new_ changes to layers but won't immediately change language in _prior_ edit history.
