### ISSUE TITLE
Add Legend to Composer

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#1277]
maploom has a functional legend
i believe it makes a request to geoserver with the layer name as a query parameter
and gets back a png file
if you could do some research into what that request is
it may be in the geoserver docs
thatd be a huge help
and if you want to take it a step further and actually build out a legend ui component, even better

**Comment by josellausas** [comment]
Found the docs for requesting a legend from geoserver: http://docs.geoserver.org/stable/en/user/services/wms/get_legend_graphic/index.html

TLDR; Example request:
```
http://localhost:8080/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=topp:states
```

**Comment by jonpmarino** [comment]
i recognize significant changes to Legend need a spec and a spike, but curious if w/in current deployment it'd be too difficult to just increase the default height for legend? Its currently pretty short. For example, in this chapter I have a layer styled w/ Unique and a color for each of the 50 states. The legend-height is such that 3 states show up, and require significant scrolling.
![screen shot 2018-06-11 at 5 28 10 pm](https://user-images.githubusercontent.com/2573761/41260702-250cd184-6d9e-11e8-91e7-86f8fe028756.jpg)

**Comment by Coop56** [comment]
How large would you want it to be?  All 50 states would take up the entire length of the screen I imagine.
