### ISSUE TITLE
Investigate Chapter Info Sidebar

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#1278]
There is a small blue arrow beside each chapter in the Composer Table of Contents. When you click it, it opens a 404 page in a separate tab. What do we want the behavior to be here? Should it display the chapter description beneath the chapter header bar, accordion style (if so, look at the layer sidebar for an example of how to implement this)? Should it not be there? Ask Laurence Cramer or John Marino. Whatever it is they would like to see happen, investigate how to implement it. The arrow I'm referring to is displayed in the bottom right: https://imgur.com/a/VjWvE

**Comment by Coop56** [comment]
This is no longer relevant, that blue arrow now takes you to the chapter in question properly.  Closing.
