### ISSUE TITLE
Various UI/UX Issues

### ISSUE THREAD

**Issue by WillPapper** [MapStory/mapstory#128]
Major:
- [ ] The “What” option under “Refine Search” section on the Explore page does not show any results
  Test URL: http://mapstory.org/search/?limit=100&offset=0&is_published&category__identifier__in=geopolitics&q=
- [ ] The “Where” option under the “Refine Search” section on the Explore page does not have any effect Test URL: http://mapstory.org/search/?limit=100&offset=0&is_published&q=&extent=-126.21093749999999,49.95121990866204,-104.0625,64.09140752262307
- [ ] Adding a tag causes a published map to become unpublished

Minor:
- [ ] Featured maps carousel on the homepage shows “No Featured Items in this Category” and template info before loading is complete
  Test URL: http://mapstory.org/
- [ ] Explore page shows "page 1 of NaN” before loading is complete
  Test URL: http://mapstory.org/search/?limit=100&offset=0&is_published
- [ ] The info@mapstory.org email in the “Building a Better MapStory” message should be a mailto: or a contact form
  Test URL: http://mapstory.org/account/login/?next=/maps/new%3Ftour
  Parent div ID is “site_wide_announcements"
- [ ] Two different scrolling methods are used for the whole Explore page and the available StoryLayers. Maybe merge into one and consider infinite scrolling? This is a small point.
  Test URL: http://mapstory.org/search/?limit=100&offset=0&is_published
- [ ] The Explore page tries to load http://mapstory.org/static/lib/js/bootstrap-datepicker.js, but it gives a 404
  Test URL: http://mapstory.org/static/lib/js/bootstrap-datepicker.js
- [ ] [“No Image” placeholder](http://mapstory.org/static/geonode/img/missing_thumb.png) could be improved. Maybe a light grayscale map?
  Test URL: http://mapstory.org/static/geonode/img/missing_thumb.png
- [ ] Long titles overflow on the Explore page. Truncating and showing the full title on rollover is probably the best option.
  Test URL: http://mapstory.org/search/?q=Test&limit=100&offset=0&is_published
  Image:
  <img width="916" alt="screen shot 2015-10-16 at 2 09 21 pm" src="https://cloud.githubusercontent.com/assets/1622331/10699851/6a0aa830-797f-11e5-88dd-e0ae3ae2c882.png">
- [ ] Keyword option on the Explore page is unclear and does not seem to function.
  Image:
  <img width="359" alt="screen shot 2015-10-16 at 2 13 11 pm" src="https://cloud.githubusercontent.com/assets/1622331/10699861/78f06a7e-797f-11e5-86b2-5affb38e76fa.png">
- [ ] “Remember Me” checkbox is slightly misaligned. This appears to be a bug with default browser behavior on Chrome and Safari, though it is possible to override it with custom styling.
  Image:
  <img width="493" alt="screen shot 2015-10-16 at 2 15 07 pm" src="https://cloud.githubusercontent.com/assets/1622331/10699866/831aafa0-797f-11e5-887d-16fdd8babd2b.png">
- [ ] Labels under the StoryStyles section on the Compose page are cramped.
  Image:
  <img width="392" alt="screen shot 2015-10-16 at 2 20 55 pm" src="https://cloud.githubusercontent.com/assets/1622331/10699905/c7008db6-797f-11e5-9daa-6e194654769a.png">
- [ ] StoryBox editor on the Compose page needs alignment and text cleanup.
  Image:
  <img width="824" alt="screen shot 2015-10-16 at 2 25 23 pm" src="https://cloud.githubusercontent.com/assets/1622331/10699910/ce407758-797f-11e5-8834-5c5140729f19.png">
- [ ] On the map preview page, it would probably be clearer to have “Save as Draft” and “Publish” instead of a publish/unpublish checkbox. The save button is also very low contrast.
  Image:
  <img width="508" alt="screen shot 2015-10-16 at 2 27 47 pm" src="https://cloud.githubusercontent.com/assets/1622331/10699915/d6a4582e-797f-11e5-9a6d-a849c5b7d70e.png">
- [ ] Message for adding a keyword on the map edit page is missing a closing paren. Current text is "commonly used word(s) or formalised word(s) or phrase(s) used to describe the subject (space or comma-separated"

**Comment by glynnis** [comment]
Closing this given the redesign work underway and the age of this issue.
