### ISSUE TITLE
Fetch Storypins from API

### ISSUE THREAD

**Issue by josellausas** [MapStory/mapstory#1295]
StoryPins are not being fetched back from the server, which means they won't show up in viewer or if you open a draft.

**Comment by josellausas** [comment]
Known issue: mapstory/story-tools-composer#121

**Comment by jonpmarino** [comment]
I don't see the storypin pop-up information showing up for a Pin on a published story. This story has a pin with text in pop-up in chapter 2: https://staging.mapstory.org/story/testing-styling-persistence/. If someone else could do a second opinion check, please do. Could be something with my browser.

**Comment by cuttlefish** [comment]
Quoting @jonpmarino:

> tangentally, when i click "changed published story" button on the published story and return to composer, the storypin is still there but the start-date and end-date I entered are lost.
