### ISSUE TITLE
Composer and Viewer playback expand/minimize bug

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#1297]
Reported by @darinacosta:

Playback settings hidden due to the following bug: when you click the “playback settings” gear, the options don’t appear correctly; they show up below the map. Looks like a styling issue.

**Comment by goudine** [comment]
Gear (playback options) icon is hidden by default. 
Edit `/deps/story-tools-composer/app/time/style/time.less` to have 

```
button[data-target='#playback-settings'] {
  display: inline;
}
```
Note: time enabled story layer needs to be added for icon to show

Html for menu options is found in `/deps/story-tools/lib/templates/core/time/playback-controls.html`

Ideal behaviour for playback options is same as seen in [Toggle Timeline](https://github.com/MapStory/story-tools/blob/4b6bf31abe71fd3691ce5f175014917decda76c8/lib/templates/core/time/playback-controls.html#L13-L14)

**Comment by jonpmarino** [comment]
Do we need 2 separate issues for playback settings in composer and in the publish/viewer? Or is it implied that playback setting should work in composer and in the viewer on published stories?
