### ISSUE TITLE
Triggers for generation of Story thumbnails

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#1304]
Code exists for generating thumbnails for Stories, but it hasn't been wired up to trigger automatically yet.

I believe this completes #1188

**Comment by DBlasby** [comment]
Yes - just needs to connect up and verify signals (esp elastic being told about it). 

Will need final testing.

**Comment by cuttlefish** [comment]
While doing this, the equivalent of #1247 should be done for stories.

**Comment by goudine** [comment]
Verified on [staging](https://staging.mapstory.org/) instance of Mapstory

<img width="1123" alt="screen shot 2018-04-16 at 9 18 27 am" src="https://user-images.githubusercontent.com/17364268/38822112-5037936c-4157-11e8-9c15-89e6550c2890.png">
