### ISSUE TITLE
Host Font Awesome locally in Composer

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#1307]
Font Awesome is included here: https://github.com/MapStory/story-tools-composer/blob/master/index.html#L41

We'll need to host it locally rather than include it via a CDN.

**Comment by cuttlefish** [comment]
Also see https://github.com/MapStory/story-tools-composer/issues/50

**Comment by cuttlefish** [comment]
How's the issue coming? It's likely to cause us some grief on restricted networks.

**Comment by goudine** [comment]
Haven't had a chance to look at this one yet this sprint
