### ISSUE TITLE
Add Save Notification to Composer

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory#1318]
Add Save Notification message - currently the user isn't alerted when a save is successful or if it fails.

**Comment by goudine** [comment]
Added a notification modal which appears after clicking Save in Composer mode.
Does not actually check if save was successful or not as there are some other issues at play.

Needs further investigation.

https://github.com/MapStory/story-tools-composer/pull/197

**Comment by jonpmarino** [comment]
Note - am working on a story on staging w/ Chrome browser. Clicking save in composer doesn't appear to provide any user feedback. Here's screenshot of story-in-process w/ URL. Date of test - June 11.

![screen shot 2018-06-11 at 5 28 10 pm](https://user-images.githubusercontent.com/2573761/41260419-f7281dce-6d9c-11e8-96c7-3f3cc0ce894c.jpg)

**Comment by Coop56** [comment]
This issue is still in the backlog, it hasn't been completed yet.

**Comment by jpierson-boundlessgeo** [comment]
Move the Save notification to the end of the promise chain

**Comment by Coop56** [comment]
Now that we've refactored saving, we can actually complete this issue with notifications that are correct and alert the user whether their save succeeded or failed.  Whoever gets this issue, please reach out to me and I can show you where the notification needs to go.
