### ISSUE TITLE
Mitigate problems with search

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#1325]
Seed IDs in tables which do _not_ inherit from resource_base with disparate values.
The goal is to prevent the IDs from stomping on each other in the Elastic Search index.

This should be a temporary measure. We can remove it once the Elastic Search problems are resolved.

**Comment by josellausas** [comment]
https://stackoverflow.com/questions/16663586/set-auto-increment-initial-value-for-id-in-django-model
