### ISSUE TITLE
Investigate Remote Services (OGC Layers)

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1338]
Check to see if core-geonode Remote Services works in a stand alone deployment verse a MapStory Deployment. 

- [ ] If core-geonode is non-operational, note that in this ticket and create a spike to implement in MapStory/Upstream geonode. 

- [ ] If core-geonode is operational and not on mapstory. Ticket the error messages within the MapStory environment.

**Comment by jpierson-boundlessgeo** [comment]
As a user, I want to be able to open an OGC compliant layer (WFS) that contains a temporal attribute and use it as a StoryLayer in StoryScapes for search and story composition.  Also, as a user I want to be able to consume an OGC compliant layer (WMS) to use as a basemap or static layer in a StoryScape

**Comment by jpierson-boundlessgeo** [comment]
MVP Document describes the OGC Layer Import features as:

Shared OGC layers inputs: StoryScapes can accepts shared OGC complaint layers

Conversation with customer on 5/31 confirms that for MVP, OGC layers is limited to WMS.
