### ISSUE TITLE
Loop Story causes story to re-start and break

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1343]
Playback/preview mode:
Loop chapter works. But “Loop story” generates this screen when a chapter transition hits:

![image.png](https://images.zenhubusercontent.com/5ad4ece44b5806bc2bcf5287/f1b75d88-2ab4-4b40-bcba-7031924d9cb9)

**Comment by jonpmarino** [comment]
Note - we also need to account for the use-case in Loop Story when the story has embedded media in a StoryPin. How can we allow for the media in a storypin to play automatically, without requiring the person viewing the story to hit "play'. Solving this problem will make "museum mode" possible.

**Comment by jonpmarino** [comment]
The updated issue is that when the Chapter reaches an end, the story reverts to composer inside the viewer. See screenshot;

![screen shot 2018-07-10 at 11 33 29 am](https://user-images.githubusercontent.com/2573761/42524092-1c2dbc6a-8435-11e8-809a-a7ae0bf1145b.jpg)
