### ISSUE TITLE
StoryScapes Classification Banner

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1365]
As a user, I should see a classification banner on each page of StoryScapes showing the default classification level of the deployed system.

This has already been implemented in Exchange, may be able to re-use that code.

**Comment by cuttlefish** [comment]
Additional requirements:
Banners on both the top and bottom of the window.
Banners are fixed in view when scrolling.

**Comment by jpierson-boundlessgeo** [comment]
Banner's do not display in Editor on whitelabel.  Look good everywhere else, though

**Comment by cuttlefish** [comment]
Editor should be displaying the banners now.

The padding isn't working on Composer and Editor, but it'll take a fair bit to get working so I think we should leave it for now.
