### ISSUE TITLE
Fortify Scans

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1366]
Evaluate Fortify Scan results for StoryScapes and work with Theresa P (Boundless ISSE)

1) Identify and document false positives for critical and high
2) Identify items that can be fixed for critical and high
3) Provide justifications for items that cannot be fixed in criticals and high

**Comment by Coop56** [comment]
The scans are now properly scanning all of the files that we want them to, and I resolved 9 of the critical errors.  Moving this back to backlog as I've been retasked to another issue.
