### ISSUE TITLE
Implement Audit Logging

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1367]
StoryScapes needs to maintain system logs and expose those for consumption by the NGA enterprise system.

**Comment by cuttlefish** [comment]
Auditable Events or Activities

**Authentication events** 

- [x] Logons (Success/Failure) 
- [x] Logoffs (Success) 

**File & Object Events** 

- [x] Create (Success/Failure) 
- [x]  Access (Success/Failure) 
- [x] Delete (Success/Failure) 
- [x] Modify (Success/Failure) 
- [ ]  ~~Permission Modifications (Success/Failure)~~ 
- [ ] ~~Ownership Modifications (Success/Failure) ICS 500-27~~ 


**User & Group Management events** 

- [ ] ~~User add, delete, modify, suspend, lock (Success/Failure)~~ 
- [ ] ~~Group/Role add, delete, modify (Success/Failure)~~ 

**Use of Privileged/Special Rights events** 

- [ ] ~~Security or audit policy changes (Success/Failure)~~ 
- [ ] ~~Configuration changes (Success/Failure)~~ 

**Additional Events**

- [ ] ~~Writes/downloads to external devices/media (e.g., A-Drive, CD/DVD drives, printers) (Success/Failure)~~
- [ ] ~~Uploads from external devices/media (e.g., CD/DVD drives) (Success/Failure)~~
- [ ] ~~Admin or root-level access (Success/Failure)~~
- [ ] ~~Privilege/Role escalation (Success/Failure)~~ 
- [ ] ~~Audit and log data accesses (Success/Failure)~~
- [ ] ~~System Reboot, Restart & Shutdown (Success/Failure)~~
- [ ] ~~Print to a device (Success/Failure)~~
- [ ] ~~Print to a file (e.g., pdf format) (Success/Failure)~~
- [ ] ~~Application (e.g., Netscape, IE, Lotus Notes, etc.) initialization (Success/Failure)~~ 
- [ ] Export of information (Success/Failure) 
- [ ] Import of information (Success/Failure)

**Auditable Event Details/Information Elements**

- Date and time of the event using the common network time (e.g., Network Time Protocol). • Type of the event (e.g., login, print, etc.) 
- Identifier indicating the source/system of the event activity. 
- Identifier indicating the identity of the subject or actor (e.g., Userld, Processld, etc.) 
- Details identifying any objects or resources accessed or involved (aka Resource List), e.g., files (including location), document id, peripherals, storage devices, etc. 
- Outcome (e.g., Success or Failure).

**Attributable Events Indicating Violation of System/target**

- [ ] ~~Malicious code detection~~ 
- [ ] ~~Unauthorized local device access~~ 
- [ ] ~~Unauthorized executables~~ 
- [ ] ~~Unauthorized privileged access~~ 
- [ ] ~~After-hours privileged access~~ 
- [ ] ~~System reset/reboot~~ 
- [ ] ~~Disabling of the audit mechanism~~ 
- [ ] ~~Downloading to local devices~~ 
- [ ] ~~Printing to local devices~~ 
- [ ] ~~Uploading from local devices~~

- [ ] ~~"Events" of concern that require further analysis or review of additional information or events. Some of these may require tools or utilities (e.g., malicious code detection).~~

Strikethrough indicates that these are server level logs that our application can't deal with and will be handled by PaaS.
