### ISSUE TITLE
Fix `Create StoryLayer` UI

### ISSUE THREAD

**Issue by goudine** [MapStory/mapstory#1379]
**Bug**:
During `Create StoryLayer` the thumbnail at top right corner does not load.
<img width="1168" alt="create_layer_ui" src="https://user-images.githubusercontent.com/17364268/40629225-9c929f70-627e-11e8-964a-c1d401ff27c9.png">

**Improvement**:
On both the former and the latter screenshot `StoryLayer` is a hyperlink to move onto the next step in layer creation.
This is difficult to notice and should be highlighted by increasing font size, changing colour, or making it a visible button.
<img width="1226" alt="create_layer_ui-2" src="https://user-images.githubusercontent.com/17364268/40629243-b939eade-627e-11e8-956a-175faa876e90.png">

**Comment by cuttlefish** [comment]
This is an issue related to some of the white labelling changes. This logo is probably still being loaded from what's specified in the django admin panel. In other places they are being hardcoded based on the orange or blue themes.
