### ISSUE TITLE
Fix `Add Feature` during `Create StoryLayer `

### ISSUE THREAD

**Issue by goudine** [MapStory/mapstory#1380]
When user selects `Create StoryLayer` there is an option to add more columns to the attribute table for the layer.

<img width="610" alt="adding_field" src="https://user-images.githubusercontent.com/17364268/40629554-cb7e6060-6280-11e8-8f32-9cfc3bf22a29.png">

If user decides to add new field, there will be save error during `Add Feature`

<img width="452" alt="adding_feature" src="https://user-images.githubusercontent.com/17364268/40629574-f17d247c-6280-11e8-87af-b37d83818c37.png">
<img width="491" alt="save_error" src="https://user-images.githubusercontent.com/17364268/40629577-f58debb4-6280-11e8-9740-f78ef559cb93.png">

If adding feature to layer which does not have extra columns added then no error.
<img width="788" alt="attribute_table_default_layer" src="https://user-images.githubusercontent.com/17364268/40629607-43a3376e-6281-11e8-843d-7edc0a16da04.png">

**Comment by Coop56** [comment]
@goudine This is not always the case.  Try different field names to narrow down what the problem may be.  I added some fields earlier that were just one word for the field name that worked fine.

**Comment by goudine** [comment]
I will double check to see in what circumstances I am able to `save` with extra added fields.

In the above example "insert string here" was something I typed just for the screen shot so that it would be clear that there was an attempt to insert a string into the text box. (before that it error'ed with something like "`testing`")
