### ISSUE TITLE
Where is content to explore?

### ISSUE THREAD

**Issue by nittyjee** [MapStory/mapstory#1381]
Not sure if it's okay to write something in the form of a question.
Also not sure if this has been ticketed, there are 200 to go through and I'm only getting into this now.

There's nothing here, and I can't search for anything:
https://mapstory.org/search/

I litererally can't find any Storylayers or MapStories anywhere.

**Comment by lhcramer** [comment]
@cuttlefish, reindexed elastic search to fix the issue.
