### ISSUE TITLE
Upgrade to Geonode 2.8.0

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory#1389]
Items that need fixed post 2.8.0 upgrade that don't have their own tickets.

- [x] Had to remove forgot password, this will need reimplemented.
- [x] Had to remove account password change from template, will need reimplemented. 
- [x] Layer imports are broken. 
- [x] The login / register modal is also broken.
- [x] Templates are broken. 
- [x] Saving stories is broken. 
- [x] Create layer is broken.
- [x] Layer preview is broken, it won't display the layer due to a JS error.

**Comment by cuttlefish** [comment]
Celery config has been updated. It at least runs and logs to the console properly.
