### ISSUE TITLE
GeoNode 2.8 and WMS layers

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#1390]
Epic encompassing all of the work necessary to implement the OGC services requirement.

**Comment by jpierson-boundlessgeo** [comment]
MVP Document describes the OGC Layer Import features as:

Shared OGC layers inputs: StoryScapes can accepts shared OGC complaint layers

Conversation with customer on 5/31 confirms that for MVP, OGC layers is limited to WMS.
