### ISSUE TITLE
Validate addition of non-temporal WMS layer to a Story in the Composer

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1394]
Test to see if adding a layer that does not have a temporal component (specifically an OGC WMS layer) actually works in Composer and does not break anything in viewing a Story

**Comment by jpierson-boundlessgeo** [comment]
Confirmed that adding remote layer does not work (undefined layer error).  Need to make it work.

**Comment by jpierson-boundlessgeo** [comment]
Need to add WMS URL and any other relevant pieces to Search API.

**Comment by Coop56** [comment]
@darinacosta and I worked on this today, he now has a function that he can hit to get the remote URL.
