### ISSUE TITLE
Trouble shoot GeoNode Remote Services implementation

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1408]
Remote services work in core GeoNode 2.8.0, but not in MapStory.  Appears to be a front-end JavaScript issue.  Need to determine and resolve the issue.

**Comment by trepagnier** [comment]
Relevant bits: 

View for registering the service
https://github.com/GeoNode/geonode/blob/master/geonode/services/views.py#L77

Service form model
https://github.com/GeoNode/geonode/blob/master/geonode/services/forms.py

Template for registering the service
https://github.com/GeoNode/geonode/blob/master/geonode/services/templates/services/service_register.html
