### ISSUE TITLE
On call support for import failures

### ISSUE THREAD

**Issue by nittyjee** [MapStory/mapstory#1412]
Get the following error when uploading both a zipped shapefile (3.7MB) and csv (32kb):
_"We're sorry but our import service is currently unavailable. Please try again later."_

For most issues I will simply ticket them.
But for some I will both ticket and whine and complain. Not towards anyone(s) in particular. Put yourself in my, and any user's shoes.

Step 1 for a user is both:
View data.
Upload data.

As has been the case 95% of the time for everything I have tried over the last 3-4 years, I can't get through Step 1.

This will work reliably 100% of the time for everything I upload to the data demo, which is only of Step 1 (local.mapstory.org), which I had to make to get past Step 1 to actually do my job and demo my data, as a content director and user who is ultimately waiting for MapStory to work enough to get past Step 1.

Step 1, viewing and uploading, must work 100% of the time, and if it doesn't, nothing else matters, because fundamentally then nothing exists for a user. This is the only priority if it does not work and there is any chance it will not work. This is perfect logic.

I know I am not a developer, and we are building this from scratch, but... don't care. It's a lot to ask me to cut any slack for this long. Fix this now, fix it always, fix it before and not after, fix it forever.

**Comment by Coop56** [comment]
Can you attach the datasets that you're trying to import to this issue please?

**Comment by nittyjee** [comment]
Cougar points:
[cougar_timeline.zip](https://github.com/MapStory/mapstory/files/2070468/cougar_timeline.zip)

**Comment by nittyjee** [comment]
Manhattan Parcels:
[MNMapPLUTO.zip](https://github.com/MapStory/mapstory/files/2070470/MNMapPLUTO.zip)

**Comment by Coop56** [comment]
Thanks.  Whenever this ticket gets included into a sprint those datasets will be helpful in figuring out what the problem is.

**Comment by jonpmarino** [comment]
@Coop56 what do you think? My suggestion is that @nittyjee create a separate ticket for each dataset from MapStory Local demo (local.mapstory.org) that he is failing to upload on mapstory.org. Each ticket can include screenshots of any error messages and the dataset attached. This will let us work through them systematically when they get into a sprint. If we find that several are failing for a common reason, we can create a separate ticket with that knowledge and close the dataset-specific ticket(s).
