### ISSUE TITLE
Actually top priority - Mapstory.org opens as "Not Secure"

### ISSUE THREAD

**Issue by nittyjee** [MapStory/mapstory#1414]
When I open mapstory.org in chrome, it says _"Your connection to this site is not secure."_
It does not open the site, but you can click a drop down and click to "Proceed unsafely" or something.

I know I said Step 1 was uploading and viewing... but I suppose Step 0 is to open the site, which I never considered as an issue. So, this is actually the top priority. A user can open it, but most users might not know how to and get confused or apprehensive, and not even use the site.

Hopefully this is quick?

**Comment by Coop56** [comment]
The SSL certificate needs renewed, this is outside of the developers hands.  I've let Jon know.
