### ISSUE TITLE
Bad JSON in layer_acls_mapstory view

### ISSUE THREAD

**Issue by josellausas** [MapStory/mapstory#1423]
- The file is `mapstory/mapstory/views.py`. 
- The function is `layer_acls_mapstory()`
- The error:

![Screen Shot 2018-06-07 at 10.04.45 AM.png](https://images.zenhubusercontent.com/5ad4fed04b5806bc2bcf554a/55d4d6d4-16a2-422f-ac6e-3c5f6607e3be)

**Comment by josellausas** [comment]
![screen shot 2018-06-07 at 12 15 46 pm](https://user-images.githubusercontent.com/4162671/41115250-8feb8d10-6a4c-11e8-8d5e-4fb27cb3fc9c.png)

**Comment by Coop56** [comment]
This no longer occurs now that we've updated to Geofence.
