### ISSUE TITLE
Setting up docker, chrome https issue

### ISSUE THREAD

**Issue by zshanhui** [MapStory/mapstory#1428]
When I go to http://docker, chrome warns me about an unsafe site. Then after proceeding, I see Nginx 502 error.

Still unable to get this running.

Also, there's a lot of containers docker is running and my machine is having a hard time handling it. Do I really need to have all the containers running (RabbitMQ, Elastic, etc...), or just the core app? It's quite heavy.

Would like to contribute, but having some difficulties setting up the env.

**Comment by cuttlefish** [comment]
The developer setup uses self-signed certificates, so it's expected that you get cert warnings. You can accept them in chrome or add https://github.com/MapStory/mapstory/blob/master/docker/nginx/docker.crt to prevent them.

`docker-compose ps` should tell you if containers are running. Some are expected to close with a 0 exit status. For annoying reasons, it usually takes the django container several minutes to come up fully. Docker can't tell the difference between a container that's up and one that's coming up.

We currently do not have an environment configured that doesn't require RabbitMQ, Elastic, etc.
doing a `docker-compose up nginx` should give you the minimal subset. `docker-compose up` will bring up a few that you don't need.

**Comment by zshanhui** [comment]
Alright, will give it a try this weekend and let you know if it works.
