### ISSUE TITLE
General Layer Permissions Problems

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory#1437]
Only admins can currently view layers, all others get permissions errors from geoserver.

**Comment by jpierson-boundlessgeo** [comment]
Layer permissions for any user but admin don't work in MS/SS.  Hopefully GeoFence implementation will resolve.

**Comment by cuttlefish** [comment]
Can anyone verify where we're at with this issue?

**Comment by jpierson-boundlessgeo** [comment]
This looked fine in testing yesterday.  I could view layers imported by other users.

**Comment by jpierson-boundlessgeo** [comment]
Still holds true on this mornings deployment.

**Comment by Coop56** [comment]
This is working, moving it over to review.

**Comment by jonpmarino** [comment]
currently an issue again. re-opening.
