### ISSUE TITLE
Cannot delete a MapStory/StoryScape

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1439]
"Delete this StoryScape" (or MapStory) button on the story page (/story/<storyname>) does not appear to do anything.

**Comment by jonpmarino** [comment]
In testing of lab on July 10th, delete story appears to work. Should get a second opinion before closing this issue.

**Comment by jpierson-boundlessgeo** [comment]
Jon saw it work in Chrome, but in Firefox, the Delete Mapstory button does nothing

**Comment by jpierson-boundlessgeo** [comment]
Works in Safari and confirmed that it works in Chrome.  Also, the delete profile button does not work in FireFox (but just Firefox as well)
