### ISSUE TITLE
User cannot edit geometry shapes or change their location

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1450]
(testing done in lab.mapstory.org with Chrome on July 10)

As a user when I click "edit geometries" on a feature while in the layer editor, I expect to be able to make edits to the feature's outline geometry (for polygons) or to move the feature location altogether (mostly for points). 

Currently in the layer editor when I click "edit geometries" the drawing tool comes up, but the user cannot select features and make the desired changes.

Here is an example point layer. The user should be able to move the location of the point but cannot select the point and move it.

![Screen Shot 2018-07-10 at 1.48.33 PM.jpg](https://images.zenhubusercontent.com/5ad609ee4b5806bc2bcf750b/b7a9e2d5-40e9-4ddb-b872-9cbcd2d8c9ff)

Here is an example of a polygon layer. The user should be able to change the vertices
 of the selected polygon but is unable to do so.

![Screen Shot 2018-07-10 at 1.48.33 PM.jpg](https://images.zenhubusercontent.com/5ad609ee4b5806bc2bcf750b/70f2d2fb-7f0a-44ea-af8d-f65877a28881)

**Comment by jonpmarino** [comment]
Using lab.mapstory on July 10, using Chrome, also when using the "add to feature" function we got this error message:

![screen shot 2018-07-10 at 11 52 43 am](https://user-images.githubusercontent.com/2573761/42525269-52350fe0-8438-11e8-9500-20bdef314a1c.jpg)

**Comment by j-meyer** [comment]
https://github.com/MapStory/MapLoom/pull/50

![point_edit](https://user-images.githubusercontent.com/205525/42893802-53ad0228-8a83-11e8-85d9-44cf14d2c700.gif)
![polygon_edit](https://user-images.githubusercontent.com/205525/42893803-53bdf538-8a83-11e8-81f6-592e9e61c5db.gif)
