### ISSUE TITLE
Update BOSH release to remove --collect-static at startup

### ISSUE THREAD

**Issue by DerekSedlmyer** [MapStory/mapstory#1471]
Currently the docker-compose up will run --collect-static that requires access to the internet to install libraries. This needs to be removed in order to support deployments without internet access.

**Comment by Coop56** [comment]
The standard --collect-static no longer reaches out to the internet, only the --collect-static-dev does so I'm closing this issue.

**Comment by jpierson-boundlessgeo** [comment]
Is this redundant with any other issues we've just opened for this Epic?

**Comment by cuttlefish** [comment]
It's part of #1687
