### ISSUE TITLE
Configurable basemaps

### ISSUE THREAD

**Issue by DerekSedlmyer** [MapStory/mapstory#1473]
Currently the Basemaps in Storyscapes reaches out to the internet. This won't work for secure environment deployments.

The request here is to make the Basemaps configurable via the Admin panel. Basemaps can then be adjusted per deployment.

**Comment by Coop56** [comment]
We'll need two environment variables for this.  We'll need one that allows the deployment to choose what basemaps get loaded into the system by default and another that allows the deployment to choose what basemap gets used for thumbnails.  Both of these values are currently hard coded to public facing sites that secure deployments won't be able to hit.

**Comment by jpierson-boundlessgeo** [comment]
Better solution would be to make it configurable within the Django admin panel.  Will also need to have thumbnail basemap be configurable as well.
