### ISSUE TITLE
Admin password reset to default on restart

### ISSUE THREAD

**Issue by DerekSedlmyer** [MapStory/mapstory#1475]
The admin password is reset to its default after restarting the containers. 

Steps to reproduce:

1. Open storyscapes
1. Login as admin
1. Go to Admin panel | Users
1. Change password for admin user. Django Admin will prompt for login with new password
1. Restart the containers via `dco up`, `dco down`
1. Open storyscapes
1. Attempt to Login as admin user with new password. Login will not be successful
1. Attempt to Login as admin user with default password. Login will be successful

**Comment by cuttlefish** [comment]
This was mandated once upon a time for... questionable reasons. 😣 

Are you happy with adding an entry to `../secrets/env`?

**Comment by DerekSedlmyer** [comment]
We need to ensure that the password isn't reset to a default when the system is restarted.

**Comment by DerekSedlmyer** [comment]
Tested successfully on BEAST.
