### ISSUE TITLE
Can't enter data into the story frame title field at first.  (Only seems to happen in a draft)

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1487]
1) cannot enter text into frame title area.

**Comment by jonpmarino** [comment]
closing. validated on whitelabel

**Comment by jonpmarino** [comment]
re-opening and re-titling this earlier issue to track the same issue that the user sometimes can't enter the title for a storyframe. appears to be most common in a draft.

**Comment by shawnkendrick** [comment]
- Form works prior to saving
- Form works after saving in draft state IF there is already and existing saved frame
- Form is not working in draft mode if a frame was not previously saved
