### ISSUE TITLE
Remove "Share Section"  (iframe embed fails)

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1488]
On whitelabel, for a story,

using the iframe embed link generated under share tab,

![screen shot 2018-08-01 at 3 06 10 pm](https://user-images.githubusercontent.com/2573761/43545852-9e870b94-959c-11e8-9c41-af68cf953421.jpg)

results in the following template error,

![screen shot 2018-08-01 at 3 06 47 pm](https://user-images.githubusercontent.com/2573761/43545842-96ddb1cc-959c-11e8-9818-3850997fce0b.jpg)

**Comment by lhcramer** [comment]
We are going to changes this to remove the share section within StoryScapes deployments
