### ISSUE TITLE
styling fails for non-admin accounts

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1489]
whitelabel

**Comment by lhcramer** [comment]
Errors in the console log show `Post 500` and `Put 403`  error when attempting to change the styles

**Comment by jpierson-boundlessgeo** [comment]
This is only happening on some layers.  Currently, known layers that do not work are "Chibok Timeline" and "Boko Haram Incidents".

Also, Unique styling is not working.
