### ISSUE TITLE
Edits showing up as anonymous

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1490]
in the edit history, it should show the username not "anonymous".

![Screen Shot 2018-08-01 at 3.23.07 PM.jpg](https://images.zenhubusercontent.com/5ad609ee4b5806bc2bcf750b/8662bc14-a81c-4c96-b7c8-eafb7ed69c21)

**Comment by Coop56** [comment]
This will be resolved once we get the automatic login working between geonode and geoserver.

**Comment by jonpmarino** [comment]
interesting note - when I edit a geometry, its attributed to "anonymous" but when I 'revert' a change, it correctly attributes it to my username, aldoleopold
![screen shot 2018-08-03 at 2 17 31 pm](https://user-images.githubusercontent.com/2573761/43661502-25575f70-9728-11e8-9794-3bc799b58630.jpg)

**Comment by cuttlefish** [comment]
The auth fix for styling didn't resolve this issue. It also doesn't work when logged in as `admin`.
It seems that it applies the username correctly when doing GeoGig API commands, but not when it does WFS-T edits.
I tried adding an `access_token` query parameter to the WFS-T request but it didn't seem to work.
Did this work in the past?

**Comment by cuttlefish** [comment]
This works in Exchange. I'm not sure what they're doing differently. They're not assigning an access_token query param.

**Comment by jpierson-boundlessgeo** [comment]
If you do an authentication against GeoServer first, edits show up as the correct user.

**Comment by jpierson-boundlessgeo** [comment]
Seems to be an issue from WFS-T transactions not getting the correct user assigned.  Also causes the same behavior in Append.

**Comment by jpierson-boundlessgeo** [comment]
The core issue is that our django templates completely overwrite the base GeoNode templates, which work because the permissions are handled within the template.

**Comment by lhcramer** [comment]
Verify 1822 addresses this issue
