### ISSUE TITLE
Layers can only be downloaded as KML

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1492]
whitelabel -

before we were able to download layers in a variety of formats....i.e. csv an shp. Now its only KML

![Screen Shot 2018-08-01 at 4.18.27 PM.jpg](https://images.zenhubusercontent.com/5ad609ee4b5806bc2bcf750b/22a327b9-7ce5-45cc-9d39-ad038e96d57d)

**Comment by jpierson-boundlessgeo** [comment]
Download code is generated by GeoNode?  We may not be modifying it.
