### ISSUE TITLE
Auto playback for storypins with embedded media

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1520]
A user-goal for MapStories is to have the option to play a story from start to end without requiring user intervention. This would allow, for example, a story to be played on a continuous loop in a museum or display. 

The "loop story" functions allows this right now. BUT, stories with storypins that have embedded videos cannot automatically play those videos unless a user is there to pause the story and click "play" on the video.

This issue is a feature enhancement issue to investigate a method that lets a video in a storypin be automatically played if "loop story" is selected. Ideally, there would also be a method for defining the points in the video the video would start and end at (so, for example, if a video is 30 minutes but only 5 minutes desire to be used, the auto start and end could be defined to show that 5 minutes)

**Comment by jonpmarino** [comment]
Hey @j-meyer question > is there any specific workflow rules for the user to make the auto playback work? In this test story on whitelabel i have 1 pin with a youtube media embed. auto-playback box is checked. video does not automatically play though. 

https://whitelabel.mapstory.org/story/test-auto-playback/

Also, i tested making the duration "120" which i assume is seconds but video continued playing beyond 2 minutes once I clicked play. 

The 'offset' does seem to work. When I created an offset of "10" the video does start 10 seconds in when I hit play.

![screen shot 2018-11-07 at 3 58 00 pm](https://user-images.githubusercontent.com/2573761/48163975-cdccce00-e2a6-11e8-891e-b43014b53116.jpg)

![screen shot 2018-11-07 at 4 05 02 pm](https://user-images.githubusercontent.com/2573761/48164006-e937d900-e2a6-11e8-838b-844352582af4.jpg)

**Comment by j-meyer** [comment]
I believe the chapter or story loop needs to be enabled for the video to autoplay, it's a quick fix if you always want it to autoplay, even if the story isn't looping.

**Comment by jonpmarino** [comment]
cool. i think if use clicks auto-play in composer that prob makes sense.

also, this is a separate issue (i will create separate ticket) but could we specify the units in the media offset and media play lengh? i assume its seconds

**Comment by jonpmarino** [comment]
update > looks like 2 separate issues:

1) autoplay should autoplay whenever the user has clicked the check box in composer (even if loop isn't initiated by user)

2) autoplay doesn't work if viewer of story clicks "loop" after the timeline is already going (in other words _after_ viewer has it play). To work, viewer must click loop _before_ clicking play
