### ISSUE TITLE
Complete Django Refactor

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory#1549]
Just as we've begun to do on the frontend, there's a lot of work that can be done to clean up the Python and Django code on the backend.  This ticket would likely encompass many sprints, and should perhaps be an epic.  

Django Refactor Notes

- Remove the apps directory and move the apps within in to the project root based on Django best practices.
- Clean up unused functions, classes and methods.
- Break up the current views.py file into multiple organized apps within the project root.
- Ensure that all unit tests live within their respective apps.
- Modify our current code to ensure it follows all linting and PEP8 standards.
- Refactor the various apps that make up a story currently into one stories app so that we can fix the saving issues. 
- Once all of this is done, we can refactor the actual code itself in all of the apps to improve the overall codebase.

**Comment by lhcramer** [comment]
@Coop56, can you convert #1613 to an epic and detail required steps for GeoNode react bump.

**Comment by lhcramer** [comment]
@Coop56 , are we able to close out this epic?
