### ISSUE TITLE
Research upgrade to ElasticSearch 6.3

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1550]
All versions of ElasticSearch prior to 6.0.0 have been disapproved on NGA's SWAP list.  MapStory/StoryScapes is currently using ElasticSearch 1.6.  Need to determine the level of effort involved in upgrading to ElasticSearch 6.x (probably 6.3 as it's the most recent)

**Comment by jpierson-boundlessgeo** [comment]
Also determine if we can or should remove Haystack as part of this.
This implies a significant refactor of our search API implementation.  Might not even need to use ElasticSearch.  Need to refactor so that client side is not making direct ES searches which is what's being done currently.

**Comment by Coop56** [comment]
This is covered by the refactor search ticket, closing.
