### ISSUE TITLE
Research level of effort to upgrade to RabbitMQ 3.7.x

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1551]
Determine the level of effort necessary to upgrade MapStory/StoryScapes to use RabbitMQ 3.7.x (most recent stable release).  We are currently using version 3.6, which is disapproved software on the NGA SWAP list.

**Comment by jpierson-boundlessgeo** [comment]
Also research feasability of leveraging an external RabbitMQ service vs including one into StoryScapes itself.

**Comment by jpierson-boundlessgeo** [comment]
Just update to RabbitMQ 3.7, should not be a significant issue.

**Comment by cuttlefish** [comment]
Upgraded
