### ISSUE TITLE
Determine level of effort to upgrading version of PostGresSQL

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1552]
Currently, MS/SS are using a disapproved version of PostgresSQL (9.6) from NGA's SWAP list.  Need to determine the level of effort to upgrade the version of PostGresSQL.  Additionally need to investigate the feasability of moving to an external PostGres service vs. an internal deployment.

**Comment by jpierson-boundlessgeo** [comment]
Most recent stable release is 10.x

**Comment by Coop56** [comment]
@jpierson-boundlessgeo Before I start work on this - can we get clarification on exactly which version of postgres they require?

**Comment by cuttlefish** [comment]
The level of effort to use an external postgres is negligible. We're using RDS (Amazon's hosted DB service) for staging and prod. The catch is that we require PostGIS to be installed and enabled.

Any versions of 9.x should also be negligible. 10.x is unlikely to be a problem.

**Comment by cuttlefish** [comment]
Lines to edit:
https://github.com/MapStory/mapstory/blob/master/docker-compose.override.yml#L27
https://github.com/MapStory/mapstory/blob/master/docker/docker-compose.lab.yml#L5
https://github.com/MapStory/mapstory/blob/master/docker/docker-compose.storyscapes.yml#L5
https://github.com/MapStory/mapstory/blob/master/docker/docker-compose.travis.yml#L29

**Comment by cuttlefish** [comment]
Looks like we'll need to use this (if updating to 10):
https://www.postgresql.org/docs/10/static/pgupgrade.html

**Comment by Coop56** [comment]
It doesn't look like you can just run pg_upgrade as you'll need both versions available and our container won't contain both versions.  There's a lot of discussion about a good way to do this at https://github.com/docker-library/postgres/issues/37.  The consensus seems to be there isn't a great way to go about it outside of a pg_dump and reimport.  There is one possible option listed which is using https://github.com/tianon/docker-postgres-upgrade.  We'll have to find a different way to do this on the RDS side of things as well.

**Comment by cuttlefish** [comment]
Yeah, this'll be a pain. Hopefully they're fine with 9.x

**Comment by Coop56** [comment]
I believe 9.6 was denied and that's the latest version in the 9.x tree.  So I assume we're going to have to upgrade to 10.x.

**Comment by cuttlefish** [comment]
Blocked waiting to hear whether we should use 9.5, 9.6 or 10.x

**Comment by jpierson-boundlessgeo** [comment]
Approved versions are 9.6.7 and 10.4

**Comment by cuttlefish** [comment]
We're currently using PostgreSQL 9.6.10

My understanding is that our options are:
1) ask to get 9.6.10 approved
2) downgrade to 9.6.7
3) upgrade to 10.4

If we update to 10.4 now, it'll save us from having to do a DB migration in the future.

Changing our deployments to either 9.6.7 or 10.4 will require a bit of work. We'll need to build our own base images for postgres and postgis. I'm guessing about a day.

As an experiment, I've updated prod to use 10.4 (it's easy to do on RDS).

**Comment by cuttlefish** [comment]
I've prepped a PR that will bring us up to 10.4
Updates to the prod DBs will have to be done via the AWS console. Devs will have to wipe out their local deployments.
#1580

**Comment by Coop56** [comment]
My recommendation barring any major problems during the experiment on staging is that we update the StoryScapes deploys now and push those out before they start adding lots of data to them.

**Comment by cuttlefish** [comment]
It's too late for the StoryScapes deployments. GeoGig also has problems with 10 (although we haven't run into any yet). So we're delaying the update for the time being.
