### ISSUE TITLE
Auto Resize Images/Video in Pins

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1553]
Embedded media (videos, images) should be proportionally resized to fit the designated media area.

![screen shot 2018-08-27 at 11 59 22 am](https://user-images.githubusercontent.com/2573761/44673347-dffdd680-a9f0-11e8-9079-40b7bb8102a4.jpg)

**Comment by jpierson-boundlessgeo** [comment]
Ok to hardcode the image resize to fit in the current pin frame
