### ISSUE TITLE
Investigate convert story-tools from Gulp to webpack

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1555]
Currently use Gulp to build story-tools.  It is the only element using Gulp, specifically an older outdated version.  In order to eliminate those dependencies issues, we will migrate from Gulp to webpack. See this Gist for instructions on how to perform the final migration:
https://gist.github.com/darinacosta/99034aeb04b1e312bce0fef545a553e3

**Comment by darinacosta** [comment]
Concatenating global JS files using Webpack:
https://code.luasoftware.com/tutorials/webpack/merge-multiple-javascript-into-single-file-for-global-scope/
For CSS:
https://code.luasoftware.com/tutorials/webpack/merge-multiple-css-into-single-file/
