### ISSUE TITLE
"Add Chapter" appears in preview mode

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1558]
The "preview" setting in MapStory composer should hide all the active composing functions to give the user a sense of what their story will look like once published.

However, Preview still shows the "add chapter" option, technically allowing a user to add chapters while in preview mode. We need to hide the "add chapter" button in preview mode. 

Screenshot below shows "preview mode" with "add chapter" option still there

![screen shot 2018-08-27 at 3 14 42 pm](https://user-images.githubusercontent.com/2573761/44684173-054d0d80-aa0e-11e8-93bf-b5703da3d701.jpg)

**Comment by jonpmarino** [comment]
The carrot button should also not be seen in preview mode, as well as the garbage can for deleting added chapters.

**Comment by j-meyer** [comment]
https://github.com/MapStory/story-tools-composer/pull/274
