### ISSUE TITLE
Thumbnail tests using the wrong style

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#1561]
The thumbnail tests seem to be using the wrong (or non-existent?) style. Set it to use the MapStory default.

The baselayer seems to not be the MapStory default either.

Instructions on how to generate the validation image can be found here:
https://github.com/MapStory/mapstory/blob/master/mapstory/apps/thumbnails/test_storylayer_thumbnail.py#L539-L545

**Comment by Coop56** [comment]
I've updated the test file to use the correct basemap and style.
