### ISSUE TITLE
Prevent user from logging in until account is activated via activation email

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1565]
For new user sign-ups, the new user should not be able to log in until they have activated their account via an email w/ link sent to the email address they listed at the time of signup. 

Currently this is not happening. As a user I can log-in immediately after completing the signup form. 

![screen shot 2018-08-28 at 3 44 16 pm](https://user-images.githubusercontent.com/2573761/44749994-d13f1e80-aad9-11e8-9369-a3cf1da030e3.jpg)

**Comment by cuttlefish** [comment]
So it's enabled on prod but not working. I think this functionality was broken and removed in GeoNode 2.8
