### ISSUE TITLE
Troubleshoot Production Layers

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory#1566]
Various layers on production are failing, figure out what the various issues are and solve those.

- [x] Layer name is undefined on certain layers in the WMS request causing 404s and failures.
- [x] Layers without geonode: in the name currently cannot be styled.
- [x] Many layers have the wrong style, should all have the default style for their layer type.
- [x] Some layers cannot be loaded from the detail page into Composer.
- [x] layers without geonode: in URL break when saved

**Comment by jonpmarino** [comment]
I think #1567 is the same thing as the last item on this list so feel free to close if true and redundant
