### ISSUE TITLE
Can't get past Step 1: "Import service is currently unavailable"

### ISSUE THREAD

**Issue by nittyjee** [MapStory/mapstory#1569]
As usual, I can't get past step 1.

I get this error on step 1 of both staging.mapstory.org and mapstory.org:

_We're sorry but our import service is currently unavailable. Please try again later._

**Comment by Coop56** [comment]
What dataset are you trying to use?  Please attach it here so we can troubleshoot.  There were many other layers imported successfully today so curious to see what’s different about yours.

**Comment by nittyjee** [comment]
Changed the basemap to WGS_84.
Sorry about that.

Looks good, looking forward to what's been done, testing things now.
