### ISSUE TITLE
Basemap difficulties 

### ISSUE THREAD

**Issue by nittyjee** [MapStory/mapstory#1575]
In uploading anything around human settlement, the basemap options are too useless.
The only option that orients you are the osm basemaps, and they show the current environment, and you can hardly see the layers on top. The other options are white or one color.
A basemap that would work would be minimal, perhaps with only streets and coloring and little to no labels.

I've attached two screenshots that show the maps in the links below.

MapStory options:
https://mapstory.org/story/ames-iowa-started_8292018_1/
Note: This is buggy - when you press play, either go to the next chapter or zoom into Ames, Iowa.

MapStory Local data demo:
http://thenittygritty.org/mapstorylocal/v1.2/#13.9/42.0311/-93.6366
Move the timeslider in the upper-right.

As you can see, the Local data demo has 4 basemap options, and I default it to the one with no labels.
This was one of the first things I had to do to show the data, not just choosing a basemap, but having one with no labels. Everything was nonsensical without that. You can of course use my basemap(s) if that's possible, but something should be thrown in regardless. Would also be good to have a satellite option.

![local_basemap_better](https://user-images.githubusercontent.com/3781494/44823084-eb552b80-abc3-11e8-89b8-969efd8262b1.png)
![osm_basemap_crap](https://user-images.githubusercontent.com/3781494/44823085-eb552b80-abc3-11e8-9bd9-741375a67ddd.png)

**Comment by lhcramer** [comment]
I'm closing this issue until it is reworded in an appropriate and constructive form.

**Comment by nittyjee** [comment]
Any way I can change the title and then reopen it? Can't seem to do it on my phone.

**Comment by nittyjee** [comment]
And reopen it that is?

**Comment by nittyjee** [comment]
Is reopening not an option I have?
