### ISSUE TITLE
Make the chapter transition icons more pronounced

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1587]
Next to chapter titles there are small caret arrows that allow a viewer to advance from one chapter to the next. We are getting user feedback that these small carrot arrows are not pronounced enough to communicate that the viewer is able to transition to different chapters.

This is a design story that needs a UI treatment. Perhaps we could just find a more pronounced arrow icon, or use the words "Previous" and "Next".

![screen shot 2018-08-31 at 9 42 27 am](https://user-images.githubusercontent.com/2573761/44919363-f4004b80-ad02-11e8-8ce9-4c4e49fb680d.jpg)

**Comment by cuttlefish** [comment]
This drove me crazy when I first tried the new composer. The arrows were subtle enough that at first I thought they were just framing devices. It wasn't clear to me at all that I was expected to interact with them.

**Comment by trepagnier** [comment]
Res: https://github.com/MapStory/story-tools-composer/pull/381
