### ISSUE TITLE
StoryFrames form continues to appear in StoryPins area

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1588]
As a user, I expect that the StoryFrames builder form will only be available in the StoryFrames builder form area. However, sometimes the StoryFrames form continues to appear in the sidebar when the user switches to working on Storypins.

In screenshot below, user is in the StoryPins area and StoryFrames form still appears.

![screen shot 2018-08-31 at 9 03 00 am](https://user-images.githubusercontent.com/2573761/44921026-07151a80-ad07-11e8-802a-ec41d72ab0ac.jpg)

(using Chrome on mapstory.org prod on Aug 31)

**Comment by Coop56** [comment]
I'm not sure if this is an issue anymore or if it's been resolved.  If it's still an issue, how do we replicate it @jonpmarino?

**Comment by Coop56** [comment]
This is no longer the case in testing, closing.
