### ISSUE TITLE
Users can "add" layers that don't exist in composer, causing issues

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1596]
In composer, when I "add a layer" to a chapter, it is technically possible to type text and click "add", thus adding a layer to a story that doesn't exist. Composer should only allow users to add real existing layers to their story.

**Comment by shawnkendrick** [comment]
- In addition to checking if a layer exists, we need to check to see if the layer has already been added within the current chapter. Adding a layer twice within the same chapter throws an error:
"Error: Cannot add item: item with id ... already exists"
