### ISSUE TITLE
Reloading a story to view sometimes shows different results

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1597]
As a viewer of a story, I expect a published story to show up the same way every time I click to view it in MapStory.

Currently on prod, stories can sometimes appear differently. For example, StoryPins that belong in chapter 2 will be appear in chapter 1. Then, another time those same pins will appear in chapter 2.

**Comment by Coop56** [comment]
This is covered by other issues, much of it was fixed including pins showing up in other chapters.  Frames still need fixed in the same way, but there's already an issue for that.  Closing.
