### ISSUE TITLE
Scrolling allows going "off of the map"

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#1607]
The basemap stops being displayed somewhere in the middle of the Pacific. But it can be scrolled past that into a blank ocean of despair. While the basemap is not drawn here, data points are.

![image](https://user-images.githubusercontent.com/1152120/45233394-78187d00-b287-11e8-9f68-49b33b4438ce.png)

**Comment by lhcramer** [comment]
@cuttlefish, isn't this already completed?

**Comment by cuttlefish** [comment]
Yeah, it got fixed about a week or two ago.
