### ISSUE TITLE
Refactor Search Research Spike

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory#1613]
Search currently relies on elasticsearch and haystack.  We'll be dumping both of these with new search code that incorporates the default django / geonode API's.

**Comment by Coop56** [comment]
This will happen at the geonode level.  The plan is to rebuild their front end using React and pull those changes into our own codebase after we're done.

**Comment by lhcramer** [comment]
@Coop56 @darinacosta, Add checklists/issues involved in implementing the GeoNode React plan. 

Estimate of 6 for sprint 12

**Comment by lhcramer** [comment]
@Coop56 and @darinacosta, when creating issues place them in an epic for "Refactor Search" I think there is a pre existing epic.
