### ISSUE TITLE
For choro and graduated styling, Parse numeric data as integer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1621]
Choropleth and Graduated styling generate style ramps based on numeric fields in data. For Choropleth, features are assigned a pallete of colors based on their numeric level on an attribute. For Graduated, features are assigned a SIZE based on their numeric level on an attribute.

Example > a user might use choropleth styling on a STATES layer to show which states have high percentages of unemplyyment. Higher percentages get darker colors.

Example > a user might use graduated styles for a layer showing battles in a war. Circles showing battles are sized based on how many casualties were incurred in the battle.

Currently some layers seem to not be parsing numeric data as integer, which is required to conduct choropleth and graduated styling.

For example, the Civil War layer has an attribute for totalcasualties. This field is filled with numbers. But it is being recognized as a string in composer, thus graduated and choropleth styling can't occur. 

Note > its a django-importer issue with how the data was originally read.

Example layer, https://mapstory.org/layers/geonode:american_civil_war_53e3ba05

**Comment by cuttlefish** [comment]
The types in the Civil War shapefile are all `string`. Parsing them as such may be intended behaviour?

**Comment by jonpmarino** [comment]
The Civil War Layer has an attribute 'totalcasualities' with numerical variables. See screenshot of data table. One use-case is to apply graduated styling so that dot points vary in size based on the # of total casualties. But doesn't seem to work for me.

Another layer example is https://mapstory.org/layers/geonode:sl_dd0318ab. Has an attribute for state legitimacy score on a 10 point scale. Would like to apply choropleth styling to color countries based on their state legitimacy score. Can't do it.

But, simple and unique styling work for these layers...presumably because simple and unique use categorical data and not integer/numeric like choropleth and graduated.

![screen shot 2018-09-16 at 5 00 17 pm](https://user-images.githubusercontent.com/2573761/45601491-5def4500-b9d3-11e8-84dc-a7205fe55ad5.jpg)
![screen shot 2018-09-16 at 5 07 05 pm](https://user-images.githubusercontent.com/2573761/45601495-63e52600-b9d3-11e8-91b9-bb385deaeda1.jpg)

**Comment by jonpmarino** [comment]
so if all attributes in these datasets are being read as string, when there are numerical fields, i presume that means we need to re-import with redefined attributes.

**Comment by jonpmarino** [comment]
Here is an old layer for which graduated does work for me, https://mapstory.org/layers/geonode:lra_shp_c3798b17. The data has a "casualties" attribute with numerical data and graduated styling does work as expected. 
![screen shot 2018-09-16 at 5 15 00 pm](https://user-images.githubusercontent.com/2573761/45601537-1f0dbf00-b9d4-11e8-9d4a-1af6387ec185.jpg).

**Comment by jonpmarino** [comment]
Another layer I imported today that has a column for "fatalities" with numerical data. Graduated doesn't appear to be working, but simple and unique do - https://mapstory.org/layers/geonode:acled_version_5_all_africa_1997_2014_8b67e526

**Comment by cuttlefish** [comment]
When I open the layer in QGIS, I see all string types. I don't have ArcGIS to compare this against. The importer seems to be respecting the types used in the shapefile.

Here are the properties along with an integer one that I added.
![image](https://user-images.githubusercontent.com/1152120/45636424-853e2480-ba5c-11e8-91c4-e09fa2c04df3.png)

**Comment by Coop56** [comment]
Agreed with @cuttlefish.  @jonpmarino I think you need to change the type to integer in whatever program you use to edit shapefiles and then import it again.

**Comment by lhcramer** [comment]
The problem is still valid for CSVs however. I believe all values are imported as strings when uploading a CSV.

**Comment by cuttlefish** [comment]
CSVs aren't working for me on staging or prod. No errors in the logs.
![image](https://user-images.githubusercontent.com/1152120/45640550-dacbfe80-ba67-11e8-864f-f26096be035b.png)

**Comment by cuttlefish** [comment]
I don't know how we could guess at the column's type without including a UI for the user to override it.
I'm pretty sure we honour the types as supplied by formats that support them.
