### ISSUE TITLE
Errors when saving story with multiple chapters

### ISSUE THREAD

**Issue by josellausas** [MapStory/mapstory#1624]
When creating a story with 4+ chapters, save fails, or does not save all chapters.

**Comment by josellausas** [comment]
![screen shot 2018-09-17 at 11 23 43 am](https://user-images.githubusercontent.com/4162671/45636594-c12db580-ba6d-11e8-8bfd-745d50717247.png)

**Comment by cuttlefish** [comment]
Does geoserver need to be rebooted?

**Comment by Coop56** [comment]
This error only fires on local machines, and is generally fixed by a reboot of your development environment.

**Comment by josellausas** [comment]
Is it posible to test saving multiple chapters in local?

**Comment by cuttlefish** [comment]
Is world dark a basemap or a layer that you've added?

**Comment by lhcramer** [comment]
@cuttlefish , its a basemap (the defualt one)

**Comment by cuttlefish** [comment]
Then it doesn't exist on GeoServer

**Comment by Coop56** [comment]
This issue is now resolved in the refactor saving PR.
