### ISSUE TITLE
Implement NGA requested app tracking for StoryScapes

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1628]
At least in the StoryScapes deployment, implement NGA requested app tracking via the Matomo app.  The following code-snippet was provided by NGA to enable the tracking.

<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//gasmetrics.nga.mil/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '261']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

**Comment by copaskevin** [comment]
[https://app.zenhub.com/files/22082722/ff657dfc-34e2-443a-b5de-b654f96ec857/download](https://app.zenhub.com/files/22082722/ff657dfc-34e2-443a-b5de-b654f96ec857/download)



Document provided by NGA
