### ISSUE TITLE
storyframes don't fully zoom to box outline

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1631]
As a user, I expect storyframes to zoom the map viewer totally to the bounds of the storyframe. But, right now, the map viewer does not zoom fully to the extent of the storyframe.

**Comment by shawnkendrick** [comment]
Zoom Level: Each StoryFrame should set the zoom level of the map canvas to fit the bounding box fully within the story viewer. The storyteller should not need to set the zoom level manually as it should be generated by the bounding box. The zoom level of the previous extent should be preserved to return to upon reaching the end date.
