### ISSUE TITLE
Text wrap the StoryPin box

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1651]
We auto-sized the media in StoryPins, but not for Text. So, text runs on. We should max-width or text wrap the storypin pop up to match images.

![screen shot 2018-10-03 at 3 37 50 pm](https://user-images.githubusercontent.com/2573761/46438032-573f2c80-c74c-11e8-87f3-45b59acdaa23.jpg)

**Comment by jpierson-boundlessgeo** [comment]
To resolve this, need to Fix CSS for pins so text box for pins so it doesn’t grow forever.
