### ISSUE TITLE
Site Wide StoryScapes Branding Review 

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1672]
Review each page on the site with Product Owner for consistent branding when skinned as StoryScapes

**Comment by cuttlefish** [comment]
We've done a quick first pass on the main page, but it needs review.
The rest of the site has yet to be addressed.

**Comment by jpierson-boundlessgeo** [comment]
Verify on whitelabel.

**Comment by copaskevin** [comment]
Working with Wade to verify changes on Whitelabel
