### ISSUE TITLE
Fix Thumbnails on UC 

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1674]
Thumbnails on UC are not generating, Possibly an issue with closed network basempas

**Comment by jpierson-boundlessgeo** [comment]
Logs from UC show gateway timeouts, but PaaS team has confirmed they can hit the thumbnail basemap URL from the UC servers.  Potentially a firewall issue on UC even.  Also have seen thumbnail test failures.

- [x] Create default StoryScapes icon.
- [x] Put in default StoryScapes icon
- [x] Make thumbnail basemap an environment variable for deployment
- [ ] Populate StoryScapes build with internal OSM server

**Comment by DerekSedlmyer** [comment]
![image](https://user-images.githubusercontent.com/19574600/46540217-ac7f5900-c886-11e8-8707-9c7e4ea0e6bf.png)
