### ISSUE TITLE
Pull any dynamic Internet load dependencies into the StoryScapes deployment

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1679]
Currently, SS/MS pulls in some external dependencies.  These libraries need to be incorporated into the SS build so that the capability functions on a closed network.  The following items are known:
- Google Fonts
- Font-awesome? (Need to verify, may have been fixed).

Additionally, testing with WiFi/Network connectivity off of a local build would identify any other dependencies.

**Comment by lhcramer** [comment]
Also be aware of Google API is being called in Layer Detail page around Social
