### ISSUE TITLE
Move pins into chapters

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1696]
within the config object, move pins and frames to be contained within chapters instead of within stories on the front end.

**Comment by jpierson-boundlessgeo** [comment]
Also need to change save code as part of this

**Comment by trepagnier** [comment]
@TODO: find every instance of `svc.pins` in `pinSvc` and point instead to `stateSvc.getConfig().chapters[svc.getChapterIndex()]`

**Comment by trepagnier** [comment]
@TODO: Make a minimal config of chapters. Check mapstory/mapstories/models.py to see the data model.
