### ISSUE TITLE
Make backups work for StoryScapes deployments

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#1721]
... or disable backups for StoryScapes deployments.

**Comment by DerekSedlmyer** [comment]
Could we remove backups at the Docker-level and rely on infrastructure backups? Snapshots on AWS and Persistent Volumes on PaaS?

**Comment by cuttlefish** [comment]
EFS doesn't support backups, other than mounting the volume and copying the files.
I'll just try to disable it all for StoryScapes deployments.
