### ISSUE TITLE
Complete Research / Data Collection for Exemplar Syria Story

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1738]
Per customer feedback, we need a 7 chapter story to demonstrate successful implementation of composer. Story should follow this rough outline:

1. Protests ignite the opposition
StoryLayers
  - Early protests
StoryFrames
  - Frame the layer to March/April 2011 demonstrations in and around Damascus
StoryPins
  -  Damascus Demo pic or video
  - Latakia Demo pic or video
2. Early insurgency and Escalation
StoryLayers
  - Opposition/government clashes, March 2011 to March 2012
3. Rise of ISIS and Islamist Groups
StoryLayers
  - ISIS expansion
  - Ansar al Nusrah
StoryPins
  - Raqqah picture
  - Orange jump suits 
4. Brutal Modern War
StoryLayers
  - Chemical Attacks
  - Refugees
  - WMS layer of Aleppo before and after
StoryPins
  - Anti Tank missile video - kornet missile shot
5. External Intervention
StoryLayers
  - Iran Attacks
  - Hizballah in Syria
  - Russia airstrikes
StoryPins
  - Russian Airstrikes Aleppo
6. Defeat of ISIS
StoryLayers
  - SDF expansion
  - ISIS retraction layer
  - Turkish intervention
StoryFrames
  - Raqqah - US airstrikes
7. Conflict Simmers

@lhcramer and @jonpmarino lead research and data collection for layer, pin, frame content. Developers address issues that prevent the story from working successfully on deploy.

**Comment by lhcramer** [comment]
@jonpmarino , do we need to keep this open still?
