### ISSUE TITLE
Refactor how Bounding Box can be drawn

### ISSUE THREAD

**Issue by copaskevin** [MapStory/mapstory#1744]
Bounding box for frames should act more like cropping features in other applications

**Comment by shawnkendrick** [comment]
Bounding Box: Each StoryFrame shall have a function to create a bounding box within the map canvas. This bounding box should operate similar to cropping a photo or selecting multiple features on the desktop. Furthermore, the aspect ratio should be set to the same aspect ratio as the map canvas within the story viewer. When in draft/edit mode, the storyteller should see an outline of the bounding box to identify where it is on the map canvas. When in preview mode or the story viewer, the user viewing the story should not see the bounding box.
