### ISSUE TITLE
Filter by StoryScape/MapStory on Explore not working. 

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1752]
When you are one the explore page as a user, you cannot filter by "MapStories" or "StoryScapes" under the content filter toggle. 
![image.png](https://images.zenhubusercontent.com/5ad4ece44b5806bc2bcf5287/8cda76f6-ba09-4dec-a5a6-e58960d6244d)
![image.png](https://images.zenhubusercontent.com/5ad4ece44b5806bc2bcf5287/14b03468-c6f9-4954-a83c-6a548ca2ec36)

**Comment by jonpmarino** [comment]
note, this seems to work fine currently on mapstory.org
