### ISSUE TITLE
Blank Tiles on Explore Page

### ISSUE THREAD

**Issue by DerekSedlmyer** [MapStory/mapstory#1759]
On Storyscapes in BEAST, there are blank tiles on the Explore page. The blank tiles link back to the Explore page.

See screenshot.

![image.png](https://images.zenhubusercontent.com/5bb7858ce1e7434bb34d6a3b/68822a0a-c2b5-4f60-94e0-c9e6dc9c7bfa)

**Comment by Coop56** [comment]
Chapters are also showing up in Explore, but Explore should only show Layers and Stories.
