### ISSUE TITLE
Determine location for storypin media assets for storyscapes & add to whitelist

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1768]
The current method for embedding media (video, images) into storypins is by linking to whitelisted services on the web (i.e. YouTube, Flickr). This won't work for SS. We need to know where these media assets will be hosted, and then add that to the whitelisted path so users of SS can add media rich storypins to their stories.

**Comment by Coop56** [comment]
We're blocked on this issue until we know what the services are that StoryScapes wants whitelisted and how their URLs are structured so that we can set them up for StoryPin embeds.

**Comment by copaskevin** [comment]
@shawnkendrick will need you to chase this down since you have .mil access.  I was told we could place all of our media on ivideo on .mil.  Assigning this ticket to you to chase down.  Ben Foster or Wade Foote at NGA can let you know where you can access this if you do not know the location.

**Comment by shawnkendrick** [comment]
Create user documentation for embedding video/image URLs for iVideo and Gallery.
