### ISSUE TITLE
Layers showing up in story tab on Profile

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1781]
As a user, I have a profile. On my profile I have a tab where I can see all my layers, and a separate tab to see all my stories

_Issue_

On white label, the story tab seems to be showing layers.  See example. HonestAbe has 2 stories and 1 layer. 

The story tab is showing a layer (Major_events_in_the_Syrian_Civil_War_11_03_18_47424e31). 

![screen shot 2018-11-08 at 11 07 34 am](https://user-images.githubusercontent.com/2573761/48227301-85291980-e367-11e8-8c2b-dab61e85910c.jpg)

However, the layer tab correctly only shows the 1 layer.

![screen shot 2018-11-08 at 3 02 28 pm](https://user-images.githubusercontent.com/2573761/48227345-aab62300-e367-11e8-9249-f25895f68187.jpg)

**Comment by jonpmarino** [comment]
note, this does not seem to be an issue on current mapstory.org prod

**Comment by Coop56** [comment]
Note - my solution for #1759 may fix this.  We should check and confirm once I finish that one.
