### ISSUE TITLE
Example Map in Get Pages module

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#18]
The example map form in Get Pages seems to ask for too much information. Is it possible here just to add a hyperlink to a mapstory?

**Comment by ischneider** [comment]
Maybe you're seeing what happens when you press the '+' button (since there are no maps yet)?

**Comment by jonpmarino** [comment]
correct. that's what i'm referring to.

**Comment by glynnis** [comment]
Closing this given the redesign work underway and the age of this issue. Please reopen and include more detail about what is desired here from a feature standpoint if this is still relevant.
