### ISSUE TITLE
Journal Link Not Working

### ISSUE THREAD

**Issue by DanielJDufour** [MapStory/mapstory#1821]
I go to https://mapstory.org/journal/ and I see
![image](https://user-images.githubusercontent.com/4313463/49061324-6edfe200-f1de-11e8-9ac1-2e029ec0f631.png)

I'm using a Chromebrowser on a Chromebook.

**Comment by cuttlefish** [comment]
It seems to be working on staging. Might be a configuration issue on prod.

**Comment by cuttlefish** [comment]
Apparently it was fixed recently and should be fixed the next time production is deployed.
