### ISSUE TITLE
Basemap in edit mode is broken for whitelabel and beast

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1827]
only in whitelabel and beast, in edit-features mode, there is only one basemap available and it shows up blank white -

![screen shot 2018-12-04 at 12 41 05 pm](https://user-images.githubusercontent.com/2573761/49490470-d79a1080-f815-11e8-9726-2907bdf8ae32.jpg)
![screen shot 2018-12-04 at 4 10 38 pm](https://user-images.githubusercontent.com/2573761/49490487-ebde0d80-f815-11e8-8a79-d391aa661feb.jpg)

**Comment by cuttlefish** [comment]
Presumably the configurable basemap work wasn't done in MapLoom...

**Comment by copaskevin** [comment]
Want to verify from @j-meyer that his work last sprint fixed this issue.  This might be a ticket where we need to validate that this issue no longer exists.
