### ISSUE TITLE
Story thumbnail issues

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1828]
It looks like each of the deployments are having issues generating the animated thumb for published stories.

> for mapstory.org, were generating the stock image, not the animated gif, although the gif was being generated before.

![screen shot 2018-12-04 at 10 51 07 pm](https://user-images.githubusercontent.com/2573761/49490799-390eaf00-f817-11e8-8e40-27e56ee20946.jpg)

> on whitelabel, we are getting same outcome as mapstory.org, except with the SS stock image.

![screen shot 2018-12-04 at 10 49 08 pm](https://user-images.githubusercontent.com/2573761/49490822-5774aa80-f817-11e8-8f06-3281842add69.jpg)

> on beast, it looks like we are now generating a broken image icon. Looking at the dates of published stories, it looks like recently we were generating the mapstory stock image, and before that we _were_ successfully using an animated gif from a layer.

![screen shot 2018-12-04 at 3 07 05 pm](https://user-images.githubusercontent.com/2573761/49490858-8723b280-f817-11e8-9cbe-1dd4470ecb5b.jpg)

**Comment by DerekSedlmyer** [comment]
Attaching logs from BEAST. 

This seems to be the main error:

celery_1          | [2018-12-04 15:10:58,438: WARNING/ForkPoolWorker-7] Traceback (most recent call last):
celery_1          |   File "/srv/mapstory/mapstory/thumbnails/tasks.py", line 576, in run
celery_1          |     new_url = self.update_thumbnail(mapstory)
celery_1          |   File "/srv/mapstory/mapstory/thumbnails/tasks.py", line 555, in update_thumbnail
celery_1          |     thumbnail_info = self.get_all_thumbnail_info(chapter)
celery_1          |   File "/srv/mapstory/mapstory/thumbnails/tasks.py", line 521, in get_all_thumbnail_info
celery_1          |     result["tile_URL"] = CreateStoryAnimatedThumbnailTask.tileURL(chapter)
celery_1          |   File "/srv/mapstory/mapstory/thumbnails/tasks.py", line 411, in tileURL
celery_1          |     return CreateStoryLayerAnimatedThumbnailTask.tileURLFromLayerName(config.name)
celery_1          |   File "/srv/mapstory/mapstory/thumbnails/tasks.py", line 162, in tileURLFromLayerName
celery_1          |     x for x in settings.MAP_BASELAYERS if "name" in x and x["name"] == layer_name][0]
celery_1          | IndexError: list index out of range

**Comment by DerekSedlmyer** [comment]
[https://app.zenhub.com/files/22082722/6595e33c-6ff0-407d-8ce9-d198553f4ee6/download](https://app.zenhub.com/files/22082722/6595e33c-6ff0-407d-8ce9-d198553f4ee6/download)
