### ISSUE TITLE
Journal broken on mapstory.org

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1859]
As a user when I click "journal" at the top of the screen, I expect to see a community blog with published posts by the user community.

Using chrome browser on Dec 18, journal link goes to an error page.

![journal](https://user-images.githubusercontent.com/2573761/50182012-c223ec80-02d3-11e9-91a0-97ff1157b772.jpeg)

*Note > journal entries by users still appear on the profile page tab under 'journal'. for example, see https://mapstory.org/storyteller/KarlRPhillips/.

**Comment by Coop56** [comment]
@jonpmarino This was already fixed - it just hasn't been deployed to production yet.
