### ISSUE TITLE
Try and import WFS services from GVS to see if it imports

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1931]

**Comment by DerekSedlmyer** [comment]
https://aerodata.nga.mil/geoserver
* Wasn't able to register in Storyscapes on UC Ops
* When accessing through the browser, it have to accept LIMDIS agreement, not sure how that impact Storyscapes accessing it.

https://ais.gs.mil
* Currently getting HTTP ERROR 504 - Gateway timeout and also Oracle Access Manager errors in WebGate.
