### ISSUE TITLE
Creation of a Test Plan to be delivered to NGA 

### ISSUE THREAD

**Issue by copaskevin** [MapStory/mapstory#1942]
This comprehensive test plan will be used as a starting point for the Beta Testing team after delivery of MVP to NGA.

**Comment by lhcramer** [comment]
# StoryScapes Testing Guide

This is a checklist of items to look for when testing a StoryScapes deployment. It assumes basic knowledge with the purpose and design of the StoryScapes platform. If you are new to StoryScapes please review the material under the "Get Started" tab of your StoryScapes deployment. If there is no material (i.e. videos, text) on the Get Started page, contact an administrator

## Testing Environments 

When testing StoryScapes, make sure to note the environment (BEAST, mil DEV, mil OPS, etc). 

It is also useful to note the web browser and operation system used during testing 

Verify each task and iterate through tasks where multiple options are presented. 

## Log-in and Homepage

- [ ] USG Banner when entering site. 
	+ _There should be a control widget that displays upon first accessing the site before log in, click on the **Accept and Continue** button to proceed to log-in modal_

- [ ] GeoAxis Log-in
	+ _log in with your GeoAxis credentials or certificate_ 

- [ ] Homepage Links
	+ _The Featured StoryScapes "See More" button should direct to storyscapes filtered search_ 
	+ _How it works links should direct to the "Learn More Tab"_ 
	+ _Each "Get Started" link should direct to the corresponding functionality. Importer, Composer, etc_ 

- [ ] Menu Bar Links 
	+ _Explore should open the search page_ 
	+ _Create drop-down should link to: Importer, Create Layer, Remote Services Registry, Icons Uploader, and Composer_ 
	+ _Learn More takes you to the informational videos and about section_ 
	+ _Profile Icon drop-down should link to: Profile page, Edit profile page, Help page, and Log out_ 
	
- [ ] Quick Search on homepage 
	+ _Searchs should auto-complete and then direct to the Explore Page_ 
	
## Explore Page 

- [ ] Test Each Filter Type for **Content**
	+ [ ] Keyword Search 
	+ [ ] Content Type
	+ [ ] Category
	+ [ ] Story Teller (ensure auto-complete)
	+ [ ] Tags

- [ ] Sort **Content** by (Popular, Newest) 

- [ ] Test Each Filter Type for **StoryTeller**
	+ [ ] Story Teller (ensure auto-complete) 
	+ [ ] City (ensure auto-complete)
	+ [ ] Country (ensure auto-complete)
	+ [ ] Interests (ensure auto-complete)
	+ [ ] VTC Members 

- [ ] Sort **StoryTeller** by (A-Z, Z-A) 

- [ ] Test Each Filter Type for **Teams**
	+ [ ] Name (ensure auto-complete)
	+ [ ] City or Country (ensure auto-complete)
	+ [ ] Type (Organization, Initiative) 

- [ ] Sort **Teams** by (A-Z, Z-A) 

- [ ] Test Clear All for multiple filters. 

## Learn More Page 

- [ ] Check all relevant user guide videos are uploaded. 

## Importer, Create, Icons 

### Importer

- [ ] Select a zipped shapefile via modal. 
	+ [ ] Layer Name 
	+ [ ] Set Start and Optional End temporal fields
	
- [ ] Verify Layer is imported by going to it's layer detail page. 

Repeat the above steps with a CSV file. 

### Create Layer

- [ ] Fill out Modal fields 
	+ [ ] Layer Name 
	+ [ ] Layer Type (points, lines, polygons)
	+ [ ] Define attributes 
		- _Make sure a temporal field is there_ 
	+ [ ] Set Start and Optional End temporal fields
	
- [ ] Verify Layer is create by going to it's layer detail page. 

### Icons Uploader 

- [ ] Upload a single SVG
	+ _Apply a tag_ 
	+ _Check its visible in composer_ 

- [ ] Upload a zip with more than one SVG
	+ _Apply a tag_ 
	+ _Check tag makes all icons in zip visible in composer_ 
	
## Profile Page 

- [ ] Verify Each Tab has the appropriate content the user has generated represented 
	+ [ ] Stories
	+ [ ] Layers
	+ [ ] Uploads 
	+ [ ] Activity Feed
	+ [ ] Favorites
	+ [ ] Icons
	
- [ ] IF OWNER: Launch Profile Editor and fill out all fields 
	+ _Verify each field shows up on the profile page_ 
	
- [ ] IF TEST PROFILE: Test deletion of profile. 

## Layer Detail Page

- [ ] Play Layer in viewer 
	+ _Test play, pause, step forward, step backwards_ 
	
- [ ] Toggle Timeline

- [ ] Toggle Legend 

- [ ] Toggle Playback Options (Gear Icon) 
	+ _Test instant and cumulative playback_ 
	+ _test playback rates_ 

- [ ] Toggle Full Screen 

- [ ] Download Layer Button 
	+ _Select either image or data to download_
	+ _Verify download in QGIS_ 
	
- [ ] Metadata Detail Button 
	+ _Launches Metadata page_ 
	
- [ ] Edit Layer Button 
	+ [ ] Append Data launches Append wizard 
	+ [ ] Edit Data launches Editor. 
	
- [ ] Download Metadata Button 
	+ _Select format and verify download_ 
	
- [ ] Compose Story button launches composer 
	+ _Ensure layer is **Pre-populated** in composer_ 

- [ ] Click on StoryTeller Avatar and confirm redirect to profile page 	

- [ ] Check Each Tab below viewer
	+ [ ] Info
	+ [ ] Attributes 
	+ [ ] Rating 
		- _Rating allows rating of story and shows current rating_ 
	+ [ ] Test comment and threaded comments. 
	+ [ ] GeoGig
		- _verify changes are tracked_ 

### If Owner of Layer 

Same As above with the following Changes 

- [ ] Edit Layer Button 
	+ [ ] Append Data launches Append wizard 
	+ [ ] Edit Data launches Editor. 
	+ [ ] Remove (delete) Layer 
	+ [ ] Metadata Wizard, Advanced Edit and Uploader
	
- [ ] If member of a Team, test "Use On Team Page" 

- [ ] Test Empty Tiled-Layer Cache 

## Story Detail Page 

- [ ] Play Story in viewer 
	+ _Test play, pause, step forward, step backwards_ 
	+ _Verify all story elements work (Styling, Pins, Frames)_ 
	
- [ ] Toggle Timeline

- [ ] Toggle Legend 

- [ ] Toggle Playback Options (Gear Icon) 
	+ _Test instant and cumulative playback_ 
	+ _test playback rates_ 
	
- [ ] Test loop chapter **and** loop story

- [ ] Navigate between chapters using arrows next to chapter title

- [ ] Toggle Full Screen 

- [ ] IF STORY OWNER: Click "Change Published/Resume Draft" to launch composer

- [ ] Flag Story 
	+ _Fill out option and reason. Confirm Notification upon submission_ 

- [ ] Favorite Story and check on profile page

- [ ] Click on StoryTeller Avatar and confirm redirect to profile page 

- [ ] Verify all Chapters and Layers are represented below viewer 

- [ ] IF STORY OWNER: Delete Story and verify its removed from profile page and search 

- [ ] Verify Thumbnail 

- [ ] Test comment and threaded comments. 

## Edit Layer (Editor) 

- [ ] Add Featured
	+ [ ] Draw geometry on map
	+ [ ] Fill all attribute data
	+ [ ] Verify addition in "View History" 

- [ ] Select an existing feature and change its geometry 
	+ [ ] Verify addition in "View History" 

- [ ] Select an existing feature and change some attribute date 
	+ [ ] Verify addition in "View History" 
	
- [ ] Open table view and change some attribute date 
	+ [ ] Verify addition in "View History" 
	
- [ ] Select an existing feature and delete it. 
	+ [ ] Verify addition in "View History" 
	
- [ ] In the "View History" tab, select an edit and show diff 
	+ [ ] verify change is tracked_
	+ [ ] revert change 
	
## Story Composer (Composer) 

- [ ] Click Edit Story Info link and update: Title, Summary and Category; Save 

- [ ] Add a new chapter
	+ [ ] Add chapter Title 
	+ [ ] Add Chapter Description 
	
After Styling, pins and Frames have been added

- [ ] Verify Save 

- [ ] Verify publish 

- [ ] Verify Preview mode 

### Styling 

- [ ] Select a different basemap 

- [ ] Add a Story Layer by searching under "Add a StoryLayer" 
	+ [ ] Verify Auto-complete 
	+ [ ] Iterate through points, lines, and polygons 
	
- [ ] Enter styling panel Iterate through each option 
	+ [ ] POINTS: Simple 
	+ [ ] POINTS: Unique
	+ [ ] POINTS: Choropleth 
	+ [ ] POINTS: Graduated 
	+ [ ] POINTS: HeatMap 
	+ [ ] LINES: Simple 
	+ [ ] LINES: Unique
	+ [ ] POLYGONS: Simple 
	+ [ ] POLYGONS: Unique
	+ [ ] POLYGONS: Choropleth 
	
- [ ] For Points, use an icon from the icon commons 
	+ [ ] Use original color 
	+ [ ] Use custom color
	
- [ ] Delete an added layer 

### Pins 

- [ ] Add story pin 
	+ [ ] Add Title
	+ [ ] Add Pin Text 
	+ [ ] Set Start Date 
	+ [ ] Set End Date 
	+ [ ] Update Map
	
- [ ] Add story pin with Image 
	+ [ ] Add Title
	+ [ ] Add Pin Text 
	+ [ ] Set Start Date 
	+ [ ] Set End Date 
	+ [ ] add pin media link (Image link) 
	+ [ ] set Heigh and width 
	+ [ ] Set playback offset 
	+ [ ] Update Map
	
- [ ] Add story pin with Video 
	+ [ ] Add Title
	+ [ ] Add Pin Text 
	+ [ ] Set Start Date 
	+ [ ] Set End Date 
	+ [ ] add pin media link (Video Embed) 
	+ [ ] set Heigh and width 
	+ [ ] Set playback offset 
	+ [ ] set playback duration 
	+ [ ] set autoplay. 
	+ [ ] Update Map
	
- [ ] Move pin by changing Lat and Long 

- [ ] Move pin using move pin button and move on map. 

- [ ] Export pins and verify csv has correct attributes. 

- [ ] Delete a Pin 

- [ ] Import Story pins 
	+ [ ] Download template and fill out appropriate fields 
	+ [ ] Re-upload template
	+ [ ] Verify bulk uploaded pins are present on map. 


### Frames 

- [ ] Set Title for frame

- [ ] Set Start Date 

- [ ] Set End Date 

- [ ] Draw bounding box on map after clicking "Create Bounding Box"
	+ _**NOTE:** make sure to shift click to draw bounding box_ 
	
- [ ] Add to Map 

- [ ] Verify playback is as expected 

- [ ] Click on the title of the created frame, verify accuracy of information 

- [ ] Edit pre-existing frame and update 

- [ ] Delete Frame and verify its removed from map.
