### ISSUE TITLE
Remove hyperlink in VTC text

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1962]
it goes to a broken link.

![Screen Shot 2019-03-07 at 4.19.15 PM.jpg](https://images.zenhubusercontent.com/5ad609ee4b5806bc2bcf750b/cd9df14c-02ec-4110-81aa-af84f87a20fc)

**Comment by Coop56** [comment]
Closed via https://github.com/MapStory/mapstory/commit/4460c9bdf3c07dc246392fa6d0c9da0f067b1659
