### ISSUE TITLE
Update wiki link in footer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1966]
For now, make it -

https://github.com/MapStory/mapstory/wiki

![Screen Shot 2019-03-15 at 1 46 15 PM](https://user-images.githubusercontent.com/2573761/54455885-cfae0e80-472a-11e9-8b8c-4998969172db.jpg)

**Comment by Coop56** [comment]
Closed via https://github.com/MapStory/mapstory/commit/b8c46157829db7d263a1c683b298269c5b72a4ec
