### ISSUE TITLE
Adding layer to Initiative Page fails to add proper URL form (breaks layer)

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1970]
To reproduce:

1. add layer to initiative page
2. the layer lacks a geonode: that causes layer to break.

![Screen Shot 2019-04-02 at 11 05 11 PM](https://user-images.githubusercontent.com/2573761/55452145-e31aff80-559b-11e9-9ab2-80b512745aee.jpg)

3. The same layer can be added to an Org page, and it works fine:

![Screen Shot 2019-04-02 at 11 07 10 PM](https://user-images.githubusercontent.com/2573761/55452181-16f62500-559c-11e9-8291-c587076a5b49.jpg)

**Comment by Coop56** [comment]
Closed by https://github.com/MapStory/mapstory/commit/2857322e29786767e899a1d4bead377a0c42b446
