### ISSUE TITLE
Propagating upload errors

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#211]
Failure in the importer causes a problem - the underlying problem is masked:
https://github.com/ProminentEdge/django-osgeo-importer/issues/4

Adding it hear even if its a uploader concern because it impacts, and I suspect there should be tests in the mapstory layer to make sure things work.

Not sure what happens if a problem fails in mapstory-specific tasks - (i cant get importer to succeed the mapstory part of things yet - fails without any message or log somewhere after setting up geoserver layer) 

Will also submit issue re having test data that definitely works available as a test fixture.

**Comment by glynnis** [comment]
Closing this given the redesign work underway and the age of this issue. Please reopen and include more detail about what is desired here from a feature standpoint if this is still relevant.

**Comment by rob-metalinkage** [comment]
closed - but not gone away... :-) 

For an example - see issue https://github.com/MapStory/mapstory/issues/515
