### ISSUE TITLE
Provide valid uploadable data as a test fixture

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#212]
amongst challenges of trying to set up mapstory is that there are no data sets easily accessible _and documented in setup instructions_ to test the install end to end.
These should be able to double as test fixtures for uploading (and extended functions).

**Comment by glynnis** [comment]
Closing this given the redesign work underway and the age of this issue. Please reopen and include more detail about what is desired here from a feature standpoint if this is still relevant.
