### ISSUE TITLE
Finalize design for StoryPins tab

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#272]
**User Story**
As a user composing a story
I want to create StoryPins for my Mapstory
In order to emphasize events, media, or places to provide more information and context to viewers of my MapStory

**Acceptance Criteria/Questions to Answer**
- [x] Change playheads back to current date picker fields for MVP mock-ups
- [ ] Bulk upload screens: modal, success/error messaging
- [ ] What should the default playback options be set to? Something the user has set for previous pins? Should they all be off? On? “Apply to all” or “create new storypin with these settings?”
- [ ] Are ‘Show StoryPin on timeline’ and ‘Show StoryPin on map’ mutually exclusive? Can you have neither selected?

**Deliverable**
Incorporate StoryPin features into the high-fidelity mock-up for Composer MVP to facilitate discussion about technical feasibility with the team and create feature stories that further refine the design or technical tasks associated with this.

**Comment by glynnis** [comment]
Questions for standup on 12/8:
1. For Bulk Upload, are we able to show upload progress, or is it success vs. fail, no progress?
 - Success or fail
2. Do we have the ability to show a success or failure message? (demo current behavior)
 - See pins listed in a list format
3. What should the user see on success? What should the user see on failure?
 - Error message display up to me

**Comment by glynnis** [comment]
- StoryPins that aren't tied to geographic data aren't part of MVP.
- Evaluate whether StoryPins on timeline only are working well/can be included in improvements

**Comment by glynnis** [comment]
After meeting with @davisc and @jonpmarino today about priorities, it was decided that this might be a story for @reynalddizon to tackle in the future. If I have time before my last day to get to this I can start, but it's lower priority than some other stories.

**Comment by josellausas** [comment]
# Old composer Pins:

![screen shot 2018-01-12 at 12 02 47 pm](https://user-images.githubusercontent.com/4162671/34888683-d537e276-f790-11e7-8e71-59eb50785243.png)


# New Composer Pins:

![screen shot 2018-01-12 at 12 04 19 pm](https://user-images.githubusercontent.com/4162671/34888689-d885229a-f790-11e7-81d0-6b09a760544a.png)
