### ISSUE TITLE
Redesign Viewer Sidebar: Chapter summary

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#278]
Currently the chapter summaries can be quite long and require the user to scroll in order to see the full description. If the summary is long and the user must scroll, the "next" and "previous" links aren't initially visible.

Things to consider as part of this effort:
- [ ] Should there be a character limit on Chapter summaries?
- [ ] Should chapter summaries for sidebar be different than chapter summaries for details page? (i.e. should they be two separate fields in Composer -- sidebar text vs. detail text)
- [ ] "Next" and "Previous" should be visible without scrolling

**Comment by jonpmarino** [comment]
@glynnis @emilyashley another thing to consider - Right now a "single chapter mapstory" is treated the same way on the STORY DETAIL page as a multi-chapter mapstory. This means that "chapter info" appears 3 times. 1) chapter info sidebar on map canvas 2) Story Summary area on detail page and 3) Chapter Summary area on detail page. A single chapter mapstory is probably best understood as a "short story" that has a different default viewer model on the detail page with the goal of not showing content more than once. Presumably, the Chapter Info and Story Summary areas should be rolled into 1 at least.
