### ISSUE TITLE
Finalize design for "Edit story data" modal (from header)

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#281]
Where does the information in the story properties modal display?
- Title: story detail page, embedded story, explore page
- Summary: story detail page (could be added to explore or embedded viewer but not currently there)
- Tags: story detail page, tags make a story searchable, add checkbox for "Include tags from all layers", add autocomplete functionality
- Category: story detail page, explore page, on the homepage if it becomes featured since the features are separated by category
- Location: not currently displayed anywhere, "include all regions for layers", autosuggestions based on tree (i.e. "Honolulu" recommends "Hawaii" and "United States")

**Comment by glynnis** [comment]
Related to #275, which includes flows for when a story is first created

**Comment by glynnis** [comment]
Not displaying "Location" for MVP since it doesn't currently work and could be added in later. 

"Tags" pictured in mock-up come from Angular Material https://material.angularjs.org/latest/

<img width="528" alt="screen shot 2016-12-08 at 12 42 35 pm" src="https://cloud.githubusercontent.com/assets/1529366/21022884/d543b0ca-bd43-11e6-92b7-5cdbe68d322f.png">

Only question left: should there a character limit on "summary" field?

**Comment by glynnis** [comment]
No character counter needed.

**Comment by emilyashley** [comment]
In the Story Properties modal, as far as the [models](https://github.com/MapStory/geonode/blob/master/geonode/base/models.py#L269) are concerned, neither the summary or the purpose have char limits, but title has a limit of 255 in the db. Not sure if this is the desired limit.
