### ISSUE TITLE
Add templates, JS list, and other data to site map once added to wiki

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#303]
Once the site map is relatively complete, create a wiki page that lists JS, assets, templates, and any other relevant info for each page.

**Comment by glynnis** [comment]
Relates to #304

**Comment by glynnis** [comment]
@emilyashley I've got the graphic uploaded (click to see large), and made an empty table here that we can fill in with the JS/template info and whatever else needs to be there: https://github.com/MapStory/mapstory/wiki/Site-map

Happy to help fill in but I may need your help getting started.

**Comment by glynnis** [comment]
I updated https://github.com/MapStory/mapstory/wiki/Site-map.

Still left to do:
- [ ] Complete the "to do" areas at the bottom with info from the google doc of notes
- [ ] Add numbers that correspond to the site map graphic
- [ ] Update the site map graphic with pages from the list that aren't represented yet
- [ ] Add URLs to MapStory.org where appropriate
- [ ] Add info about JS assets

@emilyashley Can you take a look at what I have so far and make any updates or leave comments here about areas that need adjustment? Thanks!

**Comment by emilyashley** [comment]
Note to self: stashed some braindump on the state of Importer assets [here](https://github.com/MapStory/mapstory/issues/838#issuecomment-316833860) --- incorporate these next time I update the wiki

**Comment by emilyashley** [comment]
started addressing w/ #1030 
more to come.
