### ISSUE TITLE
Add support for raster filed on import

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#305]
As a user, I want to upload raster data, such as a print map or an aerial image, or sequence of images, into MapStory as a StoryLayer so I can do things, like, make MapStories that animate digital data on top of historic print maps or images.

**Acceptance Criteria**

- [ ] Support injest of a single geo-referenced image with a date
- [ ] Support injest of a zipped file with several images (mosaic) showing change over time

**Notes**
Previous tickets for raster upload on the old site:
https://github.com/MapStory/mapstory-meta/issues/669
https://github.com/MapStory/mapstory-meta/issues/1264

**Comment by jonpmarino** [comment]
Now that os-geo importer is up to latest, we can investigate the state of raster support that is supposed to be there

**Comment by Coop56** [comment]
django-osgeo-importer does support georeferenced raster files.  We need to make some business decisions around this about supporting raster without time.  Closing this specific ticket as it's complete.
