### ISSUE TITLE
Re-deploy Activity Feed to user profiles

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#306]
We de-activated the Activity Feed on user accounts because:

1) it was showing the creation of individual "chapters" as its own action, with links to chapters outside the context of their story and,

2) we weren't tracking users uploading of icons in the activity.

We should add the icon uploads to activity feed data and remove links to individual chapters, rather than just mapstories, and redeploy activity feed to user profile

**Acceptance Criteria:**

-Activity Feed added back to user profiles
-Chapters not showing up in activity feed w/ links outside the context of their story
-Icon commons uploads reflected in activity feed.

![screen shot 2016-12-18 at 11 32 49 pm](https://cloud.githubusercontent.com/assets/2573761/21302369/e169b7ce-c57b-11e6-8ad8-4494e2d31a9f.jpg)

**Comment by josellausas** [comment]
> **Acceptance Criteria:**
> 
> - [x] Activity Feed added back to user profiles
> - [x] Chapters not showing up in activity feed w/ links outside the context of their story
> - [ ] Icon commons uploads reflected in activity feed.

**Comment by josellausas** [comment]
Created a new issue for 'Icon commons uploads reflected in activity feed.' > #657

**Comment by josellausas** [comment]
Checking if working on the orange theme as well.
