### ISSUE TITLE
Normalize column names for imported data

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#307]
When a user imports a dataset, the wizard should allow the user to help sanitize and normalize attribute names to a common schema so that there is consistency with naming and casing of attributes labels within the application. This will also help avoid the use of reserved words as attribute names.

We could keep a mapping of changes and use as future suggestions at the point of upload.

Example fields extracted from the existing database used for the time field however we shouldn't limit it to time fields:

A_year
Date_start
Elect_year
Expend_Yea
Fake_end
Fake_start
ISO_time
New_start
Oil_year
a_starting
a_year
a_years
aa_year
acc_date_t
access_days_time
acq_date
acq_time
active_year
activitystart
age_as_year
alt_year
amend
amended_by
amendscan
annexdate
anxyear
apprehende
ar_start
area_year
award_date
backend_start
bd_blends
beg_yr_as_year
begin_date
begindate_as_year
begindate_xd
begintime
begintime_as_date
begintime_parsed
begintime_xd
beginyear
beginyear_parsed
beginyear_xd
birthdate
bldg_end_d
bldgyear
blk_read_time
blk_write_time
buffers_backend
buffers_backend_fsync
build date_xd
byear
cal_year
can_year
card_date
cc_year
changeyear
checkpoint_sync_time
checkpoint_write_time
checkpoints_timed
class_date
closedate
codes_date
commentend
cowedate
coweyear
cowsdate
cowsyear
cpit_year
cpiy_year
creation_time
cy1year
cy2year
d1_year
d_years
data_end
data_start
data_time
data_year
date
date1
date2
date_
date_1
date_2
date_as_year
date_built
date_created_xd
date_end
date_end_1
date_estab
date_field_as_year
date_format_as_year
date_new
date_of_bi
date_of_st
date_rec
date_st
date_start
date_started
date_text
date_time
date_xd
date_year
date_yr
datebymont_as_year
dateend
dateended
dateform
dateformed
datenum
dateoftrea
dateonly_as_year
dateopened
dates
datestart
datestarted
datet
datetext
datetime
datetime_as_year
datetime_precision
datetimes
days_year
deededdate
deis_end
deis_start
depl_year
descendant
description_as_year
dispatch date / time
dro_years
e1_year
e85_blender_pump
e_date_xd
e_year
e_years
earn_year
ec_date
efayear
elect_year
encendido
end
end date
end date / time
end date_parsed
end date_xd
end year
end2
end2_parsed
end2_xd
end_2
end_acq_dt
end_chg_ty
end_date
end_date_1
end_date_2
end_date_2_as_date
end_date_3
end_date__
end_date_as_year
end_date_parsed
end_date_xd
end_day_
end_month
end_month_
end_mp
end_n
end_parsed
end_period
end_ref
end_rule
end_serf
end_slave
end_time
end_xd
end_year
end_year_
end_yer
end_yr
end_yr_as_year
endate
endcong
endcong_1
enddate
enddate_as_year
enddate_parsed
enddate_parsed0
enddate_xd
enddate_xd0
enddatet
enddayofye
enddesc
ended
endingdate
endlat
endlng
endlon
endofperiod
endofperiod_parsed
endofperiod_xd
endorsemen
endowment
endtime
endyear
endyear_parsed
endyear_xd
ent_date_as_year
est_crime_time
event_date
eventdate
exp_year
expend_cou
expend_dol
expend_obj
expend_sta
expend_yea
eyear
f_date
f_date_ope
f_year
fake_end
fake_start
fakeyear
fakeyear2
fats_end
fats_start
fcc_as_year
fdate_xd
feis_end
feis_start
final_time
final_year
finaldate
fipscode_as_year
fire_date_as_year
fire_year
fire_year_as_date
firstpumparriving_attendancetime
fiscal_date
fiscal_year
friendlyca
friendlyki
friendlywi
from_date
full_year
g_year
g_years
gdp_year
gender
gender_gap
gni_year
gpp_year
gps_time
gr_year
h_years
hdi_years
hl_year
homes_year
ht_year
i_year
identity_start
if_year
iit_end_da
iit_start_
im_year
image_year
in_end
in_end_ref
in_start
in_timeline
insert date_as_year
instdate
int_start
is_udt_dependent
iso_date
iso_end
iso_start
iso_time
isodate
isotime
it_year
iv_year
iyear
job_end_dt
job_start_
k_time
ktime
l_year
l_years
lat_end
lat_start
legal_date
legend
lending_in
listyear
ln_year
local_time
long_end
long_start
longitude_as_year
lv_year
lymet_year
m_year
ma_time
ma_time_as_date
ma_time_as_year
minde_year
mn2_year
mp_years
msndate
mt_year_
multimed_1
multimedia
n_end_date
n_start_da
n_year
name_as_year
name_start
neg_k_time
neg_time
neo_year
new_date
new_end
new_start
newdate
newtime
numbackends
numpumpsattending
numstationswithpumpsattending
observation date_as_year
oid_as_year
oil_year
on_year
on_year_as_date
on_year_as_year
opendate
openyear
osm_timest
osmtimesta
outdated
p1_year
p_years
pan_time
parent_end
parl_year
peak_attendees
pend_litig
permit_end
pg_dbt_end
pg_end_dat
po_year
prek_year
prepare_time
prsend
prsstart
py10year
py1year
py2year
py3year
py4year
py5year
py6year
py7year
py8year
py9year
q_start
query_start
rate_year_
ratif_year
rc_year
realdate
repdate
repyear
result_cast_datetime_precision
road_year
s_year
sale_date
secondpumparriving_attendancetime
self_time
sh_year
shift_time
showtime_
sql_language_year
sset_year
start
start date
start date / time
start date_parsed
start date_xd
start1
start2
startDate
startTime
start_2
start_3
start_as_year
start_dat0
start_dat1
start_date
start_date_as_date
start_date_as_year
start_date_of_incident
start_date_parsed
start_date_xd
start_ear
start_month
start_n
start_parsed
start_ref
start_time
start_value
start_xd
start_year
start_year_parsed
start_year_xd
start_yr
startcon_1
startcong
startdate
startdate_parsed
startdate_xd
startdated
startdatef
startdatefix
startdayof
starting_d
startingdate
starttime
startup_s2
startup_s3
startup_s4
startup_so
startyear
startyear_parsed
startyear_xd
str_year
study_time
sum_year
sum_year_1
sum_year_2
surveyyear
syear
synoptime
t1_year
t2_year
t5_year
t_year
taxyear
teen_year
tempend
tempstart
terr_year
time
time observations started
time1
time2
time_
time_as_date
time_as_year
time_e
time_hhmms
time_of_report
time_over_
time_parsed
time_perio
time_preci
time_precision
time_s
time_tab_1
time_tab_2
time_table
time_txt
time_xd
time_year
timeend
timeend_parsed
timeend_xd
timeline
timeline_1
timeline_Y
timeline_e
timeline_s
timeline_y
timeofcall
timeofftar
timeofobservations
timeontarg
timeseries
timespan
timestam_1
timestamp
timestamp1
timestamp2
timestamp3
timestamp_
timestamp_as_date
timestart
timestart_parsed
timestart_xd
timezone
tmp_end
tmp_start
to
to_date
total_attended
total_time
tracktime
typsend
u_starting
ur_year
usa__date
vending
vendor
vendorid
verbatimel
verbatimev
w12_end_yr
w1_opendat
w1_opendat_as_date
w1_opendat_as_year
w1_opendat_parsed
w1_opendat_xd
wendi_name
who_year
wind_year
xact_start
year
year1
year2
year_
year_1
year_12
year_12_13
year_12_14
year_12_15
year_2
year_adm
year_annex
year_appea
year_as_da
year_as_date
year_as_year
year_b
year_blt
year_built
year_close
year_compl
year_cor
year_date
year_draft
year_e
year_elect
year_end
year_end_as_date
year_est
year_found
year_id
year_insta
year_long
year_nu
year_of_im
year_open
year_opene
year_ord
year_parsed
year_parsed0
year_purch
year_s
year_st
year_start
year_start_as_date
year_t
year_tex_1
year_tex_2
year_text
year_txt
year_xd
year_xd0
year_year
yearalter1
yearalter2
yearannex
yearblt
yearbuilt
yearcensus
yeardbl
yearend
yearparcel
yearpassed
years
years_on_f
yearstart
yearstring
yeartext
yeartxt
yearval
yearyear
yearyear2
yearyear3
yr_ce_end
yr_end
yr_start
zone year
zone_end_y
zone_year
ztime

**Comment by Coop56** [comment]
@davisc Since you already took the time to create this giant list - should we write a script to go through and change all of the field names outlined here to the normalized version?  (start_time or end_time)
