### ISSUE TITLE
transparency of viewer sidebar is too high - text not legible if strong styles are applied

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#311]
![screen shot 2016-12-12 at 10 23 55 am](https://cloud.githubusercontent.com/assets/2573761/21107076/162f59da-c056-11e6-90aa-3183db58f89c.jpg)
the current viewer sidebar has a transparency setting, so that the map, layers and styles are visible behind Chapter Info text. The current setting is too transparent. Text is difficult to read if strong stylers are applied.

In screenshot below, the line styling on the States is strong, and makes text difficult to read.

Research different settings based on different styles and apply fix.

**Comment by emilyashley** [comment]
Transparency has been decreased. 

Please let me know if the current transparency on production is still an active issue, if not we can close and remaining questions can be housed in a Story Viewer design story.

Thank you .

**Comment by glynnis** [comment]
Closing this. Please re-open if transparency is still an issue.
