### ISSUE TITLE
Icon Commons icons should show in a list without requiring search

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#316]
When a user is trying to add an icon to a point-layer style, the Icon Commons modal appears with no icons pre-loaded. Thus, it looks empty:

![screen shot 2018-07-23 at 7 33 15 pm](https://user-images.githubusercontent.com/2573761/43110073-9dbc5456-8eaf-11e8-9d42-ed93abf197e3.jpg)

![screen shot 2018-07-23 at 7 33 26 pm](https://user-images.githubusercontent.com/2573761/43110078-a3fd2660-8eaf-11e8-8edb-6a4b9827b2b1.jpg)

If a user knows what icons they are looking for, they can type in a keyword and have icons appear, but this requires already knowing what is there, something very few users will no.

Instead, the Icons Commons modal should appear with all icons pre-loaded into the modal so the user can see them. The text box to enter keywords should just function to reduce the Icons that appear to those that correspond with the Keyword (in other words, a filter).

**Comment by lhcramer** [comment]
Unclear what happened to the above screenshots, however, Issues remains valid in the story-tools based composer. 

Upon Selecting the Icons Common option for points styling and launching the "Select Modal", Enhance with having a list of icon thumbnails pre-populated (by most popular?) in addition to the keyword search function.
