### ISSUE TITLE
Use Core GeoNode

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#317]
Remove all of the custom MapStory specific code from our fork of Geonode so that we can stay up to Geonode master, and so that the Geonode tests will work.  Geonode is already fairly tested (and we can add tests and submit PRs to Geonode if anything is missing) so this will help get us a long way towards a high percentage of automated test coverage.

**Comment by sarasafavi** [comment]
This is going to be broken into multiple sub-issues over the next few sprints, will tag #317 as those are created

**Comment by sarasafavi** [comment]
PR up at https://github.com/MapStory/mapstory/pull/660
