### ISSUE TITLE
Update elastic search object so that if a user changes their name, their content attaches to new name

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#320]

**Comment by emilyashley** [comment]
Had some notes on this:

- 'first_name' & 'last_name' aren't on geonode's Profile Model but instead are in our EditProfileForm 

- our own custom mapstory_profile_post_save also calls geonode's profile_post_save

 - viewing the detail page of said resource will trigger the first / last name information to be updated in search results
