### ISSUE TITLE
Investigate a Check service to avoid uploading/importing of identical data

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#321]

**Comment by glynnis** [comment]
@jonpmarino Closing this for lack of detail. From the title, this sounds like a spike. Feel free to re-open after you've updated to include some of the detail specified by the [Spike template](https://github.com/MapStory/mapstory/wiki/How-to-create-a-spike), specifically: what is the deliverable? What questions should be answered by this task, and why?
