### ISSUE TITLE
Evaluate performance of vs.js

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#322]

**Comment by Coop56** [comment]
This one needs more information / context.  @jonpmarino @davisc?

**Comment by glynnis** [comment]
@jonpmarino Closing this for lack of detail. Feel free to re-open after you've updated to include some of the detail specified by the [Spike template](https://github.com/MapStory/mapstory/wiki/How-to-create-a-spike), specifically: what is the deliverable? What questions should be answered by this task, and why?
