### ISSUE TITLE
StoryPin media service used in maploom/composer needs to be configured for storytools/viewer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#330]
Steps to reproduce:

1. Go to mapstory composer
2. add a storypin
3. Paste a link to media in your storypin using one of our supported media services (i.e. flickr)
4. Confirm that the media link shows the media popping up as you play back your layer in composer
5. Publish your story.
6. Notice that your storypin media does not show up as an embed, but just as a text link in a published story.

(This is an issue of StoryTools not supporting MapLoom functionality.)

i.e. 

in composer, the embedded photo from flickr appears:

![screen shot 2017-01-26 at 2 15 38 pm](https://cloud.githubusercontent.com/assets/2573761/22348649/2adb97a0-e3d2-11e6-84a9-f0cba6f4df89.jpg)

Once the story is published, only the link appears.

![screen shot 2017-01-26 at 2 16 30 pm](https://cloud.githubusercontent.com/assets/2573761/22348677/3de5b330-e3d2-11e6-9d5c-c33eebe446db.jpg)

**Comment by trepagnier** [comment]
Merged here:
https://github.com/MapStory/story-tools/pull/254
