### ISSUE TITLE
Viewer does not appear to support ESRI basemap. Or confirm it works.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#337]
### Steps to reproduce

- [ ] Go to mapstory.org and login
- [ ] Create a new mapstory
- [ ] Create a new chapter
- [ ] Select the ESRI NGS basemap. For example:

![screen shot 2017-01-02 at 12 56 09 pm](https://cloud.githubusercontent.com/assets/2573761/21594670/ecf60f78-d0ea-11e6-84c2-6f98e9126ee8.jpg)

- [ ] Add a layer to your story and publish it

In viewer, the basemap is missing
![screen shot 2017-01-02 at 12 57 22 pm](https://cloud.githubusercontent.com/assets/2573761/21594680/0b3d97da-d0eb-11e6-9b4a-633602b2e984.jpg)
. For example:

I was logged in as jonpmarino.

Using Chrome Version 55.0.2883.95

On Jan 2 at 12:55pm

Example story used is https://mapstory.org/story/23415

**Comment by trepagnier** [comment]
Esri basemap removed from options here: https://github.com/MapStory/mapstory/pull/567
