### ISSUE TITLE
After deleting a message, user is brought to the wrong view

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#338]
Issue summary:
After deleting a message on your profile, you should remain on your profile page with the Messages tab open. Now, however, after deleting a mapstory, the user ends up on an "inbox" view that is not connected to Profile.

Steps to reproduce:
1) Login and go to user profile
2) Delete a message. If you don't have a message to delete, ask another user to send you a message
3) You will end up on a page like this (URL = https://mapstory.org/messages/inbox/):
![screen shot 2017-01-03 at 8 25 48 am](https://cloud.githubusercontent.com/assets/2573761/21610690/214f0352-d18f-11e6-81bc-2b56e75f7fb3.jpg)
4) Instead, after deleting a message you should should end up in a view like this:
![screen shot 2017-01-03 at 8 31 55 am](https://cloud.githubusercontent.com/assets/2573761/21610694/28d63b68-d18f-11e6-8472-2ab6e58c8634.jpg)

This bug was found on mapstory.org. Jan 3. Using Chrome version 55.0.2883.95 .

**Comment by glynnis** [comment]
@jonpmarino Just wanted to say that this is a fantastic bug report! Super clear and easy to understand, even without additional context :+1:

**Comment by glynnis** [comment]
@jonpmarino Could you add the URLs for these screen shots?

**Comment by emilyashley** [comment]
update: my go-to method of overwriting the django view or modifying url routing in mapstory/urls.py and/or views.py didn't change the behavior on reverse redirect. Attempted a rename of each, as well. Interested in looking into `geonode-user-messages`, @Coop56?

**Comment by Coop56** [comment]
@emilyashley Yeah I can take a look at this one as soon as I finish some other tickets.
