### ISSUE TITLE
Adding a media link as a StoryPin that isn't part of our white listed service causes an error

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#342]
Using mapstory.org with Chrome Version 55.0.2883.95 on Jan 3rd.

To reproduce:

1. Login and compose a new mapstory
2. add a layer to a chapter
3. create a storypin. 
4. Paste a link to a jpeg images from Wiki Commons (non supported service), such as:
![screen shot 2017-01-04 at 8 15 08 am](https://cloud.githubusercontent.com/assets/2573761/21645039/17eaecf0-d256-11e6-8af4-5c49703410d8.jpg)
5. The following error message pops up in composer and cannot be minimized:
![screen shot 2017-01-04 at 8 04 20 am](https://cloud.githubusercontent.com/assets/2573761/21645050/23dc5c60-d256-11e6-9517-500b23ad0b95.jpg)

Instead of this long developer-centered error message, we should show the user a human friendly explanation of what happened. Proposed text:

 _"Oh no! Your StoryPin links to a website that we don't support. Here's the list of ones we do support. Use one of these and try again: YouTube, Twitter, Imgur, SoundCloud, Flickr, Instagram, Vimeo and Vine"_

**Comment by trepagnier** [comment]
Will await Story-tools refactor before proceeding with this issue.
