### ISSUE TITLE
Improve truncation in  GeoWebCache when using parameterized caches

### ISSUE THREAD

**Issue by smithkm** [MapStory/mapstory#352]
* If a layer's data is edited by a WFS-T transaction, the embedded GWC listens for that event and truncates the cache in the bounding box of that transaction.  It does so across formats, gridsets, and styles the layer is configured to cache.  It does not do so across other parameters like time (it will only truncate for the default value).  Time filters are generally using regular expressions and so are not enumerable.

    - [X] https://github.com/GeoWebCache/geowebcache/issues/359

* When parameter filters change, they might 'orphan' old parametrized caches.  Style changes try to avoid this via a bunch of specialized code.  Other filters (Like time) are ignored and will 'leak' caches when changed.  Style handling still has the potential to leak as well if things go wrong.  Once leaked a cache will just sit there until DiskQuota purges it (if DiskQuota is enabled).  Solving this would make other things possible in future like dynamic parameter filters (Such as a TIME filter looks at the dimension info in the layer metadata in order to configure itself. This could also simplify the implementation of the STYLES filter.)

    - [X] https://github.com/GeoWebCache/geowebcache/issues/170
    - [X] https://github.com/GeoWebCache/geowebcache/issues/257

**Comment by smithkm** [comment]
I was working on this 2 years ago.  Hopefully I can salvage something https://github.com/smithkm/geowebcache/commit/6f0d1961529e6da163b44eb4b3965cde29b76d23

**Comment by smithkm** [comment]
Rebasing the old work doesn't look like it's worth the effort.  Looking it over should still help getting me back to understanding what I need to do faster this time.

**Comment by smithkm** [comment]
GWC PR: https://github.com/GeoWebCache/geowebcache/pull/505
GS PR: https://github.com/geoserver/geoserver/pull/2206

**Comment by jonpmarino** [comment]
@smithkm is this still an active issue? And what other work would be needed from you for MapStory to be able to turn on geowebcache?

**Comment by smithkm** [comment]
All the changes should be in stable releases of GeoWebCache or GeoServer now except the bounds expander which is a plugin that can be built and dropped into an otherwise stock GeoServer and doesn't require any setup.

**Comment by cuttlefish** [comment]
@smithkm I'll slack you about the deployments
