### ISSUE TITLE
Adding a feature in edit mode to a newly uploaded layer causes a 504 error

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#357]
At mapstory.org, on Jan 11 using Robert LaFollette user account on Chrome Version 55.0.2883.95, I 

1. Went to this StoryLayer, https://mapstory.org/layers/geonode:prisons_jan_11
2. Clicked "edit storylayer"
3. In edit mode, _added_ a new feature located on the southern tip of Greenland with date 1930. Put FID as 1.
4. Clicked save.
5. Received the 504 error message indicated in the screenshot.
![screen shot 2017-01-11 at 10 23 34 am](https://cloud.githubusercontent.com/assets/2573761/21857009/93a59258-d7e9-11e6-9c81-9eb464dccf9a.jpg)

**Comment by jonpmarino** [comment]
Just noticed that the edit i made actually is appearing in the "contributions" tab on viewer page. But the newly added feature _does not_ show up in playback of the layer, so it does not appear to be there by any viewer of the layer. (again, the newly added feature was placed at the southern tip of Greenland in 1930). This playback issue for added features is captured on Jira as https://issues.boundlessgeo.com:8443/browse/MSSS-177. 
![screen shot 2017-01-11 at 10 44 57 am](https://cloud.githubusercontent.com/assets/2573761/21857513/5849d6b8-d7eb-11e6-96d7-125f7014620c.jpg)

**Comment by Coop56** [comment]
I'm unable to reproduce this on local or demo, so this is a production only issue.

**Comment by jonpmarino** [comment]
Moving out of 0.0 milestone based on @Coop56. Will re-evaluate once we have docker deployment and more parity between demo and prod to know if this is still an issue

**Comment by jonpmarino** [comment]
additional context:

We just tested the scenario of _editing_ the geometry of an existing feature on mapstory.org and got the same result. The error message depicted below appeared when saving the edit. But, upon further review you can see that the feature was actually moved successfully, and the edit is captured in the edit history. In the example below, the feature was moved from southeast Texas to the tip of Venezuela.

![screen shot 2017-02-07 at 1 16 58 pm](https://cloud.githubusercontent.com/assets/2573761/22707469/7f0c747e-ed38-11e6-9460-81abc8498fd1.jpg)

![screen shot 2017-02-07 at 1 17 13 pm](https://cloud.githubusercontent.com/assets/2573761/22707482/87f05362-ed38-11e6-94fb-9e241c3cf8d0.jpg)

![screen shot 2017-02-07 at 1 18 40 pm](https://cloud.githubusercontent.com/assets/2573761/22707494/9326a952-ed38-11e6-9252-df3bf94380a0.jpg)

**Comment by jonpmarino** [comment]
so, just tested a new layer (https://mapstory.org/layers/geonode:prisons_myneekx) with new user account williambutleryeats, made edits to it and logged of an on to sojournertruth and made another edit. all worked without the error. so, given that this was originally only a prod issue (no local or demo) i'm closing for now.
