### ISSUE TITLE
first edit showing as anonymous in layer history in composer

### ISSUE THREAD

**Issue by Shepsara** [MapStory/mapstory#360]
![image](https://cloud.githubusercontent.com/assets/13316560/22032578/ecd1d102-dcb2-11e6-8839-6709d3515814.png)

1. I imported a layer
2. edited a feature on that layer
3. checked history and noticed that the first edit was labeled anonymous instead of my name
I was logged in as debbieberry using mapstory.org on Chrome Version 55.0.2883.87 m on January 17th at about  12:30pm

**Comment by jonpmarino** [comment]
Noticed that the username _is_ actually being captured in the detail page edit history. But, it does show up as anonymous in the edit-layer view (link to detail page for that layer is https://mapstory.org/layers/geonode:mlk_speeches_deb_z7jqe0n) 
![screen shot 2017-01-17 at 12 27 48 pm](https://cloud.githubusercontent.com/assets/2573761/22034032/749a4450-dcb0-11e6-808a-59d30ecfb7e2.jpg)

**Comment by jonpmarino** [comment]
today created a new layer as johnglenn and added several features. The "Contributions" tab on the detail page shows all edits as being done by admin. In the "edit layer" mode it shows the first edit being done by admin, and the rest by johnglenn.

![screen shot 2017-01-23 at 10 54 44 am](https://cloud.githubusercontent.com/assets/2573761/22213653/9f6f5626-e15a-11e6-9ede-e7ecb87c8c72.jpg)

![screen shot 2017-01-23 at 11 11 32 am](https://cloud.githubusercontent.com/assets/2573761/22214314/cb9fb914-e15c-11e6-9662-005e8777f9ec.jpg)

**Comment by emilyashley** [comment]
note: I was the last to edit the [detail page html](https://github.com/MapStory/mapstory/blob/master/mapstory/templates/layers/_geogig_layer_detail.html#L29) and [geogig controller](https://github.com/MapStory/geonode/blob/master/geonode/contrib/geogig/static/geogig/geogig.js) so tossing in these quick links and notes. 

Previously on the detail page `commit.author.name` housed the long First Last formatted name that was only available __after__ the geogig store was initialized (i.e. the 2nd commit) iirc.  `commit.committer.name` houses the username supplied by the first commit. We nixed the use of First Last format (and consequently, author.name) [here](https://github.com/MapStory/mapstory/commit/603e2489de539faf90d11d60bfafa156b0881a81#diff-2e5d01236fa8e1414ac1b0d087c00a9dL32) to maintain a user-facing unique ID for layer editing accountability. Unsure if these changes made it into composer or editor.

Questions for @jonpmarino: Is John Glenn an admin or superuser? I can see the screen shot of JohnGlenn viewing the layer history, but I don't see a screenshot of the initial import and subsequent edits, can you visually verify (reproduce if needed) that JohnGlenn was the user logged in for these actions?

**Comment by reynalddizon** [comment]
<img width="1280" alt="screen shot 2017-01-26 at 4 47 19 pm" src="https://cloud.githubusercontent.com/assets/4611843/22341132/97e384ba-e3e7-11e6-9d75-53ba10e2df52.png">

checked this issue with jon, and i didn't get that issue with my newly created layer using my regular non-admin account.

**Comment by jonpmarino** [comment]
hey @emilyashley johnglenn is not admin or superuser. that layer was created with the Create tool, so no data was imported. once the layer was created the "edit features" tool was used to add the features. I can't reproduce at the minute due to timeout errors with the Create Layer tool, but will try again at another time. Here's my hypothesis. When Rey creates a layer it does show up correctly in the edit history on the detail page as his user name (he added a screenshot above). I think that although I was logged in as johnglenn, who isn't admin or superuser, perhaps on Geoserver i was logged in as admin. Perhaps because I had used jonpmarino account in an earlier session (which is admin) and, although logged off and done a hard referesh, geoserver still didn't log me off as admin.  That issue is logged as #383

**Comment by emilyashley** [comment]
this could tie into #447

**Comment by jonpmarino** [comment]
now it looks like its admin, not anonymous per #504
