### ISSUE TITLE
Update to OSGEO Importer Master

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory#362]
This is a spike issue that will encompass many other issues.  The goal for this spike is to research what it will take to get us upgraded to the master version of django-osgeo-importer.  I will create separate issues out of this one and reference this issue.

Once all of those issues are completed and we're officially using the latest version of django-osgeo-importer this issue will be considered complete.

**Comment by sarasafavi** [comment]
I've added a related issue at https://github.com/MapStory/mapstory/issues/642

#642 is a blocker to #317's completion, but I understand it may be rendered obsolete by the work being done in #362's related issues.

**Comment by Coop56** [comment]
Our fork of Geonode and the version of Geonode that django-osgeo-importer is using are extremely incompatible.  This task needs to hold off until @sarasafavi finishes the Geonode work and we're on a similar or the same branch of Geonode as importer uses.

**Comment by sarasafavi** [comment]
@Coop56 reminder that https://github.com/MapStory/mapstory/issues/642 is a blocker to #317 being merged, so working on that now while you consider this pending would probably be a good idea
