### ISSUE TITLE
The download schema for append adds additional fields which makes it unclear what a user should do

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#363]
**Background:**

![screen shot 2017-01-18 at 6 05 48 pm](https://cloud.githubusercontent.com/assets/2573761/22088335/ed38e7c4-dda8-11e6-8e22-79aaec106413.jpg)

The purpose of the Append function is to let a user add several edits to a StoryLayer at once. The current workflow for doing this to go to a StoryLayer, click "Append", download a blank schema, add your features to this schema, return to the Append modal, and proceed. The user expectation after a successful Append is that the new features they added will show up on the map canvas when the layer is played, and will show up in the "edit history" when a user goes to edit mode for the layer.

_note: there is probably a better workflow for this we should look at in the edit-layer redesign work. But, for now the goal is to have what we present work._

**Issue**

When downloading the blank schema, 3 additional columns are added to the schema that aren't part of the original StoryLayer uploaded by a user: 1) FID 2) ogc_fid and 3) wkb_geometry.

![screen shot 2017-01-18 at 5 58 46 pm](https://cloud.githubusercontent.com/assets/2573761/22088354/0d56355c-dda9-11e6-8c79-1e16f089ea84.jpg)

Its not at all clear what a user who is seeking to append features to a StoryLayer should do with these three additional fields. Are they to be left blank? Should place holder values be put there? 

Seems like we need to either prevent these additional fields from being generated, or communicate to the user what their correct action should be.

**Comment by reynalddizon** [comment]
<img width="1280" alt="screen shot 2017-01-20 at 3 22 04 pm" src="https://cloud.githubusercontent.com/assets/4611843/22154659/4400a3e0-df24-11e6-8534-43f5e24e2bea.png">

I've tried appending before and i got extra columns like ogc_fid, fid and wkb_geometry. But this time i got a "geometry" column. Quite unclear what to do with it.

**Comment by Coop56** [comment]
A quick update.  I've gotten these fields removed for CSV downloads, next up I'll be working on SHP downloads.

**Comment by cuttlefish** [comment]
I'm not sure if it's related or not, but I'm getting 500s on `demo` and `prod`
```Internal Server Error: /layers/download-append-csv
Traceback (most recent call last):
  File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/git/mapstory/mapstory/mapstory/views.py", line 858, in download_append_csv
    csv_url = request.session['csv_link']
  File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'csv_link'```

**Comment by cuttlefish** [comment]
Something has changed since this was written which is breaking it. I'm bumping it to back to `in progress`.

**Comment by jonpmarino** [comment]
On demo I got the first screen shot..."internal server error". On prod I get the second.
![screen shot 2017-03-09 at 6 32 28 pm](https://cloud.githubusercontent.com/assets/2573761/23776927/e5d8cd94-04f6-11e7-9afe-d0b139ed027c.jpg)
![screen shot 2017-03-09 at 6 32 14 pm](https://cloud.githubusercontent.com/assets/2573761/23776935/f02fa1f0-04f6-11e7-9ba3-964060318d64.jpg)

**Comment by Coop56** [comment]
This issue was closed long ago, I just reverified it.  Closing.
