### ISSUE TITLE
Ensure Viewer only shows one world

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#365]
Users with no data can use the CREATE STORYLAYER wizard to create a new storylayer that is empty, and then use the "edit" functionality to add features to the empty storylayer. 

In our current UI there is no method for setting the starting "zoom level" of a created layer. As a result, newly created StoryLayers look like this:

![screen shot 2017-01-19 at 12 06 52 pm](https://cloud.githubusercontent.com/assets/2573761/22119531/8b27b378-de41-11e6-96b5-04d706d27544.jpg)

StoryLayers created with imported data are assigned a starting zoom level based on their data. MapStories have a starting zoom level set in the composer itself. So, this is a unique problem for storylayers created with CREATE STORYLAYER wizard.

Thoughts:
- it might be good for starters just to change the current default setting that shows the maximum zoom-out (3 versions of continents show) to just one view of the world. Like this:
![screen shot 2017-01-19 at 12 07 42 pm](https://cloud.githubusercontent.com/assets/2573761/22119587/c430d3c0-de41-11e6-850b-045afc072755.jpg)

- In edit-layer mode we probably need a place for editors to change the default zoom level for the layer. As new features are added presumably the zoom level will need to change. For example, imagine a created storylayer for "beer breweries of america". The person starting it might begin in Virginia, so the default zoom level should be zoomed in on Virginia to highlight those features. But, once editors add breweries in other states, the zoom level should move out.

**Comment by Coop56** [comment]
@jonpmarino Did a quick investigation on this, it actually doesn't have anything to do with Create itself.  This has to do with the viewer allowing you to zoom out too far, and showing multiple worlds.  We can shut off the wrapping with the openlayers option wrapX = false.  This will need to be done in StoryTools.  Showed it to @darinacosta  and he's going to take on this ticket since he already has a working StoryTools development environment setup.

**Comment by trepagnier** [comment]
Merged here: MapStory/story-tools#256

**Comment by cuttlefish** [comment]
This isn't working in production. I'm going to try reloading its copy of story-tools.

**Comment by cuttlefish** [comment]
I got it working.
