### ISSUE TITLE
Update Create StoryLayer modal text so it tells user not to use "name" as a field title

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#368]
Errors will occur if a user creates a StoryLayer with the attribute title "name". The layer creates, but once the user gets to the step of adding features, the attribute with the title "name" will not appear.

Our current modal text in Create StoryLayer at the Attributes step looks like this:

![screen shot 2017-01-19 at 4 55 45 pm](https://cloud.githubusercontent.com/assets/2573761/22128841/3104b662-de68-11e6-84bf-bc52a3b0bd6c.jpg)

We should update this text to be accurate to current functionality. Proposed text:

"Now, define your attributes for this StoryLayer. Attributes are pieces of information that explain a feature. For example, if you are collecting features about libraries, your Attributes might be "Year Founded" and "Library Name". One thing to note: don't give any of your attributes the title "name". This will cause errors in the creation process.

**Comment by glynnis** [comment]
> One thing to note: don't give any of your attributes the title "name". This will cause errors in the creation process.

@emilyashley Is there a way that we could sanitize or validate entries? Ideally the message above would only show if a user types in "name" and tries to submit, and then we'd show it as an error in close proximity to that input field (like when you try to create a bad password, you might see something like "Password must be longer than 8 characters and include at least one capital letter", etc.). Putting direction like this in a body of instructions is kind of awkward and will likely be overlooked by users, so we should be smarter about it if we can.

@emilyashley Let me know what might be possible here and I can design/advise appropriately.

**Comment by Coop56** [comment]
Chiming in here - @glynnis is on the right track.  We should validate these fields on the front end.  I already worked another issue where if users type capital letters, spaces or special characters into this I sanitize the input on the backend and replace spaces and special characters with underscores.

But for something like this where they can't choose a certain word or words, I would say front end validation is ideal.

**Comment by Coop56** [comment]
This is addressed in #478.
