### ISSUE TITLE
New default avatar for users

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#370]
As a user of MapStory
I want to have a default avatar that represents a person
So that there's a better image to represent me until I add one myself

Acceptance Criteria
- The avatar should look good on both MapStory and StoryScapes
- The avatar will replace the default avatar that comes from Gravatar, which stands out due to its blue color (and doesn't represent a person very well)

Deliverable: 70 x 70px avatar for 35x35 display (2x for retina support)

**Comment by glynnis** [comment]
![default_avatar](https://cloud.githubusercontent.com/assets/1529366/22158222/db34f960-df00-11e6-8948-cc93adf6acd0.png)

@emilyashley Here's the avatar! As mentioned in the issue, this is at 2x to support retina screens, but you'll want to display it at the current size of 35x35px. I'm sending this to you on Slack as well in case github compresses the image.

**Comment by glynnis** [comment]
Let me know if I need to adjust due to the border radius -- I guessed at the circle size for the background color, but we could possibly handle that through CSS. Happy to tweak if it gives you any trouble.

**Comment by emilyashley** [comment]
cc: @cuttlefish 

Static files: https://github.com/MapStory/mapstory-assets/tree/master/design_assets/2017_01_18%20-%20default%20user%20avatar

settings: https://django-avatar.readthedocs.io/en/latest/#AVATAR_GRAVATAR_DEFAULT
