### ISSUE TITLE
Add hyperlink to "Learn more about creating data" text in the Create Layer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#372]
In the Create Layer modal, we need the words "Learn more about creating StoryLayers" to link to https://mapstory.org/getstarted.

![screen shot 2017-01-20 at 12 16 00 pm](https://cloud.githubusercontent.com/assets/2573761/22160441/1a16d1f8-df0b-11e6-8dd4-e986663c7ed9.jpg)

Or, we could remove the text there if that is easier for now.

**Comment by emilyashley** [comment]
html [here](https://github.com/MapStory/mapstory/blob/master/mapstory/static/mapstory/partials/createLayerModal.html#L162)

**Comment by Coop56** [comment]
This is addressed in #478.

**Comment by cuttlefish** [comment]
Production seems to be directing to `getskills` rather than `getstarted`
I'm not sure if this is a deployment/config problem or not.
