### ISSUE TITLE
Improve user experience for Explore

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#377]
As a user exploring MapStory
I want to find MapStories, StoryLayers, and users easily
In order to explore the site and find content that is relevant to my interests

Acceptance Criteria
- Searching for users and searching for content should remain separate (with separate search bars), since the APIs are distinct
- Represent top tags, category, and storyteller search for content
- Make sorting and filtering (and the differences between them) more distinct and understandable to the user.

Deliverable: high-fidelity mock-up & discussions with @emilyashley for front end implementation. Any CSS work or additional effort beyond the mock-up should be addressed in a separate issue.

**Comment by glynnis** [comment]
First pass mock-up for content page of Explore:

[Outdated mockup](https://cloud.githubusercontent.com/assets/1529366/22309334/733b42c4-e310-11e6-8e13-847434fa8406.png)
Updated to show: "Showing 1-9 of 100 results" text, remove avatars, and add "clear" links to each filter section, plus magnifying glass icons to each search box.

[Outdated mockup](https://cloud.githubusercontent.com/assets/1529366/22308454/a2e653be-e30c-11e6-95a7-bf323fe60205.png)

**Comment by glynnis** [comment]
When no results match for content:
[Outdated mockup](https://cloud.githubusercontent.com/assets/1529366/22309801/6e7935d2-e312-11e6-881a-7293cc117883.png)

When no results match for people:

[Outdated mockup](https://cloud.githubusercontent.com/assets/1529366/22309795/6a1d3b00-e312-11e6-8b20-62a6f45c6233.png)

**Comment by emilyashley** [comment]
Thank you @glynnis :tophat:

**Comment by glynnis** [comment]
Updated per @jonpmarino to replace "People" with "StoryTellers".
![explore_v2 - no results content](https://cloud.githubusercontent.com/assets/1529366/22337453/924a670e-e3aa-11e6-9ba6-493d0f1155e0.png)

![explore_v2 - no results people](https://cloud.githubusercontent.com/assets/1529366/22337574/e8f81a74-e3aa-11e6-9ad7-edabf7370dac.png)

![explore_v2](https://cloud.githubusercontent.com/assets/1529366/22337454/924aca82-e3aa-11e6-8931-9ba6e049ff1a.png)

**Comment by glynnis** [comment]
StoryTellers page:
![explore_v2 - storytellers](https://cloud.githubusercontent.com/assets/1529366/22342143/ef1fa882-e3b8-11e6-8db8-68be5be4fb9c.png)

**Comment by glynnis** [comment]
<img width="88" alt="default_avatar_lg" src="https://cloud.githubusercontent.com/assets/1529366/22342527/5cff4f50-e3ba-11e6-9b24-adff119c7eca.png">
Sent this to @emilyashley on slack -- a larger version of the default avatar, which will be necessary given the size that avatars display on the Explore page. Adding here for documentation sake, though Github's uploader may have compressed this. Ask me if you need to download this file for use and I can get you the uncompressed version.
