### ISSUE TITLE
Remove link to "example" in the Type step of the Create Layer modal

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#380]
In the "Type" step of the Create Layer modal there is the word "example" which implies a link to an example. Let's eliminate that word for now.
![screen shot 2017-01-26 at 10 58 10 am](https://cloud.githubusercontent.com/assets/2573761/22341568/e52ea96a-e3b6-11e6-915d-83bf91e2af13.jpg)

Related #372

**Comment by jonpmarino** [comment]
hold off on this until we have green light from @Coop56 to make link clean-up changes on Create and Append modals

**Comment by emilyashley** [comment]
note to self: I think this lives [here](https://github.com/MapStory/mapstory/blob/master/mapstory/static/mapstory/partials/createLayerModal.html#L35)

**Comment by Coop56** [comment]
This is addressed in #478.
