### ISSUE TITLE
GeoServer and GeoNode logon/logoff not synced

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#383]
If a user has multiple user accounts on mapstory.org and logs out on mapstory.org and logins with a different user account, the user is _not_ also logged off and on to the new account in GeoServer.

For example, currently logged in as AlbertaEinstein
![screen shot 2017-01-26 at 12 18 36 pm](https://cloud.githubusercontent.com/assets/2573761/22344480/0041772c-e3c2-11e6-97ef-a6b94818b5e6.jpg)

Geoserver shows AlbertaEinstein logged in.

![screen shot 2017-01-26 at 12 19 24 pm](https://cloud.githubusercontent.com/assets/2573761/22344741/e05d04e8-e3c2-11e6-9ba1-81e7d97848f3.jpg)

Log off AlbertaEinstein and into another account, johnglenn.

![screen shot 2017-01-26 at 12 33 23 pm](https://cloud.githubusercontent.com/assets/2573761/22344950/be8c6ccc-e3c3-11e6-9bba-b519d9fd8f2a.jpg)

In GeoServer, still logged in as AlbertaEinstein

![screen shot 2017-01-26 at 12 33 37 pm](https://cloud.githubusercontent.com/assets/2573761/22344970/df74a5b2-e3c3-11e6-9e07-fb89bf5e5c40.jpg)

**Comment by Coop56** [comment]
This is no longer relevant because the way we do this has changed with Geofence.  Closing.
