### ISSUE TITLE
Edit Feature and Append Features options don't appear on detail page for layers created with Create modal

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#387]
(confirmed with @Coop56)

Expected behavior:

The purpose of the Create StoryLayer tool is to empower a user that doesn't have starter data to upload for a given topic to be able to "launch" an empty storylayer and through editing to be able to begin adding features. If the storylayer is opened for community editing when it is created, then any registered user should be able to add/edit features on the storylayer as well, thus allow groups to work together in the collection of data for a layer right in the web browser.

Issue:
The Edit Feature and Append Data options don't seem to appear on the detail page for layers created with the create layer. For example, on demo.mapstory.org, logged in as "pierrelenfant" and viewing Beer Breweries Jan 27 layer, which was created by Isaiah Bowman using create layer. There are no Edit Features or Append Data options:

![screen shot 2017-01-27 at 3 26 51 pm](https://cloud.githubusercontent.com/assets/2573761/22388299/7e9f58b2-e4a5-11e6-9fb5-ac1f0a1d7a1e.jpg)

But, still logged in as "pierrelenfant" and viewing another layer uploaded by Isaiah Bowman, the Edit Features and Append Data options appear:

![screen shot 2017-01-27 at 3 28 20 pm](https://cloud.githubusercontent.com/assets/2573761/22388320/9bc24bb6-e4a5-11e6-95ca-afc125450856.jpg)

to reproduce:

To reproduce this, you must have access to 2 user accounts, or work with another user.

1. Log in and create a layer using "Create Layer"
2. Also create a second layer by uploading data
3. make sure both of your layers are set to enable community editing
4. Log in as a different user. 
5. Go the detail page for each layer and see if the Edit Features and Append Data options appear.

**Comment by Coop56** [comment]
This has been fixed for all newly created layers and the fix was in osgeo-importer so it's already live on production.
