### ISSUE TITLE
Composer is loading many dozens of WMS layers that aren't used

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#391]
This drastically slows down the initial load of composer.

I counted approx 100 being loaded on demo.

**Comment by cuttlefish** [comment]
Some of these seem to take so long because the browser will only allow so many concurrent requests at once. Solving this may mitigate some cases for #392.

**Comment by cuttlefish** [comment]
Setting `var searchUrl = '/api/layers/search/?limit=100';` to be 1 instead of 100 seems to mitigate this.
Line 628 of `common/addlayers/ServerService.js` in MapLoom.
I assume this isn't the correct thing to do, but I'm not really setup at the moment for doing MapLoom development.
Whatever is going on here, we shouldn't be loading 100 layers when we load MapLoom.

**Comment by emilyashley** [comment]
note to self: defer search until modal "add-layer-dialog" / "loom-addlayers" is exposed on [click](https://github.com/MapStory/MapLoom/blob/feature/composer-wip/src/common/sidebar/partials/storyLayers.tpl.html#L8)

**Comment by Coop56** [comment]
So what do we want to do here?  How many layers do we want to load off the bat when a user clicks the modal to add a layer?  We can defer the loading of course like you said above @emilyashley but when we do load it how many do we want the user to see initially?

@jonpmarino @glynnis @emilyashley @tbattle?  Anyone have an opinion?

**Comment by jonpmarino** [comment]
original idea was, when opening mini-explore, the user would see the layers they've favorited, the layers they own, and a small number of "most common layers". ones like US states or global countries. could just use the "popular" filter available in explore to take like the top 20 (or some number) based on popularity. i don't know the implications for load times and what number makes sense.

**Comment by cuttlefish** [comment]
There are two problems here.
1) It's loading a ton of layers that aren't being used.
2) Instead of loading a thumbnail it's doing a full WMS request.

We shouldn't even be loading that many thumbnails upfront.
