### ISSUE TITLE
Add back social logins

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#395]
We removed Facebook and Google login icons from the Sign Up and Login modals so those services weren't open for use while they were outdated from latest versions. That work was completed by @Coop56. Now just need to add back the icons on the modals and reactivate the service

Need to get addressed before we open up registration again aggressively to any new users...also because many previous users created accounts using Facebook and Google logins

![screen shot 2017-01-31 at 10 07 37 am](https://cloud.githubusercontent.com/assets/2573761/22473281/016e2f02-e79e-11e6-8682-6c2437b0d608.jpg)
![screen shot 2017-01-31 at 10 07 23 am](https://cloud.githubusercontent.com/assets/2573761/22473290/095489fa-e79e-11e6-934e-1649d8ca86c8.jpg)

**Comment by glynnis** [comment]
@Coop56 Do you need any design input here? Sounds like this involves reinstating something that existed previously, so there may not be much to tweak from a UI standpoint.

Let me know if that's not the case -- happy to assist!

**Comment by jonpmarino** [comment]
Rey and I are getting errors when testing social login. Could this be because we have prior existing accounts? I will find a few people who have never created mapstory accounts to test.
![screen shot 2017-03-17 at 9 39 48 am](https://cloud.githubusercontent.com/assets/2573761/24048152/f580ec72-0af5-11e7-9269-911f4b481e13.jpg)

**Comment by jonpmarino** [comment]
confirmed working with google account "John Evans" so closing. Note - if a user already has an account with a registered email address and then tries to use a google login separately, it will not work.
