### ISSUE TITLE
Line styling

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory#396]
I'm making a mapstory using the storylayer railroads0123 (https://mapstory.org/layers/geonode:railroads0123) to test the different line styling options. Of the four options (simple, unique, choropleth and graduated), only simple and unique work. 

Railroads0123 contains the numerical column, volume, to test choropleth and graduated styles.

Here's the result:
1. Choropleth doesn't appear as one of the options.
2. Graduated is an option but after I set up the classification parameters like column source and number of breaks, etc, there are no features on the map display but the range of values generated by the classification is displayed in the sidebar.

<img width="1280" alt="screen shot 2017-01-31 at 5 34 06 pm" src="https://cloud.githubusercontent.com/assets/4611843/22476890/dc9808f4-e7db-11e6-8db3-ff60ddb931ab.png">

**Comment by davisc** [comment]
Vote to defer to future due to evaluation of MapBox Styles
