### ISSUE TITLE
Chapter buttons get covered up by playbar on mapstory detail page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#412]
A published mapstory with several chapters and chapter info content has the chapter advance buttons covered up by the playback bar.

(this view is generated on Chrome with a 13 inch Macbook. Zoom level is normal 100%, although it seems to hold true if the browser is zoomed in and out.)

![screen shot 2017-02-01 at 4 25 26 pm](https://cloud.githubusercontent.com/assets/2573761/22529145/ee82dc86-e89b-11e6-91e1-1b57af2aea49.jpg)

**Comment by emilyashley** [comment]
I had attempted to address this previously, [here](https://github.com/MapStory/mapstory/commit/90f9bcd2ba69614126f8a4e3a80dcf662b6a8b6f#diff-703495917169eda6694707687ea0ade5R39). Lemme take a double look.

**Comment by glynnis** [comment]
@emilyashley My bad! I forgot to move this to "In Progress" -- I'm currently working on this.
