### ISSUE TITLE
Stories published using OSM basemaps appear to have no basemap

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#413]
(second-opinion confirmed with Jon and Rey using Chrome Version 55.0.2883.95

Steps to reproduce:

1. login and launch composer
2. use Open Streetmap or Humanitarian OpenStreetmap as the basemap for your chapter.
3. Add a layer and maybe a storypin to your story
4. Publish your story.
5. The basemap behind your published story appears to be missing.

Examples:
https://mapstory.org/story/23727 uses OSM basemap.

**Comment by davisc** [comment]
Note: New composer should provide a config validation step  (turbotax) prior to actually publishing the story so that the user can confirm all expect info is there.. I have a prototype that summarizes all of the information.

**Comment by darinacosta** [comment]
Merged here: https://github.com/MapStory/story-tools/pull/256

**Comment by trepagnier** [comment]
Merged here: https://github.com/MapStory/story-tools/pull/257
