### ISSUE TITLE
Remove other options besides pause playback from composer for storypins, or get the other options working

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#414]
This is a placeholder issue to keep notes about the performance of "pause playback" for storypins. Once we have a more precise understanding of what is happening and what the issue and solution is, we can refine the ticket and add to appropriate priority level.

**Desired State:**

In composer, the user has the ability to decide if he/she wants playback to "pause" when a StoryPin's start time is reached, or if playback should continue once the StoryPin's start time is reached.

**Current State**

We are getting different outcomes with pause playback currently. Sometimes it seems to pause when Pause Playback is _not selected_. Other times it seems to not pause when it _is selected_.  Hard to tell if irregularities are due to browser, caching on the viewer, other factors in the storypin setting (i.e. if "show content automatically" is selected versus not selected).

**Comment by trepagnier** [comment]
https://github.com/MapStory/MapLoom/pull/29 resolves this issue

**Comment by jonpmarino** [comment]
I see https://github.com/MapStory/MapLoom/pull/29 removed pause playback.

Now that we are getting some stories published and have #1520 , it would be nice to be able to have the layers in a chapter pause while embedded media autoplays. So, the use case would be if i have a video in a pin and have enabled it to "autoplay", autoplay means the playback pauses until the video is over.
