### ISSUE TITLE
Add links to home and profile in composer sidebar

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#420]
1. Add link to mapstory.org on the house icon and text MapStory
2. Add link to profile on the Username.

![screen shot 2017-02-08 at 12 05 47 pm](https://cloud.githubusercontent.com/assets/2573761/22750597/09d4f266-edf7-11e6-933a-b941f84af2b8.jpg)

Should be a hard exit from composer, not a new tab. Same behavior as the "exit" bottom in edit layer mode (referenced below):
![screen shot 2017-02-08 at 12 07 23 pm](https://cloud.githubusercontent.com/assets/2573761/22750651/4010cbb6-edf7-11e6-910c-350a22be198e.jpg)

**Comment by glynnis** [comment]
Work on this is complete and this is just waiting for review.

**Comment by trepagnier** [comment]
Merged here: https://github.com/MapStory/MapLoom/pull/27

**Comment by cuttlefish** [comment]
These links don't seem to be working on `demo`.

**Comment by trepagnier** [comment]
@cuttlefish looks like the changes from https://github.com/MapStory/MapLoom/pull/27 haven't made their way onto demo yet
