### ISSUE TITLE
label site as "beta" once ready for release

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#421]
to tailor user expectations.

**Comment by glynnis** [comment]
Going to add a "Beta" tag to the header so it's visible from most pages of the site.
![screen shot 2017-02-07 at 10 14 03 am](https://cloud.githubusercontent.com/assets/1529366/22699813/3e58bc22-ed1e-11e6-8993-2ab1ddc7f34a.png)

**Comment by glynnis** [comment]
@davisc Is the beta tag only desired for the Mapstory.org theme, or is that something we want visible for other customers/themes too?

**Comment by davisc** [comment]
@glynnis just for mapstory

**Comment by glynnis** [comment]
This PR has already been merged. Closing.
