### ISSUE TITLE
Make StoryLayer and MapStory label on explore different colors

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#423]
A slight color difference in these labels will make it much easier to see which cards are for storylayers and which are for mapstories. For colors, we could use 'mapstory brown' and 'mapstory orange' (should be in @reynalddizon style guide).

![screen shot 2017-02-08 at 11 59 17 am](https://cloud.githubusercontent.com/assets/2573761/22750361/2112785a-edf6-11e6-9eb8-f60fb19a8d23.jpg)

**Comment by emilyashley** [comment]
Right on.  In the mockup I'm working from they're both grey. Thoughts @glynnis? We can easily change this when we go over the css on explore page.

**Comment by glynnis** [comment]
![explore_v2](https://cloud.githubusercontent.com/assets/1529366/22789668/58f4fcd0-eea9-11e6-873b-65f8a32f689e.png)

In my mock-ups I changed the location of these indicators and made the icons more distinct from each other (right now they're so similar that I don't think they're providing a good visual cue of a distinction).

If something about the treatment in this mock-up isn't possible or won't work and needs adjusting, definitely let me know and I can revise it.

**Comment by jonpmarino** [comment]
looks good to me @glynnis
