### ISSUE TITLE
Enable data layer features to show get-feature-info (InfoBoxes) when viewer clicks on them in a published layer.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#424]
Pullover from Github #1470. Right now Infoboxes can be customized in composer using the Masking function, but there is no way to see them on a published layer or story.

Desired behavior is that on the detail page for a layer, the viewer of a layer could pause playback, click on a feature, and see the get-feature-info (infobox) on the feature, just as they can when in edit mode. 

This is straightforward for layer playback view.

Here's an example of a map using another map service that lets you click on the features of the layer and see the get-feature-info, http://www.telegraph.co.uk/travel/maps-and-graphics/Mapped-The-worlds-largest-rail-networks/

Another example: http://www.azcentral.com/story/news/politics/elections/2016/03/27/slim-polling-options-maricopa-county/82278474/

For stories this is a bit more complex, because we need to decide how we will manage the situation where a story has multiple layers, and thus overlapping features. For 0.1.0 a win would be just completing the work to enable the feature info for layers. Stories likely needs to be ticketed as part of the future design work being done by Glynnis, unless a quick solution is clear and folks want to move on it.

**Comment by jonpmarino** [comment]
Related to #540

**Comment by trepagnier** [comment]
https://github.com/MapStory/mapstory/pull/563 & https://github.com/MapStory/story-tools/pull/258 resolve this ticket

**Comment by jonpmarino** [comment]
closing. in prod.
