### ISSUE TITLE
Investigate solution to X on storypin pop-up behavior

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#434]
Current situation:

When a StoryPin is set to "show content automatically", it is expected that at the storypin's "start date" it will popup the storypin content automatically and remain until the "end date" is reached". (Current related issue #435 is blocking this, but that is a separate issue).

Currently, when the pop-up appears there is an X button that implies to a viewer that they can minimize the pop-up information. However, the current behavior is that if the storypin is set to "show content automatically", when the viewer hits the X, the storypin pop-up content will minimize for a moment and then re-appear.

This is frustrating to a user who thinks they have minimized the storypin pop-up.

An X button appears on a storypin pop-up.

This is a spike that needs research and design. There maybe a short-term solution to address the immediate user pain-point and then a longer term design consistent with "playback modes" that are envisioned for the composer/viewer redesign.

Short-term options could be:

- [ ] remove the X altogether so the viewer doesn't have the "option" to minimize a storypin pop-up
- [ ] Write the storypin behavior so that if a viewer hits X, the storypin pop-up stays minimized even if set to "show content automatically".

**Comment by trepagnier** [comment]
I hid the X for now and tacked the commit on to this PR: https://github.com/MapStory/mapstory/pull/456
