### ISSUE TITLE
Storypin pop-up remains visible across multiple chapters

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#435]
cross checked with Darin and Rey on Feb 6.

Desired behavior:
A user should be able to set a storypin start and end time in composer. The desired behavior is that the pin shows up at start time and disappears at end time.

Current problem:

The actual "pin" aspect of the StoryPin is respecting the start and end time, but the pop-up does not (when set to "show content automatically). It remains visible after the end time has passed, and even remains going into the next chapter if the story has multiple chapters.

In this screenshot (showing https://mapstory.org/story/23751) a StoryPin with start time 859 and ending in 1190 is there.  Content starts showing automatically at 859 and remains. At 1190 the dot for the pin disappears as expected, but the pop up remains. 

![screen shot 2017-02-06 at 12 16 27 pm](https://cloud.githubusercontent.com/assets/2573761/22660427/1bfd3fa2-ec67-11e6-86ca-3b44bddc63f3.jpg)

And it remains even if the story is advanced to Chapter 2.

![screen shot 2017-02-06 at 12 35 03 pm](https://cloud.githubusercontent.com/assets/2573761/22660868/b8814d9a-ec68-11e6-9883-fe9b3aebc301.jpg)

Example uses Chrome Version 55.0.2883.95 (64-bit).

**Comment by trepagnier** [comment]
Merged here:
https://github.com/MapStory/mapstory/pull/456
https://github.com/MapStory/story-tools/pull/255

**Comment by jonpmarino** [comment]
re-opening. Pins still show up in the wrong chapters.

**Comment by Coop56** [comment]
This was resolved in a previous sprint.
