### ISSUE TITLE
When selecting "change published story", layers are removed in composer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#436]
**Current state/problem:**

Once a storyteller has published their mapstory, we provide an option for the storyteller to "change  published story". Clicking "change published story" leads the storyteller back into composer. 

It appears that all elements of the story are there in composer (chapters, chapter info, storypins), but the _storylayers_ used are erased, forcing the storytelling to add their layers again.

**Desired state:**

When a storyteller clicks "change published story" and is taken back into composer, all the elements of their story should appear in composer, and nothing should be erased or removed.

**Example:**

https://mapstory.org/story/23751 has 2 chapters,  2 layers and 1 storypin in chapter 1 (OldestUniversitiesAfrica and OldestUniversitiesFinal). 

![screen shot 2017-02-06 at 12 54 52 pm](https://cloud.githubusercontent.com/assets/2573761/22661609/9332464a-ec6b-11e6-9e3d-4359e8c94870.jpg)

Clicking "change published story" takes user back into composer where the storypin is still visible in chapter 1, but both layers are gone.

![screen shot 2017-02-06 at 12 59 21 pm](https://cloud.githubusercontent.com/assets/2573761/22661736/1c937f94-ec6c-11e6-923a-6217720fbc51.jpg)

Verified with @reynalddizon and @darinacosta on Feb 6.

**Comment by Coop56** [comment]
Closing this as it is not reproducible.
