### ISSUE TITLE
Chapter breadcrumbs showing up in layer edit view

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#444]
(2nd opinion confirmation with @reynalddizon on Feb 8)

Issue Summary:

When a user wants to make edits to a StoryLayer, he/she clicks "edit features" on the layer's detail page, and is taken to the edit mode for the layer. In this mode, the user should only have access to functions for making edits to the layer.

However, currently there are "breadcrumbs" in the View History tab that, if clicked, will accidentally bring a user into story composer mode, which they shouldn't be able to access from the edit-only mode. Those breadcrumbs should be removed from the View History tab of the edit-only mode.

![breadcrumbs](https://cloud.githubusercontent.com/assets/2573761/22745057/e318545e-ede4-11e6-8f76-54b248ddbf36.jpg)

Steps to reproduce:

1. From search, click on any StoryLayer
2. From the Storylayer's detail page, click "Edit Features"
3. Once features have loaded, click the "View History" tab.
4. Notice the breadcrumbs for "chapters". (see screenshot above). If these breadcrumbs are clicked they take you to composer view, which you should not be able to do when editing a layer.

**Comment by emilyashley** [comment]
This should have been resolved with https://github.com/MapStory/MapLoom/commit/71b52ea2942ec5a476fe16e8798b0f86b0980a3a ? 

I had trouble verifying it in a local environment because of our maploom django wrapper setup tho.

**Comment by Coop56** [comment]
@emilyashley It was resolved with that commit.  @jonpmarino It's likely that it just hasn't made it up to production yet.

**Comment by jonpmarino** [comment]
breadcrumbs are visible in "edit history" part of layer editing in demo.
