### ISSUE TITLE
Missing geospatial data features on composer

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory#445]
Username: rei41590 (non-admin)
Browser: Version 55.0.2883.95 (64-bit)
Date occurred: Feb 8, 2017

1. I successfully uploaded a storylayer (https://mapstory.org/layers/geonode:superbowl_teams0) and it's displayed correctly on the viewer page. Below is a screen cap of the first timeslice of the storylayer. Kansas City vs Green Bay.
<img width="1280" alt="screen shot 2017-02-08 at 4 04 09 pm" src="https://cloud.githubusercontent.com/assets/4611843/22745577/fcc50620-ee18-11e6-9f9b-600446e4f80c.png">

2. I composed a mapstory using the storylayer and it loaded without encountering any errors. Screencap is the first time slice of the Super Bowl storylayer.
<img width="1280" alt="screen shot 2017-02-08 at 3 58 16 pm" src="https://cloud.githubusercontent.com/assets/4611843/22745645/3273b2e4-ee19-11e6-971a-078c0167b927.png">

3. I tried to style it so i clicked Style Layer and when the styling interface loaded, the Kansas City point disappeared.
<img width="1280" alt="screen shot 2017-02-08 at 3 58 23 pm" src="https://cloud.githubusercontent.com/assets/4611843/22745772/9b37eab6-ee19-11e6-8ee7-2ed1c921ff78.png">

**Comment by jonpmarino** [comment]
coop, just something to keep in the back of your mind and look out for in conjunction with importer work.
