### ISSUE TITLE
Detail page attributing all edits to layer owner, regardless of user that makes the edits

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#446]
(Confirmed with @reynalddizon on Feb 8. Using Safari 10.0.2 and Chrome Version 55.0.2883.95)

Issue:

If a layer is open to community editing, any registered user can go to the layer's detail page and click "edit features" and begin adding, modifying or deleting features from the layer.

Currently if multiple different users make edits to a layer, all of those actions appear to be attributed to the owner of the layer in the "Contributions" tab on the detail page.

Example:

In https://mapstory.org/layers/geonode:prisons_yinsaxp, the user ninasimone imported this layer. 2 different users have since contributed edits: EllaFitzgerald and ninasimone. This is reflected in the edit history of the layer that appears in edit mode:

![screen shot 2017-02-07 at 9 27 01 pm](https://cloud.githubusercontent.com/assets/2573761/22746725/704a3338-edea-11e6-856f-258ff2fc7041.jpg)

However, on the detail page itself, all 10 edits are attributed to ninasimone:

![contributions](https://cloud.githubusercontent.com/assets/2573761/22746223/b6afb458-ede8-11e6-9dab-b733963e57d8.jpg)

Steps to reproduce:

1. Go to search
2. Click on any layer...make sure it is one that has the "edit features" option enabled
3. Click "edit features".
4. Add a feature to the layer and make sure it is recorded in the edit history
5. Exit the editor and return to the detail page
6. Look at the "Contributions" tab and check to see what username is represented for the edit you made.

**Comment by emilyashley** [comment]
Html [here](https://github.com/MapStory/mapstory/blob/master/mapstory/templates/layers/_geogig_layer_detail.html#L30) and js controller [here](https://github.com/MapStory/geonode/blob/c454a46fb174e0bd7bf3577461dfe143575ab6a3/geonode/contrib/geogig/static/geogig/geogig.js#L59)

**Comment by glynnis** [comment]
Related to #447
