### ISSUE TITLE
Story layer admin panel error

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#470]
Hit an error attempting to view a story layer in the Django admin panel.

![image](https://cloud.githubusercontent.com/assets/1152120/22999060/722e941a-f38e-11e6-8ddf-b804362c328d.png)

![image](https://cloud.githubusercontent.com/assets/1152120/22999105/99992c9a-f38e-11e6-8f39-09d217021755.png)

**Comment by Coop56** [comment]
This was already ticketed here - https://github.com/MapStory/mapstory/issues/437 and has since been resolved but hasn't been pushed to production yet.

**Comment by cuttlefish** [comment]
It seems to have been resolved a few days ago, so it may not have made it into my test system.
I'll give that a run through tomorrow.
