### ISSUE TITLE
change homepage tagline from "atlas of change that anyone can edit" to "atlas of change that everyone can edit".

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#491]
we actually have the latter one protected as official.

This seems to be hardcoded on the mapstory.org theme. Changing with the custom site properties in django adds more text but doesn't replace this existing text.

Ideal solution would be to have no hardcoded text so we can use the custom site properties in django to customize and change when we want as admins.

**Comment by emilyashley** [comment]
Closing with #503 to remove hardcoded html and rely solely on custom site properties. 

Worth mentioning that I had to restart gunicorn for changes to the django site properties to consistently persist upon refreshing the page and something similar may need to be done if tagline is updated from the admin panel on demo & production.
