### ISSUE TITLE
Increase upper limit of class IDs in unique, choropleth and graduated styling

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#496]
As a user, I want to be able to style a layer in my story with unique classifications for over 20 different classes, but currently I am limited to nine.

**Acceptance Criteria**

Our current styling palette sets an upper limit of 9 classification IDs for unique, choropleth and graduated styling. This will limit the storytelling in many cases. For example, if a storyteller is telling a story about a Presidential primary and wants to set a unique color for the campaign stops of 12 different presidential candidates, they will be unable to do so.

Increase this limit to 99 for now and lets see if we get any requests for a higher limit, or if that causes problems.
![screen shot 2017-03-01 at 5 33 46 pm](https://cloud.githubusercontent.com/assets/2573761/23486547/662b4afa-fea6-11e6-94a3-f11e1d62c1bf.jpg)

**Comment by trepagnier** [comment]
Resolved by https://github.com/MapStory/story-tools/pull/271

**Comment by jonpmarino** [comment]
closing issue. this is live on beta.
