### ISSUE TITLE
Layer View's contribution tab is displaying JSON

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#500]
![image](https://cloud.githubusercontent.com/assets/1152120/23490133/5adb3b38-feab-11e6-9403-92758ce5a34e.png)

**Comment by cuttlefish** [comment]
Fixed by 3d19c747c46265ed702c5ec5709ff411fc42d16c

**Comment by Coop56** [comment]
Weird I could've sworn I already sent in a fix for this.  Thanks for getting it fixed @emilyashley and @cuttlefish.

**Comment by cuttlefish** [comment]
Yeah, now that you mention it I thought this got fixed about a month ago. It must have gotten mangled in a merge or something.
