### ISSUE TITLE
editing doesn't work

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#501]
I've been unable to test this in production. I just get timeouts.

In demo and local it throws an error when a user tries to edit another user's layer.

![image](https://cloud.githubusercontent.com/assets/1152120/23490320/c613c4c8-feac-11e6-963d-ce6a88dce3b6.png)

**Comment by cuttlefish** [comment]
This applies to both imported and created layers.

**Comment by jonpmarino** [comment]
this is a layer on production that has edits from 3 different users: Rey Dizon, Nina Simone and John Glenn. It is a new layer...not legacy: https://mapstory.org/layers/geonode:national_parks_of_the_philippines

**Comment by jonpmarino** [comment]
i've been able to add/edit features on this layer from multiple accounts, https://mapstory.org/layers/geonode:prisons_myneekx

**Comment by jonpmarino** [comment]
re-opening based on failures to edit other people's layers on demo after update on March 21

**Comment by cuttlefish** [comment]
https://mapstory.org/layers/geonode:prisons_myneekx on production does seem to work.
Perhaps the geonode auth isn't configured correctly on demo?

**Comment by jonpmarino** [comment]
perhaps

**Comment by Coop56** [comment]
Locally editing works without a problem, which seems to suggest it's not a code issue.  I am able to go to my own layer, or other peoples layers that are open for editing, and add or edit features and save the geometry.  @jonpmarino @cuttlefish

**Comment by Coop56** [comment]
This has been confirmed as working on demo now.

**Comment by jonpmarino** [comment]
confirmed editing working on prod.
![screen shot 2017-04-04 at 7 27 55 am](https://cloud.githubusercontent.com/assets/2573761/24656462/4c538c42-1908-11e7-8cdf-0d9936726d0c.jpg)
