### ISSUE TITLE
Incorrect link in Story Viewer

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#502]
When viewing a story, the link to the user's profile is broken. It goes to `/storyteller/` rather than `/storyteller/{username}` and throws a 404.

![image](https://cloud.githubusercontent.com/assets/1152120/23490355/13c9c1cc-fead-11e6-90cf-25476d68bab7.png)

**Comment by jonpmarino** [comment]
this is now correct on prod.
