### ISSUE TITLE
mini-explore modal in composer often does not scroll (demo.mapstory.org)

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#506]
Steps to reproduce:

1. go to demo.mapstory.org and login
2. start Compose mapstory
3. Add StoryLayer to chapter

issue encountered on clean build of demo at 8am on march 2 using Chrome Version 56.0.2924.87 (64-bit). Initially we thought this was a load-time issue on prod, but appears to be happening on a clean build of demo that has very little data.

![screen shot 2017-03-02 at 7 58 07 am](https://cloud.githubusercontent.com/assets/2573761/23510236/529f4eaa-ff1e-11e6-8ba8-0b5a4ca8f192.jpg)

**Comment by Coop56** [comment]
I was unable to reproduce this on local, demo, or production.  I tried it on Chrome, Firefox, and Safari.  Then I moved over to my Windows machine and tried it on Chrome, Firefox and Edge.  I have scroll bars every time without a problem.

**Comment by jonpmarino** [comment]
Ok, @Coop56 we had it reproduced by several folks but this is is great news. Lets leave it for the RFT to see if it pops up in that testing process. I'll move this back to Backlog.

**Comment by jonpmarino** [comment]
this was not observed at all in RFT testing. I'm leaving open in the backlog in case it rears its head but definitely taking out of 0.1.0
