### ISSUE TITLE
Favorites appear to be removable from other user's profiles

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#511]
<img width="1284" alt="screen shot 2017-03-02 at 11 39 58 am" src="https://cloud.githubusercontent.com/assets/15912063/23519672/5ecce434-ff3d-11e6-9483-ea3fd98ccba8.png">
<img width="1252" alt="screen shot 2017-03-02 at 11 42 08 am" src="https://cloud.githubusercontent.com/assets/15912063/23519674/6071336c-ff3d-11e6-98e8-f8f34fe5829c.png">

**Comment by cuttlefish** [comment]
Reproduced in production.

**Comment by Coop56** [comment]
Resolved in https://github.com/MapStory/mapstory/pull/566
