### ISSUE TITLE
Permissions Reference

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#513]
This issue describes the desired user outcomes from a permissions standpoint. It can stand as a reference point to check back on at any point. It can be updated as new functionality comes online and new permissions questions emerge.

Action | Any Visitor | Logged in User | Admin
------------ | ------------- | ------------ | ------------
Search for published layers and stories | X 
Play published layers and stories | X
Embed a published story on another website | X
Search for and view profiles of registered users | X
See _all_ layers and stories (published and unpublished) | | | X
Import Data | | X
Compose and publish MapStory | | X
Download Data | | X
Edit their own StoryLayer | | X
Edit another StoryLayer (collaborative editing) | | X
Revert an edit made on a StoryLayer | | X
Turn off collaborative editing on a StoryLayer | | | X
Favorite, Flag and Rate StoryLayers | | X
Receive Flags | | | X
Comment on StoryLayers and MapStories | | X
Send messages to users | | X
Feature stories on Home | | | X
Upload a custom thumbnail to Layers or Stories I own | | X
Upload a custom thumbnail to any Layer or Story | | | X
Change published settings on a layer or story I own | | X
Change published settings on _any_ layer or story | | | X
Author Journal articles | | X
Delete Journal articles I wrote | | X
Delete Journal articles anyone wrote | | | X
Update custom site content (i.e. footer, parallax, headline, Get Started items) | | | X

**Comment by Coop56** [comment]
Closing this as there's no task involved, and this closed issue will remain archived for knowledge purposes.
