### ISSUE TITLE
If the window is too small buttons are hidden in the Story viewer

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#514]
Slightly too small
![image](https://cloud.githubusercontent.com/assets/1152120/23570509/52a93220-0019-11e7-8b1f-1c09299e93a6.png)

Big enough
![image](https://cloud.githubusercontent.com/assets/1152120/23570528/6484967e-0019-11e7-94e3-d63a8c924bd1.png)

**Comment by glynnis** [comment]
There are some additional bugs I've discovered in the nav as I've been working with the code to put together a fix for this that, as long as there's no objection, I'll bundle into this effort.

Specifically, at the smallest size there are scroll bars that appear for the navigation menu, which would be an especially maddening experience on a touch device.
![screen shot 2017-03-07 at 11 44 13 am](https://cloud.githubusercontent.com/assets/1529366/23669913/8a22a6cc-032b-11e7-849b-d5766947a731.png)

Looking at the CSS for this, which has a lot of negative margins, `!important` tags and other code smells, I'll probably be doing a rewrite to clean up the code and squash these bugs.

**Comment by glynnis** [comment]
PR here: https://github.com/MapStory/mapstory/pull/533
