### ISSUE TITLE
Create StoryLayer fails on production

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#515]
![image](https://cloud.githubusercontent.com/assets/1152120/23590561/1b349dbe-0197-11e7-8ecc-6952030b02f7.png)

Attempted with `admin` and a couple of normal accounts.
Works as expected on `demo`.

**Comment by cuttlefish** [comment]
The layers seem to be created correctly in GeoServer.

**Comment by cuttlefish** [comment]
It's timing out PUTing to geoserver for some reason.
```
ERROR 2017-03-05 20:35:56,421 importers 2500 139781816248128 504
ERROR 2017-03-05 20:35:56,422 importers 2500 139781816248128 Gateway Time-out
ERROR 2017-03-05 20:35:56,422 importers 2500 139781816248128 https://mapstory.org/geoserver/rest/workspaces/geonode/datastores/hiro-layers/featuretypes.json
ERROR 2017-03-05 20:35:56,422 importers 2500 139781816248128 {'Date': 'Mon, 06 Mar 2017 02:35:56 GMT', 'Content-Length': '176', 'Content-Type': 'text/html', 'Connection': 'keep-alive', 'Server': 'nginx'}
ERROR 2017-03-05 20:35:56,422 importers 2500 139781816248128 <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by jonpmarino** [comment]
note #366 and #504 as potentially related?

**Comment by jonpmarino** [comment]
is it because you said no to version editable?

**Comment by jonpmarino** [comment]
looks like the new deploy to prod complete on April 4 fixed this. Was able to create a new layer with a new account (ulyssesgrant) that hadn't uploaded any data yet. worked well. https://mapstory.org/layers/geonode:create_before_upload_grant
