### ISSUE TITLE
Geoserver re-installs by itself and loses configuration

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#518]
Geoserver loses configuration on deployments (reported that it re-extracts war file) - cure is run ansible geoservers.yml then reboot...

**Comment by cuttlefish** [comment]
I haven't figured out _why_ it's re-extracting the war file. No one has noticed a pattern to when it decides to do so.

We're currently working on revamping how we do the deployments, so this should become irrelevant.
