### ISSUE TITLE
Decouple story thumbnails from geonode.geoserver.signals

### ISSUE THREAD

**Issue by sarasafavi** [MapStory/mapstory#521]
_Part of the greater effort towards bringing MapStory's GeoNode dependency up to par with upstream GeoNode (reference: #317)._

With the MapStory model & related logic migrated out of our GeoNode fork, we need to also completely decouple MapStory thumbnail creation from GeoNode itself.

**Comment by davisc** [comment]
@lhcramer see this PR as it may be helpful to Mapstory in resolving the thumbnail issue. 
https://github.com/boundlessgeo/exchange/pull/414
