### ISSUE TITLE
Deal with bouncing map views on published stories

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#524]
**User Story**

As a user, I do not want the map view to bounce around as the story plays. See example:  https://youtu.be/7EzWd1wGQ1Q. 

This story has a StoryPin located in Philadelphia. The way the detail page is configured, whenever a storypin pops up that exists outside of the viewing window, the map canvas moves to show the storypin pop up and continues to bounce back and forth. 

Also, if the viewer of the story zooms the map in or out and then hits play, the zoom level will revert back to the starting setting.

(another example, https://demo.mapstory.org/story/55)

From @davisc it appears this is happening because of the way Chapter View and StoryBoxes are configured. When a Chapter View and StoryBox is set, under the current configuration, the zoom level holds at that level no matter what. Thus, if the viewer of the story zooms in or out, and then hits play again, the zoom level will return to the pre-set setting. Also, if a storypin pop-up forces the map viewer to move, the map view will be forced back to the initial setting, causing the map to "bounce".

**Acceptance Criteria**

- playback settings (zoom levels, storyframes, etc) should be honored in a rational way for viewers viewing a story at either detail page, full screen or mobile scales. This probably means that the Chapter View and StoryBox should be interpreted as a _starting setting_. In other words, the Chapter view or StoryBox should _begin_ at the zoom level defined by the composer when the story was composed _until or unless_ a viewer of the published story changes the zoom level. If the browser is refreshed, or another user plays the story, it should always begin playing with the zoom levels set by the storyteller.

- If StoryPin pop-ups are larger, or extend off the map, when the mapstory is played from the detail page, the map canvas should not move around. The viewer of the story is free to zoom in/out in order to see the storypin pop-up and/or go to full screen mode.

**Comment by jonpmarino** [comment]
Related to #540

**Comment by trepagnier** [comment]
Resolved in https://github.com/MapStory/story-tools/pull/261/
