### ISSUE TITLE
Deploy social features on story detail pages

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#537]
As a user In expect to be able to perform the same social review functions on a story that I can on a layer. These include:

-commenting on story (threaded comments)
-rating a story on a 5-star scale
-flagging a story for administrator review
-favoriting a story to add to your profile

**Acceptance Criteria**
Implement the following on the story detail page:
- commenting on story (threaded comments)
- flagging story for administrator review
- favoriting story to add to your profile
- rating story on a 5-star scale

These are in order of priority if the preference is to do some but not all.

**Comment by josellausas** [comment]
See 
- [x] #1444 Commenting
- [x] #1445 Flagging
- [x] #1446 Favorite
- [ ] #1447 Rating
