### ISSUE TITLE
Deleting uploads doesn't update totals or remove from UI

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#553]
Very minor cosmetic issue. When you delete uploads, the number in the tab and the number on the page don't update.

![image](https://cloud.githubusercontent.com/assets/1152120/24070173/5d16ace4-0b75-11e7-8bc3-9d6efcab048d.png)

**Comment by emilyashley** [comment]
Note to self: tie this in to #752 work if it's still persists

**Comment by lhcramer** [comment]
Follow-up on this, Uploads don't remove themselves from list upon deletion (on Beta) 

See UserSnap #266:
On Beta --> Profile Page --> Upload tab, when you delete an upload, it doesnt remove itself (or ask for confirmation) unless you refresh the page.

**Comment by emilyashley** [comment]
roger that @lhcramer, I have that noted on my local as well.
