### ISSUE TITLE
Lack of paging on profiles prevents user from seeing more than 30 layers or stories

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#575]
If a user has more than 30 storylayers or mapstories, it appears that they cannot page forward to view beyond the first 30.

For example, see the Admin account on prod: https://mapstory.org/storyteller/admin/. It has 113 layers. Scrolling all the way down gets you to see the first 30, but there is no way to proceed to view the remainder of the 113.

**Comment by emilyashley** [comment]
(note to self from previous ticket on the issue)
todo: try separating Layer and MapStory tabs into their own controllers to isolate page and results counts. Use shared pagination methods & markup from the search/explore module example (or tap into how Uploads uses uib-pagination? and implement that sitewide)

check in to see if a quick fix is preferred or if this re-work should have a design story for the profile page in tandem

**Comment by jonpmarino** [comment]
closing, seems a duplicate of #624
