### ISSUE TITLE
Location option in mapstory properties modal shows no options

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#579]
![screen shot 2017-03-31 at 12 46 40 pm](https://cloud.githubusercontent.com/assets/2573761/24562364/2aab1c40-1610-11e7-861c-0c79610a0b52.jpg)

We should remove this option until we have fully integrated spatial and temporal search in a future release.

**Comment by emilyashley** [comment]
Of note: neither the Location nor the Tags fields are saved from this form. 
Also, if you have selected a category and reopen this form it does not show the saved category as  selected.

**Comment by jonpmarino** [comment]
So, in prod now (April 4, 10:30am) the location drop down seems to be there so i'm going to close this for now. We will have Emily's notes for future ref.
![screen shot 2017-04-04 at 9 27 37 am]

![screen shot 2017-04-04 at 9 28 12 am](https://cloud.githubusercontent.com/assets/2573761/24661830/12416734-1919-11e7-9d3c-079cde40f43d.jpg)
