### ISSUE TITLE
Gear is missing from the playback bar for StoryLayers and MapStories on demo

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#581]
On MapStory prod there is a "gear" icon in the player bar which lets the viewer control playback speed and playback setting.

On demo currently the gear icon is missing:

![screen shot 2017-03-31 at 12 58 01 pm](https://cloud.githubusercontent.com/assets/2573761/24562807/ba9487e6-1611-11e7-8b54-99234d23224d.jpg)

Here it is on prod:

![screen shot 2017-03-31 at 12 56 24 pm](https://cloud.githubusercontent.com/assets/2573761/24562785/a88bffc0-1611-11e7-9631-5ec6ebc2b9e1.jpg)

**Comment by trepagnier** [comment]
https://github.com/MapStory/story-tools/pull/262 resolves this issue

**Comment by jonpmarino** [comment]
(May 1) on demo, when the gear is clicked, the playback options appear transparent. This is using Chrome Version 57.0.2987.133 (64-bit) so could be different for different browser scenarios.
![screen shot 2017-05-01 at 9 36 26 am](https://cloud.githubusercontent.com/assets/2573761/25582287/036cf34c-2e52-11e7-9537-c3f29ee9a59b.jpg)

**Comment by trepagnier** [comment]
@jonpmarino this looks to be a result of the css that's set here: https://github.com/MapStory/mapstory/blob/master/mapstory/static/style/maps/viewer.less#L341

@glynnis, does jon's comment above warrant its own ticket; or should I simply set `color` in the viewer less file to black and submit a pull request?

**Comment by glynnis** [comment]
@darinacosta From searching the repo, it looks like the only place that style gets applied is in the scenarios above, so changing the color sounds fine if the intent is just to restore behavior.
