### ISSUE TITLE
Update text to modal that appears just before you publish a story is not correct

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#582]
Just before a user publishes a story, they see this warning message:

![screen shot 2017-03-31 at 1 00 28 pm](https://cloud.githubusercontent.com/assets/2573761/24562961/693a049c-1612-11e7-84ed-5485ffff3667.jpg)

Now that we have the ability to make changes to a published story and re-publish, this text is not correct.

For time being, change text to:

"Great work! Once you hit publish everyone will be able to search for your story. Don't worry, after you publish your story you can make changes to it anytime and publish an updated version. You can always delete it too."

**Comment by josellausas** [comment]
Created pull request on Maploom: https://github.com/MapStory/MapLoom/pull/31
