### ISSUE TITLE
Confirm supported thumbnail file types and add help text so that users use supported file types

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#583]
During user testing an RFT member tried to upload an SVG image as a thumbnail and got an error. We should confirm the file types we support (or at least the ones we know are solid for now) for these images first and second add a bit of text under "Change image" to say "MapStory supports X, Y, Z file types for thumbnails."

![screen shot 2017-03-31 at 1 10 36 pm](https://cloud.githubusercontent.com/assets/2573761/24563358/9faff814-1613-11e7-9a4b-3b5ee016aaac.jpg)

**Comment by josellausas** [comment]
Added the text:

<img width="878" alt="screen shot 2017-04-10 at 1 28 34 pm" src="https://cloud.githubusercontent.com/assets/4162671/24876686/3f35dea4-1df2-11e7-9258-f29b60c19e57.png">
