### ISSUE TITLE
map save 500 error when composing story

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#584]
Issue:

Several members of RFT encountered "map save 500" error when composing a story. The "map save 500" error message shows up in the composer session. When the story is published it appears like this...a strange basemap is there with no layers or timeline.

![screen shot 2017-04-05 at 9 54 59 am](https://cloud.githubusercontent.com/assets/2573761/24712880/b835c1b4-19e9-11e7-8f63-186fa1992755.jpg)

Also, a couple of times users have reported that a story has been successfully published, but then when it is returned to at a later date it will again look like this:

![Uploading Screen Shot 2017-04-05 at 9.54.59 AM.jpg…]()

For example @zrouse-Boundless reported this story looking good https://mapstory.org/story/24215 but at a later date it changed to look like the basemap w/ no timeline.

**Comment by jonpmarino** [comment]
More context... @reynalddizon published this story, PLPS - https://mapstory.org/story/24239. It suffered from the error mentioned above. He also published a different story, Cables - https://mapstory.org/story/24237. When he returned to the draft mode of PLPS to try to add a new style and recreate PLPS, it broke the cables layer in the CABLES story too.

**Comment by emilyashley** [comment]
Possibly related bug I'm noticing locally ---- if I log out my user and log back in my **imported** layers are not appearing on my search or my profile. Going directly to the layer url its still there. When I update metadata (like posting/removing a tag) the layer reappears on search and my profile. (of note: **created** layers work fine)

so maybe the mapstory config is have the same issue of not finding a layer once a user has logged out and back in.

**Comment by emilyashley** [comment]
Also of note: I don't see this story on @zrouse-Boundless's profile 
<img width="924" alt="screen shot 2017-04-05 at 2 26 23 pm" src="https://cloud.githubusercontent.com/assets/15912063/24723144/ed987e6a-1a0b-11e7-928e-c5622d7c3149.png">
