### ISSUE TITLE
In "Edit Profile" update help text for social media profile links

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#585]
In Edit Profile, social media links can be added by only putting in the username. For example, adding a link to a Twitter profile can be added by just inputting "mapstory" rather than the full https://twitter.com/mapstory.

In testing sessions, most users continue to add the full link, though. This can be mitigated by just adding clearer help text, i.e. 

"Enter your Twitter username. For example, if your Twitter username is mapstory, just put mapstory, and not the full link to Twitter.

"Enter your Facebook username. For example, if your Facebook username is mapstory, must put mapstory and not the full link to Facebook."

Enter your Github username. For example, if your Github username is mapstory, just put mapstory and not the full link to Github." 

![screen shot 2017-03-31 at 1 18 35 pm](https://cloud.githubusercontent.com/assets/2573761/24563914/be38005e-1615-11e7-8737-94bff61a9036.jpg)

**Comment by emilyashley** [comment]
Note: a lot of this lives in our geonode fork [here](https://github.com/MapStory/geonode/blob/master/geonode/people/models.py#L49). Check to see 1) if this is core geonode 2) if so, how to best customize this for the front end display on the edit profile form.

**Comment by Coop56** [comment]
@emilyashley VTC and all of the social media links are not core geonode.  We added all of that to our fork and it will be removed when @sarasafavi moves us back to core geonode so it's something that will need reimplemented.

**Comment by sarasafavi** [comment]
@Coop56 is correct; this has nothing to do with core geonode.

I've already implemented the mapstory-specific Profile properties in my [WIP branch](https://github.com/sarasafavi/mapstory/blob/WIP-geonode-fork-surgery/mapstory/mapstory_profile/models.py#L16-L68) for #317. 

@glynnis and/or @jonpmarino - if you can provide me with the desired help text updates for all relevant fields, I'll update the WIP implementation to reflect (and this story can be rolled into #317's work).

**Comment by glynnis** [comment]
@sarasafavi Just reassigned this to you.

Here's what I think we should use for each label, placeholder text, and descriptive text below the field, respectively:

Twitter Username
[_______________________]
Provide your Twitter username, e.g. 'mapstory'.

Facebook Username
[_______________________]
Provide your Facebook username. From your profile page, this is what comes after 'facebook.com/' in the URL.

LinkedIn Username
[_______________________]
Provide your LinkedIn username. From your profile page, this is what comes after 'linkedin.com/in/' in the URL.

Github Username
[_______________________]
Provide your Github username, e.g. 'mapstory'.


Let me know if you have questions.

**Comment by sarasafavi** [comment]
Thanks @glynnis -- help text has been updated in the WIP branch (see: https://github.com/sarasafavi/mapstory/blob/WIP-geonode-fork-surgery/mapstory/mapstory_profile/models.py#L21-L46).

Since this is attached to #317 I'll leave it in "Needs Review" for the time being.

**Comment by jonpmarino** [comment]
this is complete on beta so closing.
