### ISSUE TITLE
In composer, storypin pop-up remains on map when transitioning between chapters

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#588]
In a composer session, If I create a storypin in Chapter 1, and then transition to another chapter _when the storypin pop up from the previous chapter is still popped-up_ the storypin will be visible in the next chapter I click to.

For example, in the image below, 2 storypins were created in Chapter 1. While the second StoryPin was popped up I clicked to create another chapter, Chapter 2. The storypin pop-up was visible from Chapter 2 even though the actual pin feature does not exist in Chapter 2.

![screen shot 2017-03-31 at 3 34 11 pm](https://cloud.githubusercontent.com/assets/2573761/24568625/45b28f60-1628-11e7-8073-dae78b94585d.jpg)

to reproduce:

-start composing a new mapstory
-add a storylayer to chapter 1
-make a storypin and save
-while the storypin pop-up is visible, transition to a new chapter.

Bug logged on demo.mapstory.org using Chrome and user account alanshepard on March 31 at 4:45pm EST

**Comment by jonpmarino** [comment]
this seems to be an issue with new composer too. On staging, I have 2 pins in Ch. 1. Here i'm in ch 2 and the ch 1 pins appear:
![screen shot 2018-03-30 at 2 06 02 pm](https://user-images.githubusercontent.com/2573761/38157399-31384b72-344c-11e8-9045-fb1874aa38d0.jpg)

**Comment by goudine** [comment]
Cannot verify. See [issue](https://github.com/MapStory/story-tools-composer/issues/121) for more details
