### ISSUE TITLE
Improve usability and design of the homepage

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#592]
Our current homepage could do a better job of helping users understand MapStory and propose more specific calls to action.

Some things to consider and incorporate into a new design:
* Explanation of the primary activities a user can engage in on MapStory, and the value proposition
* More approachable copy that's easy to understand, even for users who aren't GIS experts
* Fewer and more targeted calls to action that are easier to understand for new users
* Better defined sections and messaging that flow down the page and lead naturally to calls to action
* Better showcase of featured content

Some notes on the current homepage:
![screencapture-mapstory-org-1491331466134](https://cloud.githubusercontent.com/assets/1529366/24673348/9552e4d0-193d-11e7-8313-d99e44c5cceb.png)

**Comment by glynnis** [comment]
Draft from 4/6:
![04-06-draftartboard 1](https://cloud.githubusercontent.com/assets/1529366/24922126/cc2e8f5c-1eb2-11e7-9680-620d7aafdedb.png)

Updating to record progress and moving back to the backlog, since we're tabling this until after ATO.

**Comment by jonpmarino** [comment]
Created #622 and #621 as quick fixes to current home based on @ChristopherTucker feedback until we get go-ahead to initiate bigger homepage facelift.

**Comment by jonpmarino** [comment]
quick amendment prior to any discussion on this @glynnis. Need to amend subheader text to ensure we use protected phrase "atlas of change that everyone can edit". replace "MapStory is an open atlas..." with: "MapStory is the atlas of change that everyone can edit. Working together, we're mapping the world as it evolves geographically, over time.""

**Comment by glynnis** [comment]
With updated copy:
![04-06-draftartboard 1](https://cloud.githubusercontent.com/assets/1529366/24930196/45d7bda4-1ece-11e7-98eb-d0a538ab077d.png)

**Comment by glynnis** [comment]
This issue was replaced by #720, which has the most current revisions. Closing.
