### ISSUE TITLE
Unicode issues when using Twitter white listed embed

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#595]
Issue identified by RFT on April 4 using Firefox browser.

Using a link to a tweet in a storypin revealed that we have unicode issues. French accents in the storypin in this story - https://mapstory.org/story/24210 - added incorrect special characters.

![screen shot 2017-04-05 at 12 04 21 pm](https://cloud.githubusercontent.com/assets/2573761/24717427/0ce2f3cc-19f8-11e7-88de-46a89dc77cb2.jpg)

To reproduce:

1. Start a new mapstory in composer
2. Create a storypin and paste a tweet with French language text in the media area.
3. Save and publish your story

**Comment by trepagnier** [comment]
Encoding issue resolved here:
https://github.com/MapStory/mapstory/pull/763

Note to self: create ticket for porting pin functionality from MapLoom.
