### ISSUE TITLE
Append schema download is cutting off columns

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#602]
To append features to a layer, the user downloads a blank schema, pastes their features to it, and goes through the append modal workflow.

In this example, the original schema has more than 10 columns and the columns are cut off. 

![screen shot 2017-04-05 at 1 13 28 pm](https://cloud.githubusercontent.com/assets/2573761/24720138/b96aa60e-1a01-11e7-91e7-ed61500bf7f1.jpg)

For example, this dataset goes to column AS. 

![screen shot 2017-04-05 at 1 03 22 pm](https://cloud.githubusercontent.com/assets/2573761/24719991/516a21e2-1a01-11e7-8c10-f3bc2180c2b7.jpg)

Downloading the dataset downloads the full data fine.

also, in edit mode, the table view shows all the columns (EV CONNECTOR TYPES is one of the very last rows in the original dataset)

![screen shot 2017-04-05 at 1 09 22 pm](https://cloud.githubusercontent.com/assets/2573761/24719978/46c4c274-1a01-11e7-8701-5dcab3f3cbf7.jpg)

**Comment by jonpmarino** [comment]
example, https://mapstory.org/layers/geonode:charging_stations_with_dates_jcbxxuv

**Comment by Coop56** [comment]
Permissions issues locally are breaking append functionality, so this bug cannot be worked until those are resolved.

**Comment by davisc** [comment]
This issue is not dependent on MapLoom, however, from what I see, we should consider stating maxFeatures=1 so that the call is not as expensive. Clicking the button a few times seems to have crash the instance.

https://github.com/MapStory/mapstory/blob/master/mapstory/views.py#L690

**Comment by Coop56** [comment]
@davisc Can do.

**Comment by emilyashley** [comment]
closed with #1033
