### ISSUE TITLE
Add basemap picker to edit mode

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#603]
Several RFT members requested the ability to toggle to different basemaps while they were in edit-mode editing a layer to help with their editing. For example, if you're editing natural features a Natural Earth basemap might better. Or, if you're editing building features an OSM basemap might be better.

**Comment by emilyashley** [comment]
Yes! This sounds like a good candidate to include in our StoryTools Layer Editor requirements.

**Comment by jonpmarino** [comment]
Closing. Added as an item in roadmap for when we go from roadmap>requirements>scoping after ATO.

**Comment by emilyashley** [comment]
Oh hey look, https://github.com/MapStory/mapstory/issues/1141  closed this with https://github.com/MapStory/MapLoom/commit/85291c0aa7c8eca6439a788f917c55d25e38d2f6, too.
