### ISSUE TITLE
Clicking "zoom to feature" in the "view history" tab causes an error

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#604]
The very first entry in the View History tab for a layer reflects the original import. 

If the user clicks "zoom to feature" on this first entry, it tries to zoom to all the original import features and throws this error:

![screen shot 2017-04-05 at 1 20 08 pm](https://cloud.githubusercontent.com/assets/2573761/24720403/ae32af38-1a02-11e7-8012-817a8dbfc68a.jpg)

![screen shot 2017-04-05 at 1 20 22 pm](https://cloud.githubusercontent.com/assets/2573761/24720418/b85f6c12-1a02-11e7-903c-e5a713d21cb7.jpg)

(testing done with Chrome on April 4. Confirmed by multiple users

Also, Zoom to commit stops transforming coordinates after first click.

**Comment by emilyashley** [comment]
tagging https://github.com/MapStory/mapstory/issues/1071

**Comment by emilyashley** [comment]
follow up question to test: is this happening for both imported and created layers' initial commits?

**Comment by emilyashley** [comment]
Closing this, it'll be available once we do a django-maploom is build, but https://github.com/MapStory/mapstory/issues/1148 arose from clearing out the other errors.

**Comment by Coop56** [comment]
This seems to be resolved.  I did a bunch of testing on it, and clicking the zoom to feature button sends you to the initial extent of the layer with no error.  That seems like desired behavior to me.  Sending this to merged column, @jonpmarino @lhcramer let me know if you see differently.

**Comment by jonpmarino** [comment]
based on testing of staging.mapstory.org on Jan 21, this issues seems to have solved itself. Agree with @Coop56
