### ISSUE TITLE
Loop chapter and Loop story don't work

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#614]
**Expected Behavior**

The MapStory viewer has an option to "loop chapter" or "loop story". The expected behavior for Loop Chapter is that when a chapter playback reaches the end, the playback will automatically return to the beginning of that chapter and begin again, without the viewer having to click.

The expected behavior of Loop Story is that at the end of the chapter's playback, the story will automatically transition to the next chapter (or if its the last chapter, to the beginning of the first chapter) without the viewer having to click.

**Experienced Behavior **

Based on testing on April 10 using Chrome on mapstory.org, account johnglenn, it doesn't appear that either Loop Chapter or Loop Story are taking the expected action when the botton is clicked.

Example stories to reproduce: 

https://mapstory.org/story/24344

https://mapstory.org/story/24354

![screen shot 2017-04-10 at 10 56 07 am](https://cloud.githubusercontent.com/assets/2573761/24870582/67f461aa-1ddc-11e7-9677-a8adaec1fd03.jpg)

**Comment by trepagnier** [comment]
Not going to move this over til demo is up to date with the latest, but it seems that https://github.com/MapStory/mapstory/issues/626 has resolved this on my local.

**Comment by jonpmarino** [comment]
tested on beta with https://beta.mapstory.org/story/139/ and it looks like loop chapter and loop story are both working. Closing this issue for now.
