### ISSUE TITLE
When transitioning to another chapter when playback is at the end, the new chapter also starts at the end

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#615]
**Expected Behavior**

In a multi-chapter story, the expected behavior is that if a viewer transitions to a "next chapter" or "previous chapter" the timeline should always begin at the start of the chapter by default.

**Experienced Behavior**

Based on testing on mapstory.org on April 10 using Chrome, account johnglenn, it seems like if viewer play a chapter through and then transitions to "next chapter" or "previous chapter", the timeline stays at the end rather than returning to the beginning of the new chapter.

To reproduce (using example: https://mapstory.org/story/24354):

1. Play chapter 1 through to the end.
2. Click "next chapter".
3. Timeline is at the end rather than returning to the start of the new chapter.

perhaps this is relevant info for #614

**Comment by jonpmarino** [comment]
(said more simply, timeline is not resetting when going to next or previous chapter)

**Comment by trepagnier** [comment]
https://github.com/MapStory/story-tools/pull/270 resolves this issue
