### ISSUE TITLE
Map viewer and timeline bar are not showing full extent of data on published stories

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#626]
(based on reports from Rapidfeedback team using production mapstory.org on April 11 using Chrome 57 on a Windows machine)

Issue Summary:

When publishing a mapstory, the timeline bar and the map canvas do not extend to show the full extent of the data. The expanded timeline, however, _does_ show all data. 

Note - the timeline bar and map canvas as set up on a published _layer_ do seem to show all data, as well as when data is played inside composer. It is only on a published story that this problem seems to occur.

Example:

In this screenshot, the data as shown in the expanded timeline extends past Jan 2016, but the time bar is stoppping playback at May 2014.

![screen shot 2017-04-11 at 10 13 06 am](https://cloud.githubusercontent.com/assets/2573761/24916379/92820120-1e9f-11e7-84b2-6b71febfffd3.jpg)

**Comment by jonpmarino** [comment]
Another data point for this issue...

In this story, https://mapstory.org/story/24426, the timebar seems to stops at June 1 2016 in the viewer, but there are several features that go past June 1, 2016. In the screenshot below of the story in draft mode, you can see a storypin and feature popping up at April 11, 2017.

![screen shot 2017-04-12 at 12 43 09 pm](https://cloud.githubusercontent.com/assets/2573761/24971455/b0f1a6f4-1f7d-11e7-9aa2-f506e0adf0d2.jpg)

**Comment by alant4ng** [comment]
Few more examples of this issue, mostly consisting of multiple layers for each story.

https://mapstory.org/story/24389
Consists of two layers, time slider stops at May 15, 2015 however the timeline below shows additional data not being played/mapped in the story. However all events show up when going into each individual layer and playing each one separately (isil events points and isil areas of control)
<img width="1122" alt="screen shot 2017-04-12 at 3 03 54 pm" src="https://cloud.githubusercontent.com/assets/5017592/24974809/837e38f4-1f91-11e7-8aa3-8071a004a470.png">

https://mapstory.org/story/24392
Consits of two layers (affiliated declared in country and global attacks). When story is played the time slider stops at May 26th, 2014, however there is clearly additional data in the timeline that is not being displayed.
<img width="1115" alt="screen shot 2017-04-12 at 3 06 22 pm" src="https://cloud.githubusercontent.com/assets/5017592/24975029/3d121560-1f92-11e7-8600-bc58a2d2cad0.png">

https://mapstory.org/story/24397
Consists of three layers, the time slider only goes to the first point then stops at Dec 31 1948, but there is additional data going through 2010 not being displayed in the story
<img width="1098" alt="screen shot 2017-04-12 at 2 58 31 pm" src="https://cloud.githubusercontent.com/assets/5017592/24974628/cda7443a-1f90-11e7-878f-a38eb19a54fe.png">

**Comment by trepagnier** [comment]
This issue no longer seems to be happening on demo, or on my local. Here's a map on demo that I used to test: https://demo.mapstory.org/story/247

**Comment by trepagnier** [comment]
I'll be out of the office for the next week and a half so I'm including some notes to refresh my memory on this issue when I return. The problem still exists for certain edge cases. 

For a sample case, include the following two layers in a single chapter, publish it, and visit the map viewer. The range should extend from 1946 to 2009, but instead extends from 1946 to 1998:

### Layers for testing
NATO:  https://demo.mapstory.org/layers/geonode:eeu1
-- TIME FIELD: JOIN_YEAR [1948-2009]
ussr_russ: https://demo.mapstory.org/layers/geonode:ussr0
-- TIME FIELD: COWSYEAR [1946-1991]

### Range construction
1. The range is assembled by this function:
https://github.com/MapStory/story-tools/blob/master/lib/ng/core/time/services.js#L16
2. The function is called here when assembling the time slider config:
https://github.com/MapStory/story-tools/blob/master/lib/ng/core/time/services.js#L112
3. And finally the config is passed to the create function:
https://github.com/MapStory/story-tools/blob/master/lib/core/time/controls.js#L313

**Comment by trepagnier** [comment]
https://github.com/MapStory/story-tools/pull/269 resolves this issue.

**Comment by jonpmarino** [comment]
marking this issue resolved for now per @darinacosta work. if users notice it again, we can revisit.
