### ISSUE TITLE
Update Story Routes

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#629]
Update `map/` to `story/` routes for composer and update Mapstory's `urls.py` file to reflect these changes

**Comment by trepagnier** [comment]
Resolved with: 
https://github.com/MapStory/mapstory/pull/630
https://github.com/MapStory/MapLoom/pull/35
https://github.com/MapStory/mapstory/pull/641

**Comment by jonpmarino** [comment]
confirmed on demo on May 1
