### ISSUE TITLE
Add migrations to icon-commons

### ISSUE THREAD

**Issue by sarasafavi** [MapStory/mapstory#633]
_Part of the greater effort towards bringing MapStory's GeoNode dependency up to par with upstream GeoNode (reference: #317)._

In Django 1.8+, Django apps without migrations cannot depend on apps _with_ migrations: https://github.com/MapStory/icon-commons depends on the AUTH_USER_MODEL (ref: https://github.com/MapStory/icon-commons/blob/master/icon_commons/models.py#L43) and likewise throws an error during initial migration.

*Acceptance Criteria*
* All MapStory tests passing
* MapStory behavior is functionally unchanged

**Comment by cuttlefish** [comment]
I'm getting an error deploying to the demo server.
`django.db.utils.ProgrammingError: relation "icon_commons_collection" already exists`

**Comment by sarasafavi** [comment]
@cuttlefish does the deploy to demo use the same ansible config as our dev server setup?

If so, try changing the command in [this line](https://github.com/MapStory/mapstory/blob/master/scripts/provision/roles/web/tasks/mapstory.yml#L141) to `command="migrate --fake-initial --noinput"` (i.e., adding `--fake-initial`).

I don't have a way to test this locally at the moment, or else I'd confirm & PR the fix into the playbook.
