### ISSUE TITLE
StoryPin titles don't appear on published stories

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#634]
(note for storytools refactor work)

Issue experienced on April 12 at 1:36 EST using Chrome v57 at mapstory.org

In composer, the StoryPin form asks the user to provide a title for each storypin. However, on a published story only the content, and not the title of the storypin appears.

From a design standpoint, it might be better to not have both a title and content but whatever direction is taken, what gets published and what gets entered in composer should match so the storyteller's expectations are meant.

Example:

In https://mapstory.org/story/24426 this storypin shows the content, including text and an image.

![screen shot 2017-04-12 at 12 33 02 pm](https://cloud.githubusercontent.com/assets/2573761/24971187/9f0f6288-1f7c-11e7-916c-6d1e4a13eae3.jpg)

In composer, this storypin has a title, "First MapStory Developer's Sprint" that doesn't appear on the published StoryPin (as seen above).

![screen shot 2017-04-12 at 12 33 23 pm](https://cloud.githubusercontent.com/assets/2573761/24971191/a4e72a88-1f7c-11e7-9ae6-85844ca02ce3.jpg)

**Comment by trepagnier** [comment]
Resolved by https://github.com/MapStory/mapstory/pull/744
