### ISSUE TITLE
Compose Story link on homepage is outdated

### ISSUE THREAD

**Issue by josellausas** [MapStory/mapstory#646]
The 'Compose Story' link on the homepage takes us to `/maps/new?tour` instead of `story/new?tour`

Screenshots:

This button: 

<img width="463" alt="screen shot 2017-04-18 at 1 16 52 pm" src="https://cloud.githubusercontent.com/assets/4162671/25146473/9687170c-2439-11e7-9786-b840893b2ce7.png">

Takes us here:

<img width="1108" alt="screen shot 2017-04-18 at 1 17 04 pm" src="https://cloud.githubusercontent.com/assets/4162671/25146483/a26fae12-2439-11e7-99e0-058eb1c5b7f4.png">

**Comment by trepagnier** [comment]
Resolved by https://github.com/MapStory/mapstory/pull/648
