### ISSUE TITLE
Automated tests fail to find angular on Travis

### ISSUE THREAD

**Issue by josellausas** [MapStory/mapstory#656]
Automated tests from #487 are failing to find angular when running on travis with the new Docker setup. The automated tests have been commented out for now in order to merge unit tests.

This is the Travis log for the error: [Error log](https://travis-ci.org/MapStory/mapstory/builds/225669142)

The error seems to happen because `https://nginx` does not load the page content properly.

<img width="970" alt="screen shot 2017-04-25 at 12 04 45 pm" src="https://cloud.githubusercontent.com/assets/4162671/25397878/7e3440fa-29af-11e7-80c5-28726238c6a0.png">

**Comment by cuttlefish** [comment]
Sorry I didn't get back to you sooner on this. It's not a problem anymore, is it?
