### ISSUE TITLE
Explore: Volunteer Technical Community filter doesn't persist on refresh or link share

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#665]
<img width="743" alt="screen shot 2017-05-18 at 2 17 40 pm" src="https://cloud.githubusercontent.com/assets/15912063/26219485/cd45b282-3bd4-11e7-997b-0c728c37d125.png">

Our 'VTC' filter on explore is a front-end angular filter that hides results that don't match. This won't persist on a refresh or link share and makes django-based pagination incorrect (and can result in dozens of seemingly-empty result pages)

I was developing on our JS controller to add it on to the query object getting sent to the API (i.e.  `$scope.query.Volunteer_Technical_Community`) and in the url (`http://192.168.56.151/search/?storyteller&limit=30&offset=0&Volunteer_Technical_Community`) so that it will work with pagination and page refresh. Prior to PR660, adding a line like [this](https://github.com/MapStory/mapstory/commit/4466a3fefaad53ffceba2317212c7c289deb74b2) ` 'Volunteer_Technical_Community': ALL` enabled me to use this filter in the API, However, unlike the City and Country filter in review [here](https://github.com/MapStory/mapstory/pull/708/commits/70ef7266a18838dd1746b52cb38ad13e6453e174), I can't seem to get this VTC filter to cooperate on the new MapstoryOwnersResource. Halp?

**Comment by sarasafavi** [comment]
@Coop56 
![image](https://user-images.githubusercontent.com/1209376/30457519-769c32ae-995c-11e7-84d3-6b5961181294.png)

**Comment by Coop56** [comment]
"@Coop56 Coop56 assigned sarasafavi and unassigned Coop56 7 minutes ago"

Waffle why did you do this to me.  I did no such thing.  All I did was reload the issue in Waffle and that apparently assigned you.  Sorry @sarasafavi :P
