### ISSUE TITLE
fix URL routes from Compose MapStory link on homepage

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#667]
The routes to composer got changed from the 'Compose MapStory' link on the homepage. Currently clicking compose mapstory from home leaders you to /maps?tour and looks like this:

![screen shot 2017-04-19 at 1 39 14 pm](https://cloud.githubusercontent.com/assets/2573761/25532850/58723592-2bf4-11e7-80ba-2e3aaad1047c.jpg)

![screen shot 2017-04-28 at 9 14 49 am](https://cloud.githubusercontent.com/assets/2573761/25532861/5e6de4dc-2bf4-11e7-8a2c-f6f9f36e8d61.jpg)

The "Compose MapStory" link in the header works fine, however.

**Comment by Coop56** [comment]
This was already resolved with PR https://github.com/MapStory/mapstory/pull/648 so I assume it hasn't been deployed yet.  @cuttlefish?

**Comment by cuttlefish** [comment]
That's correct. I'll do a deploy to demo tonight or tomorrow. If everything looks good we can push to prod on Monday.

**Comment by cuttlefish** [comment]
Demo should now be deployed with ccbf349b9a284482dad028f37a33c14f664c50e7
The problem seems to be resolved. I'll push it to production tomorrow.
