### ISSUE TITLE
Update sharing to latest Twitter Card

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#677]
**User Story:**

As a user, I want to share Mapstory content on Twitter visually, so that the viewer of my tweet sees animation that my mapstory content intends to show.

**Acceptance Criteria**

- From a mapstory detal page, add a sharing option for Tweet This.
- Configure mapstory media output (i.e. Gif? Video?) to align with Twitter card policy, so that visual appears similar to examples linked below.

**Workflow**

- When user clicks "Share this" button on mapstory detail page they currently have options to share link or copy/past embed. Under these two options we can add "Tweet". Clicking tweet should bring up the "Share a link on Twitter" twitter dialogue with a pre-loaded but editable tweet. Pre-loaded tweet should have: MapStory Title, link, via @MapStory by StorytellerName and animated thumbnail in appropriate format.

See below for a depiction of this workflow in Youtube, which is similar

![screen shot 2017-07-07 at 11 28 53 am](https://user-images.githubusercontent.com/2573761/27967207-ca379f10-6307-11e7-9099-33cfb61a630f.jpg)

**Notes**

Work was done on Twitter Cards on retro. Here's a link to the issue and discussion for reference:

https://github.com/MapStory/mapstory-meta/issues/500

Twitter Card docs for developers can be found at https://dev.twitter.com/cards/overview.

Examples of animated maps shared on Twitter:

https://www.youtube.com/watch?v=o5dQKDtfb28&feature=youtu.be
http://lenkiefer.com/2016/08/24/more-maps
https://twitter.com/CSIS/status/828670600461692928/photo/1

Here is a single chapter mockup produced by @reynalddizon:

![www gifcreator me_1knskj](https://cloud.githubusercontent.com/assets/2573761/25756890/10b150ae-318e-11e7-8b8d-1d1ee3e67335.gif)

Here's a multiple-chapter mockup from Rey Dizon at super-small size
![stories_gif_with_annot_sm](https://cloud.githubusercontent.com/assets/2573761/25960938/216cfe66-363e-11e7-82d8-9e7fd397e83e.gif)

And a multiple-chapter mockup at i-phone size:
![stories_gif_with_annot_lg](https://cloud.githubusercontent.com/assets/2573761/25961067/8e66bfe8-363e-11e7-98d4-a276dce041d4.gif)

Here is a breakdown of the elements the Twitter Card media output would include (right side column):

<img width="1063" alt="screen shot 2017-05-05 at 5 11 31 pm" src="https://cloud.githubusercontent.com/assets/2573761/25756919/294b851c-318e-11e7-9a25-031b62af0f3c.png">

**Comment by jonpmarino** [comment]
As a user, I expect that if I tweet a layer or story, the standard tweet will use a "twitter card" format which will include the thumbnail for the layer or story i'm sharing. If this thumbnail is an animated GIF, the twitter card should show this animated gif.

Based on a test with https://beta.mapstory.org/layers/shootings_47e21ec7 the tweet appears with just text and links but now image included:

![screen shot 2017-08-04 at 2 28 20 pm](https://user-images.githubusercontent.com/2573761/28984136-18a68e24-7922-11e7-8505-2ce265962b5d.jpg)

**Comment by josellausas** [comment]
There was a url error that has been fixed. This is the result I get for sharing the URL on Twitter

![screen shot 2017-08-08 at 6 41 40 pm](https://user-images.githubusercontent.com/4162671/29099349-883ec3d2-7c6a-11e7-9e89-dc9d51f8bfe7.png)


Also from Twitter card's documentation: (only first image of GIF will be used)

![screen shot 2017-08-08 at 6 42 24 pm](https://user-images.githubusercontent.com/4162671/29099358-9669a9f4-7c6a-11e7-8914-a9d38e4ddd85.png)

**Comment by jonpmarino** [comment]
thanks @zunware. that stinks about only first image. Perhaps in a future implementation we will have to look at formats that show the animation in the tweet, like video. But good for now. thanks!
