### ISSUE TITLE
Layer thumbnails currently generated have no basemap

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#679]
**Bug**

When a StoryLayer or MapStory is published, a thumbnail is generated that appears on the Explore page. Currently the thumbnails generated have no basemap. The thumbnail shows features on a blank white background:

![screen shot 2017-05-05 at 12 34 00 pm](https://cloud.githubusercontent.com/assets/2573761/25757186/2e9fc194-318f-11e7-933c-303bb9da9a93.jpg)

**Minimum Acceptance**

A default basemap should appear as part of thumbnails.

**Stretch goal**

Ideally, for MapStories the thumbnail would use a basemap background that the storyteller has used in the story itself in Chapter 1.

**Comment by jonpmarino** [comment]
A thought - could this just be a function of using MapBox World Light as a default? If we changed the default basemap used to something else would a basemap then show up in thumbnails as before?

**Comment by jonpmarino** [comment]
Update - on Beta it now appears no thumbnail is being generated for layers. 
![screen shot 2017-08-14 at 12 15 44 pm](https://user-images.githubusercontent.com/2573761/29282966-6a802dd4-80ea-11e7-8368-d8870930ea19.jpg)

**Comment by cuttlefish** [comment]
Is this resolved?
