### ISSUE TITLE
Unable to edit user avatar, routing issue?

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#684]
Re: PR #660 

From Edit Profile page, I am unable to update a user's avatar. 

<img width="892" alt="screen shot 2017-05-05 at 9 14 57 pm" src="https://cloud.githubusercontent.com/assets/15912063/25769147/07dacbfa-31d8-11e7-8f19-cd3e4ce132d4.png">

**Comment by jonpmarino** [comment]
Just confirmed this on my jonpmarino account on Beta. Is this PR still in review?
