### ISSUE TITLE
Initiative Page MVP

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#690]
Using the recently completed Organization Page code, implement an "Initiative Page". The MVP Initiative Page will have the same baseline functionality as the Organization Page. Over time the 2 page types will diverge based on new feature requirements that emerge through use.

**Acceptance Criteria**

- Enable MapStory admin to create the Initiative Page in django-admin and assign users to administrate/lead the Initiative Page

- Have Initiative Pages resolve to a URL path mapstory.org/initiative/NAME

- Add to Storyteller Type filter in Explore>Content for Initiatives

**Comment by glynnis** [comment]
@jonpmarino Can you provide the retro and beta work here so @Coop56 and I are able to reference it?

**Comment by jonpmarino** [comment]
Here is a link to the beta ticket for Initiatives. It has a screenshot showing an old Initiative page, https://github.com/MapStory/mapstory-meta/issues/1154. 

There were no Initiative pages in Retro, Just org pages. I corrected the note above.

**Comment by rob-metalinkage** [comment]
Is there any doco on this - we have discussed how this will interact with reference data,  gazetteers and eras  (initiatives may revolve around pre-defined data templates with a gazetteer harvest model, and the link to era definitions will probably be a similar thing)

**Comment by jonpmarino** [comment]
Hi Rob, the task Jose / @zunware is working here is not at all related to uploader or data model in terms of "initiative driven importer". The Initiative Page that he's working on is just a twin sibling of the Organization Page where a page administrator can assemble layers and stories considered to be part of that "initiative". So we can have a single "profile" page for MapStory Invasive Species initiative, or MapStory Beer, or what have you. It is constructed as a django-app that can be extended with new features and capability in the future. @zunware can detail how he's set it up.

Right now an Initiative page admin will just manually decide what layers or stories are included on the page.  Once we have the work going on the data/importer side that you mention, that will help determine what "counts" as being part of the initiative. Perhaps once he's ready with the MVP Initiative Page, Jose can do a demo to include you so you can map out the interconnections.

Write up on Org and Initiative Pages in roadmap is here, https://github.com/MapStory/mapstory/wiki/Data-Import-&-Management-Improvements#initiative-driven-importer
