### ISSUE TITLE
Create wireframes for changes and additions needed to accommodate Organization Page workflows

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#695]
Create wireframes and/or high-fidelity mock-ups for changes and additions needed to accommodate Organization Page workflows throughout the rest of the site.

I'll need to make sure this list is complete by talking more with @Coop56, but here are a few needs that I know we'll need to include in this effort:
- Pricing page for Organization Pages
- Form for initial creation of an Organization Page
- Administrative features of Organization Page
  - Adding additional admins
  - Removing admins
  - Receiving a notification that someone has added you as an admin
- Adding/removing Organization Members to Organization Page
- Editing "About" content for Organization Page
- Adding/editing/changing avatar for Organization Page
- Switching between acting as a regular user and acting as an organization
  - Adding content to the "Featured Content" area (other users' StoryLayers and MapStories)
  - Importing layers as an organization
  - Uploading icons as an organization
  - Creating MapStories as an organization
  - Publishing, editing, and saving drafts of journal entries as an organization
  - Removing or deleting/undoing any of the above

**Comment by jonpmarino** [comment]
3 thoughts:

1) add a space for links on the lefthand sidebar separate from the org homepage and social media links.

2) consider a space for org to customize a banner in addition to their logo

3) reflect where playlists created by the org will exist on the org page in future releases. (See https://github.com/MapStory/mapstory/issues/675 - playlists are sets of multiple mapstories that can be played on a loop in museum mode without user interaction)
