### ISSUE TITLE
Create wireframes for multiple authors

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#713]
Given user research findings from #692 and @jonpmarino's direction to go ahead with multiple author support (with Organization pages in mind), @Coop56 and I need to create a spec that outlines our plan for multiple author support.
* Multiple author support on StoryLayers (possibly as part of importer task flow, or worst case as part of the layer detail page)
* Multiple author support on MapStories (possibly part of MapLoom/Composer, possibly waits until StoryTools refactor, or worst case as part of the MapStory detail page)
* Multiple author support for version control/GeoGig (not sure if this will be part of the initial work but we should consider it and make a decision)

Assumptions:
* Multiple author support allows for nominating other MapStory users as additional authors
* Initially, there will not be support for authors who do not have MapStory accounts
* Indications of funders or other players who are not authors of the data should be considered separately
* Once work on organization features is underway, an Organization should be able to exist as the single author of a StoryLayer or MapStory, or as one of multiple authors.
* The wireframes and specs for this feature should be created with the intent of sharing our specs with GeoNode in a "do you want this? yes/no"-type interaction. This will prevent unnecessary back and forth or negotiation of features, when our primary concern is getting this implemented for MapStory users.

**Comment by jonpmarino** [comment]
Just a note that multiple author support is mentioned in our Roadmap and thus was already a desired featured - https://github.com/MapStory/mapstory/wiki/Next-Plateau#collaborative-story-composing. Its being moved up given strong user requests and the Org Page model's dependency on it.
