### ISSUE TITLE
Homepage design revisions

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#720]
- [x] Footer can switch back to original
- [x] Header revisions for Chris to approve from Glynnis
  - [x] Based on the two designs that have Central America/no video
  - [x] Have three versions prepared to send him
- [X] Text revisions once ready from @jonpmarino and Chris to go into template/coding (no further mockups needed)

Replace "Improve data accuracy through collaboration" with "Share your expertise through edits"

Replace 2nd call to action with ""The more we all know about the story of our planet, the more likely we are to treat it, and each other well. Sign up, and become a mapstoryteller today.""

- [X] List of six featured stories from @jonpmarino.
Based on the stories that seem to playback reliably right now that give us a good range of geographical, topical, storyteller and timespan diversirty:

1. https://mapstory.org/story/21510 (Holly Winscott)
2. https://mapstory.org/story/21977 (Jeff Meyer)
3. https://mapstory.org/story/21133 (Jonathan Davis)
4. https://mapstory.org/story/20868 (Everett Lasher)
5. https://mapstory.org/story/21037 (Kathryn Pole)
6. https://mapstory.org/story/20881 (Shobona Atmaraman)

- [X] Sign up text from @jonpmarino for footer
"MapStory is the atlas of change that everyone can edit. We're a community mapping how the world evolves geographically at local, regional and global scales. Our work is sustained by the nonprofit MapStory Foundation and dedicated mapstorytellers and sponsors. Join us!"
- [ ] Notes for future iterations and releases
- [x] Explanatory section "How It Works" stays the same until we have better images

**Comment by glynnis** [comment]
Here are the alternate header versions:

*A* - The circle overlay Chris liked, but with the white navigation background. I added a drop shadow under the navigation to fix some of the design issues I mentioned so that it still looks good with the light background.
*B* - The gradient treatment I presented last week, unchanged.
*C* - Another shape overlay, this time with the SFMTA Bike Lanes map
*D* - A light cream overlay over the Karenis Brevis Florida map. This map works especially well since the left side has a land mass that works well for text legibility, and all the motion and map content is over on the right side.

<img width="1746" alt="hero_options" src="https://cloud.githubusercontent.com/assets/1529366/26326199/da6214a0-3eff-11e7-9fea-932ea6edd108.png">

I'll update here once I hear back from Chris about which he wants to move forward with.

**Comment by jonpmarino** [comment]
we prefer Option A. Also, lets lose the ! after "The atlas of change that everyone can edit"

**Comment by glynnis** [comment]
Finalized homepage design, which has been approved by @jonpmarino:
<img width="1440" alt="homepage_final" src="https://cloud.githubusercontent.com/assets/1529366/26375768/cda566f6-3fcf-11e7-98d9-03c22d5f66a6.png">

I've also posted it to InVision here with comments that may be useful for implementation/CSS: https://invis.io/CXBUJ137Y#/235280586_Homepage_Final

**Comment by glynnis** [comment]
Assets and design files for this work are now part of the mapstory-assets repo here:
https://github.com/MapStory/mapstory-assets/tree/master/design_assets
I'm still pushing to GitHub and need to submit a PR, but I think this link is where it will end up once it's merged.

I've also sent invites to the team to the Boundless Google Drive folder where the same assets are housed. For Boundless folks, you can search for "MapStory" which lives in the Design folder (`Design > UI > MapStory`)

**Comment by glynnis** [comment]
PR for design assets: https://github.com/MapStory/mapstory-assets/pull/5

**Comment by josellausas** [comment]
The new design is being implemented in issue #727
