### ISSUE TITLE
Homepage re-design implementation

### ISSUE THREAD

**Issue by josellausas** [MapStory/mapstory#727]
Implement approved homepage re-design changes from #720 

<img width="1440" alt="homepage_final" src="https://cloud.githubusercontent.com/assets/1529366/26375768/cda566f6-3fcf-11e7-98d9-03c22d5f66a6.png">

**Comment by glynnis** [comment]
@zunware I've got a PR up with all the assets that should be ready to use in front end development of the homepage here: https://github.com/MapStory/mapstory-assets/pull/6

Some notes:
* `05-23-2017.pdf` is a PDF version of the overall design file that I think you can open or import into Sketch. There's also the Illustrator file with the `.ai` extension in case that's useful.
* For the hero area, I've got a fallback image, `hero_img_fallback.png`, but this section should be animated when possible (probably with a video call).
* For the middle explanatory section, there is `expertise_through_edits.png`, `global_data_commons.png`, and `map_small_fallback.png`. The map will ideally be animated, but I've included the image for a fallback.
* Icons for the "How It Works" section are the files starting with `icon_`. I've included both the SVG and transparent PNG versions depending on what makes sense. Ideally SVG would be used to leverage vector scaling.
* For the blue section near the bottom, I've got `bg_topography.png`, but I also included the original pattern, `topography.png` in case it makes sense to do the blue color separately via CSS.
* Sponsor logos all begin with `sponsor_`. The ERDC logo has a white background unfortunately, but @jonpmarino is working on getting a vector file that can be made into a transparent logo. Original vector files for sponsor logos (if we have them) are in the `sponsors_vector` folder.

You can also see notes and implementation details for CSS properties on InVision comments here:  https://projects.invisionapp.com/share/G8BV9PSJQ#/screens/235280586/comments
