### ISSUE TITLE
Deploy geogig 1.1 to a mapstory demo instance for testing

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#737]
**Task**

Now that Geogig 1.1 has been released, we need to begin to assess its performance for MapStory as we gear up to make "community versioned editing" a more central part of the MapStory user experience.

**Acceptance Criteria**

Deploy Geogig 1.1 to the environment that makes such, such as lab.mapstory.org or demo.mapstory.org

**Comment by cuttlefish** [comment]
This was done on lab, but is now being setup properly on beta. See 756
