### ISSUE TITLE
Importer Update breaking on previously uploaded data

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#742]
Hey, heads up, changes from PR #729  work fine with new uploads 
<img width="717" alt="screen shot 2017-05-31 at 12 51 39 pm" src="https://cloud.githubusercontent.com/assets/15912063/26646278/9a11b0f6-4600-11e7-852b-1cd7bd67adca.png">

but the importer api breaks on any data that was uploaded before this PR
<img width="690" alt="screen shot 2017-05-31 at 12 52 18 pm" src="https://cloud.githubusercontent.com/assets/15912063/26646287/a010c28a-4600-11e7-9637-3e2ddc33c74a.png">
<img width="699" alt="screen shot 2017-05-31 at 12 52 36 pm" src="https://cloud.githubusercontent.com/assets/15912063/26646295/a5cc41a4-4600-11e7-86b4-321e2d27f67b.png">

Should be fine for pushing to demo, but it was blocking me locally (I'm making new users with uploads) and we'd definitely want to address this before it goes to production.

**Comment by emilyashley** [comment]
cc: @cuttlefish we probs shouldn't deploy to production until this is addressed? Or I can temporarily hide the uploads tab altogether in the meantime if this is a hard blocker.

**Comment by Coop56** [comment]
Closing as Beta does not have any previously imported data from before this change.
