### ISSUE TITLE
Add6ish more projection support to os-geo importer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#746]
**User Story**

As a user I expect when I upload data to MapStory in a supported file type that MapStory will be able to handle the projection in my data (as long as its a quite common projection).

**Acceptance Criteria**

- Determine if best solution is to support the projections themselves or translate them all to one projection upon import or translate ones we can't identify immediately.
- Implement determined solution (more tickets may be required)

**Comment by Coop56** [comment]
Resolved by https://github.com/GeoNode/django-osgeo-importer/pull/167
