### ISSUE TITLE
Style new profile card and integrate into profile layout

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#754]
![screen shot 2017-06-08 at 1 28 04 pm](https://user-images.githubusercontent.com/15912063/26944463-5a29c308-4c4e-11e7-8118-324fcfc8c44e.png)

prerequisites for integration: #749 #745 
does *not* include development of dropdown to edit profile & settings

**Comment by jonpmarino** [comment]
@emilyashley for your reference found this screenshot of the profile page on retro, 
[PastedGraphic-7.pdf](https://github.com/MapStory/mapstory/files/1187850/PastedGraphic-7.pdf)
