### ISSUE TITLE
Set up beta.mapstory.org as a clean instance

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#756]
This will be a clean fresh build where we will feed legacy user accounts, layers, and high quality new stories.

When it is sufficiently populated with legacy user accounts, layers and stories we will point mapstory.org production domain to this service

**Comment by Coop56** [comment]
Should we use the latest version of Geogig here?  If we don't - what are the repercussions down the road to having to update to it instead?  @cuttlefish  We want this instance to be for the long term, and not have to do a clean rebuild anytime in the future.

**Comment by cuttlefish** [comment]
It's been setup with persistent networked disks. It still needs the newest GeoServer and GeoGig added.
