### ISSUE TITLE
Address brand customization on homepage design before deploying to StoryScapes

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#773]
Needs requirements for customization of any/all copy language, Sponsors, Footer Content, and Featured Stories for the StoryScapes instance of the homepage to implement either via THEME in settings or another preferred way.

**Comment by emilyashley** [comment]
Ties into #837

**Comment by cuttlefish** [comment]
https://docs.google.com/document/d/1UifPMmuGC7S7CKX5CNhQzRjQ7HnVNFogZFvIFQYKhs0/edit
