### ISSUE TITLE
Get latest gazetteer workflow/modules installed into lab.mapstory.org

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#783]

**Comment by rob-metalinkage** [comment]
installed and tested against sample data - exposes link examples for Ux integration tasks

need to know short term update cycle - and get some review of how fixtures etc are affected by processes others invoke.

**Comment by rob-metalinkage** [comment]
This depends on getting the docker build on local dev working for me, #790 then working out how add modules #791
