### ISSUE TITLE
Module extension pattern for docker deploy

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#791]
Need to be able to  add and manage an extension module to a deployed GeoNode or Mapstory environment, as per https://github.com/MapStory/mapstory/wiki/Update-Use-Cases (move to GeoNode at earliest possible time too!)

(which needs to be updated to reflect the full scope of supported Use cases - and provide health warnings for obvious cases not well supported yet!)

**Comment by rob-metalinkage** [comment]
Spoke with @davisc about this -he was going to have a look and provide feedback about how Boundless Exchange was handling this.  In the meantime the suggestion is for module install processes to use bash - then invoke this from docker or ansible or X as required (more generic modules cannot assume docker used for all django). Will start with this process...

**Comment by rob-metalinkage** [comment]
So question 1 here - we have a bunch of war files to deploy - RDF server, workbench (which provides necessary management API to automate build) and a REST/SPARQL client.  I suspect we would want to run this in a separate container to the geoserver - so this component can scale differently to geoserver - this is a fairly heavy footprint to duplicate in a dev context - but maybe thats OK for now.  Certainly its update cycle will be more dynamic that geoserver during development over next 12 months.  So i'm guessing two scripts for the semantic layer (django-rdfio) - one for the server container and one to inject modules into a running django container?  What about dependent modules that then use this? Currently only install scripts need to know the RDF server location to load fixtures - but perhaps they should register these with the rdfio module to load on their behalf.

**Comment by rob-metalinkage** [comment]
Q2 - the REST/API will be running on some other container - what is required to make these accessible to the outside world - is this a proxy config in the nginx container. whereby it accesses the tomcat in its own container.  Is this something a script should self-report to something in the nginx container that will register this requirement - or will it mean manually hacking the nginx config?

**Comment by rob-metalinkage** [comment]
Q3: how to run continuous integration tests for installed modules - what should modules expose to make this automatic?

**Comment by davisc** [comment]
@rob-metalinkage Take a look at the docker compose file for Boundless Exchange specifically the registry container and the exchange container. Also the RDF server container could be modeled after the Geoserver container.

https://github.com/boundlessgeo/exchange/blob/master/docker-compose.yml

**Comment by rob-metalinkage** [comment]
helpful - its an ugly thing though - all those fixed ip dependencies sprinkled through it.  

this was really useful:
https://github.com/boundlessgeo/exchange/tree/master/docker

What are _all_ the pieces of the puzzle that need to be managed: 

where is the container itself defined? is this actually the directory docker/<imagename>  - referenced by the image: property of a service..

if the module managed is elsewhere, does that mean we have to hack the master project docker directory to make it work - and could an install script look for a <module>/docker directory and write it to <master>/docker/<module> as a way to pick up this configuration?

Could the docker-compose.yml look for per-module service configurations in the docker/ and include them - or am i reading to much into docker's file structure requirements?
