### ISSUE TITLE
Chapter info sidebar on viewer does not allow text to extend to full height of the sidebar

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#831]
As a user, I expect that if a MapStory has enough text in the Chapter info area of the sidebar to require a scrollbar, then all the available area in the sidebar should be filled with content (text, chapter advance buttons).

However, currently we cut-off the text about halfway down the sidebar making the text area extremely small, and leave empty whitespace below.

the screenshot below illustrates and provides devtools information for problem solving.

![screenshot_from_2017-07-14_07-10-01_720](https://user-images.githubusercontent.com/2573761/28227767-0d25a008-68a1-11e7-8382-596d24051e96.png)

**Comment by emilyashley** [comment]
This was shortened in February when we modified the viewer sidebar so chapter navigation (next chapter, previous chapter buttons) don't require scroll or end up hidden (especially when timeline and or playback settings are open)

I can expand it again if desired. Or we can spend time in the future to plan and refactor how these different widgets interact or overlay on each other.
