### ISSUE TITLE
Address site-wide use of {{sitename}} variable as language for MapStories

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#837]
We had been using the `{{SITENAME}}` variable from settings to distinguish between content types (MapStory, Story, StoryScape) in both HTML and JavaScript. However, with the updated deployments, they've exposed that this is not a reliable mapping of what language should be used. You might see `example.com` or `demo.mapstory.org`, etc.  I've got the go ahead from Clarence to change the instances below to be hardcoded as `MapStory`

As I find more, I'll drop them in the comments.

Please lemme know if we need to come up with a different way to distinguish them (maybe a different variable not tied to `{{sitename}}`) if we need to do otherwise. But I'm under the impression that we don't have to distinguish them now.

![Screen Shot 2017-07-17 at 12.32.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570697024a4dff0e00dfbeed/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f46b7191a379ed0c2853415d46bc21254d58eeb9cb74fce36f34985619e8d96a5b75c13b11fdbf871ded05b9718b4f87b5b4821896fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be14e54ad1a306be671316e0a.png)
![Screen Shot 2017-07-17 at 12.32.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570697024a4dff0e00dfbeed/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f46b7191a379ed0c2853415e47bc21254d58eeb9cb74fce36f34985619e8d96a5b75c13b11fdbf871ded05b9718b4f87b5b4821896fa2137a5dad11b61435c52dcbd4f3fb29b4dc259f34be14e54ad1a3160e772366e0a.png)
![Screen Shot 2017-07-17 at 12.37.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570697024a4dff0e00dfbeed/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f46b7191a379ed0c2856415a47bc21254d58eeb9cb74fce36f34985619e8d96a5b75c13b11fdbf871ded05b9718b4f87b5b4821896fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be14e57a4103567e775366e0a.png)

**Comment by jonpmarino** [comment]
another - 
![screen shot 2017-07-18 at 9 01 14 am](https://user-images.githubusercontent.com/2573761/28321042-cc7db44c-6b97-11e7-8340-4007be06fe13.jpg)

**Comment by emilyashley** [comment]
geogig info from an edit says "from MapStory Composer" so thats also a thing we'd have to catch
