### ISSUE TITLE
Text Query search should recognize words connected by an underscore

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#839]
As a user, I expect if I type a word into the Text Query search it will generate results for any layer or story that has that word in its title.

Currently our Text Query  search will not generate results if the word is connected to other words with an underscore.

For example, if I search for ivory, I am told there are no results, even though I see a layer with the word ivory in it:

![screen shot 2017-07-17 at 3 12 38 pm](https://user-images.githubusercontent.com/2573761/28287823-a51c5204-6b02-11e7-81d8-4c5615490a72.jpg)

![screen shot 2017-07-17 at 3 12 52 pm](https://user-images.githubusercontent.com/2573761/28287828-abdf2a1c-6b02-11e7-96f1-cbb08394f590.jpg)

If I log in as an admin and change the layer name in the Metadata modal so that underscores are replaced with spaces, a Text Query  search generates results when the word "ivory" is searched for:

![screen shot 2017-07-17 at 3 13 28 pm](https://user-images.githubusercontent.com/2573761/28287869-cc36ac90-6b02-11e7-9643-5aac412e5ba9.jpg)

![screen shot 2017-07-17 at 3 13 45 pm](https://user-images.githubusercontent.com/2573761/28287872-d2519fae-6b02-11e7-90fb-cb2005179858.jpg)

**Comment by emilyashley** [comment]
:tada::tada::tada:

**Comment by emilyashley** [comment]
Update, @jonpmarino I edited some of your language above and switched out 'Keyword Search' to 'Text Query Search' since keywords is a word often used to describe a different query to the API (what you and I and users would call Tags)

**Comment by emilyashley** [comment]
#### Braindump for @Coop56 

So [Here](https://github.com/MapStory/mapstory/blob/master/mapstory/api/resourcebase_api.py#L204) is where we tackle handling multiple words FROM the users text box input to the API for resources (i.e. Layers & Stories, not users, owners, orgs, etc) --- at first I thought this is where I needed help to handle the regex for underscores... but on second thought it has to do with the results COMING from the API, not the text query GOING to the api. 

I've tried changing some of the django query syntax around (i.e. like some nearby examples, `title__exact=phrase`, `title=Raw(search_word)`) and trying out other ones like `__contains` or `_icontains` etc, but I was mostly just trying to conjur up an answer. Here's teh docs I was starting to read when I got distracted on the issue (probs the wrong version) http://django-haystack.readthedocs.io/en/v2.4.1/searchqueryset_api.html  && http://django-haystack.readthedocs.io/en/v2.4.1/searchqueryset_api.html#id1

**Comment by jonpmarino** [comment]
thanks @emilyashley !!

**Comment by Coop56** [comment]
Closed by #1005.
