### ISSUE TITLE
Category dropdowns are not populating because Category and Regions API are empty.

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#841]
Category dropdowns are currently not populating in Composer and Layer Metadata 
This _might_ be a local build issue, but stashing it here so I don't lose track of it.
![Screen Shot 2017-07-17 at 4.14.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570697024a4dff0e00dfbeed/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f46b7191a37cf1132f4f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ee5d6695e73c03d40abbd804dbb02eb208b4d86beb4de1ad2f42f67b6d5db1063474f4dcbed5727a39841c95df64be24e56a0133f65ee752431.png)
![Screen Shot 2017-07-17 at 4.15.31 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570697024a4dff0e00dfbeed/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f46b7191a37cf1132e4f5c5e5ecc3c4a4356bcbbd671f3e57862804e0ee5d6695e73c03d40abbd804dbb02eb208b4d86beb4de1ad2f42f67b6d5db1063474f4dcbed5727a29f41c95df64be24e56a0133f65ee722431.png)

**Comment by emilyashley** [comment]
Categories are also not available in the search Sidebar.

Looking at https://docker/api/regions/ && https://docker/api/categories/ these are empty. We populate our front-end info from these api's.  

Should I re-open https://github.com/MapStory/mapstory/issues/685  (see PR https://github.com/MapStory/mapstory/pull/699) or are these [fixtures](https://github.com/MapStory/mapstory/blob/master/mapstory/fixtures/initial_data.json) not set up to run locally? Also happens on beta.

cc: @cuttlefish

**Comment by emilyashley** [comment]
Confirmed the data is on Beta now :) Thanks, @cuttlefish

**Comment by cuttlefish** [comment]
Sorry, lost track of this issue. I should set it to populate these for all deploys, right?

**Comment by Coop56** [comment]
This is resolved in the new Composer, closing.
