### ISSUE TITLE
Add fields to select category and complete summary for layers in importer modal

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#843]
In order to enhance Search performance, add ability for the user to select a category and enter a summary in the importer modal. This information will be captured and populated in the metadata form for the layer.

The category drop-down and summary text box can be added to the form in the importer modal that currently lets the user enter a Layer Title.

![screen shot 2017-07-18 at 8 54 39 am](https://user-images.githubusercontent.com/2573761/28320667-ce6bfdaa-6b96-11e7-94c2-33eca2b36ab1.jpg)

This work was already completed in Exchange (https://github.com/boundlessgeo/exchange/pull/323) and can be carried over to MapStory.

Note - #838 specifies a slight change to the Layer Title entry in importer modal that should be consulted as part of this issue.

Note - ticket made at request of @davisc

**Comment by emilyashley** [comment]
yes! just a heads up that I also need to look into #841 for categories being unavailable (local env) on the mapstory module root scope so don't be alarmed if that's the case.

**Comment by jonpmarino** [comment]
@davisc doing some ticket grooming. Is this ticket that you requested complete? Can it be closed? Doesn't look like those categories are available in MapStory import modal at the moment but not sure if that's what you were intending or not.
