### ISSUE TITLE
Double check that `map` types are kept from Explore page on production

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#845]
I had a map show up in a search - not a storylayer, not a mapstory, a map as in either a chapter or some remnant of a legacy story. I'm 95% certain I prevented this from happening with new data locally, so this is either a commit that hasn't made it up to prod yet or an issue that I won't see locally.

![screen shot 2017-07-18 at 2 01 06 pm](https://user-images.githubusercontent.com/15912063/28339739-f15bb5b4-6bc1-11e7-9bfa-ffafdf2f6202.png)

Raw API response [here](https://mapstory.org/api/base/search/?limit=30&offset=0&content&is_published&q=village%20destruction%20in%20the%20darfur) See three items, one is type: "map" from 2012-04-22 (not okay), the others type: "layer" and type: "mapstory" which are AOK.

`map` types won't display their card or their detail page properly as they are no longer intended for public view, so I gotta make sure and keep 'em outta search. 

Here's a ticket to double check that on prod when its bumped and address this issue if it's still there.

**Comment by lhcramer** [comment]
@emilyashley can this be closed because we are no longer on hipster.mapstory.org?
