### ISSUE TITLE
Stories on Activity Feeds are not being tracked

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#848]
This is an issue to list key activities that the current "Activity Feed" does not seem to be tracking. May need to be broken up into individual issues to isolate specific actions. 

(Based on beta.mapstory.org)

Activity feed is the tab on the user profile labeled "Activities". It should be a public display of a user's key actions. We should:

- [ ] First, make sure existing GeoNode activity tracking capabilities are turned on
- [ ] Once that's confirmed, audit what's missing and strategically add priority activities to track.

On beta.mapstory.org it looks like _only_ Uploads are being tracked. In the screenshot below for SojournerTruth only 2 upload activities are tracked. Any edits made, stories made, etc are not tracked. This could be a beta-only issue. Not sure yet until beta is made prod.

![screen shot 2017-07-20 at 1 05 47 pm](https://user-images.githubusercontent.com/2573761/28432372-4337f618-6d4d-11e7-928d-1637ed0edb82.jpg)

**Comment by emilyashley** [comment]
Note, story deletion is working again now thanks to @Coop56 on #924 

However we need to make sure story deletion is registering with the Activity Feed. It seems to log layer deletion (published and unpublished) but not story deletion

**Comment by Coop56** [comment]
Most things are tracked now, however creating or deleting a MapStory is still not showing up in the activity feed, so I'm leaving this one open.
