### ISSUE TITLE
Composer-MiniExplore -Partial Word search not functioning. Looking for layer "Asylum Centers" (u[...]

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#849]
**Sender**: cramer@mapstory.org
[Open #240 in Usersnap Dashboard](https://usersnap.com/a/#/mapstory-beta/p/mapstory-beta-abc33389/240)
**Notes**:
 - (1) Partial Word search not functioning. Looking for layer "Asylum Centers" (used in US#238) but no search results found. Possibly search results not using wildcards?

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/06-18/f874c080-0b41-441d-9035-3f928a1250b1.png'>![Usersnap Feedback - Partial Word search not functioning. Looking for layer "Asylum Centers" (u(...)](https://usersnappublic.s3.amazonaws.com/2017-07-19/06-18/7fa1f14f-f256-4d0f-9e84-ab0111f7dd3f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/06-18/f874c080-0b41-441d-9035-3f928a1250b1.png'>Download original image</a>

**Browser**: Chrome 59 (Linux)
**Referer**: [https://beta.mapstory.org/story/new?tour#add-layer-dialog](https://beta.mapstory.org/story/new?tour#add-layer-dialog)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 651

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by lhcramer** [comment]
@Coop56, @emilyashley , Has this been addressed in another issue / can it be closed?
