### ISSUE TITLE
Styling is not changing in composer.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#851]
**Sender**: jonpmarino@gmail.com
**Comment**: My styling is not changing. I am trying to compose a story using the asylumcenters layer on beta. I've changed the orange circles to blue triangles. this was saved but does not show up on the map or timeline.
[Open #238 in Usersnap Dashboard](https://usersnap.com/a/#/mapstory-beta/p/mapstory-beta-abc33389/238)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/05-30/10232639-7087-4ebe-85f2-99ccf9dcfb7a.png'>![Usersnap Feedback - My styling is not changing. I am trying to compose a story using the asylu(...)](https://usersnappublic.s3.amazonaws.com/2017-07-19/05-30/2375a610-b22d-4d81-8c53-30f7fe7b5819.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/05-30/10232639-7087-4ebe-85f2-99ccf9dcfb7a.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [https://beta.mapstory.org/story/new?tour](https://beta.mapstory.org/story/new?tour)
**Screen size**: 1440 x 900 **Browser size**: 1260 x 752

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by lhcramer** [comment]
Tested this using same layer and changes. Style changes updated upon exit of composer, resume draft and then entry into layer styling dialog again.  However, I couldn't repeat these steps to restyle to green squares.  Inspecting the `save style` button shows that action relates to storyService.save(), Potentially need to hook geosever refresh? Xpath = //*[@id="editStoryLayer"]/ng-include/div[5]/button

**Comment by cuttlefish** [comment]
Where are we at with this issue?

**Comment by davisc** [comment]
The current issue is `You don't have permissions to change style for this layer`

**Comment by cuttlefish** [comment]
Does this have something to do with it? I'm unclear how these permissions actually work.

![image](https://user-images.githubusercontent.com/1152120/29423102-79865ea6-8348-11e7-8cba-4286203b14be.png)

**Comment by davisc** [comment]
Yes, we need to modify the default perms on import to include the registered group for style editing.
Add the following to the settings.py file.
```
DEFAULT_IMPORTER_CONFIG = {
    'configureTime': True,
    'editable': True,
    'convert_to_date': [],
    'always_geogig': True,
    'index': 0,
    'permissions': {'users':{'AnonymousUser':['change_layer_data', 'download_resourcebase', 'view_resourcebase']}, 'groups':{'registered':['change_layer_style']}}
}
```

**Comment by cuttlefish** [comment]
Would adding those layer/style perms in the admin panel help anything?

**Comment by emilyashley** [comment]
confirmed on beta

<img width="982" alt="screen shot 2017-09-18 at 2 44 48 pm" src="https://user-images.githubusercontent.com/15912063/30561274-143390fe-9c80-11e7-8da8-09cbd39b4d44.png">
