### ISSUE TITLE
After a polygon shape is edited, the playback still shows the previous shape

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#865]
**Comment**: Updated the shape of a feature (outlined by the blue border). I refreshed the page and the orange area (which is the initial form) is still displayed. But when i clicked the the orange feature, it outlines the updated shape. Layer: geonode:isil_expansion_62f979fa
[Open #254 in Usersnap Dashboard](https://usersnap.com/a/#/mapstory-beta/p/mapstory-beta-abc33389/254)

The expected behavior is that once the polygon shape is changed, future playback would show the updated shape of the polygon.

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-21/13-41/64aacad7-53a0-4c54-b5a1-19af522d9695.png'>![Usersnap Feedback - Updated the shape of a feature (outlined by the blue border). I refreshed (...)](https://usersnappublic.s3.amazonaws.com/2017-07-21/13-41/9b867ed8-81d2-44a5-8416-063040c25184.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-21/13-41/64aacad7-53a0-4c54-b5a1-19af522d9695.png'>Download original image</a>

**Browser**: Chrome 58 (macOS Sierra)
**Referer**: [https://beta.mapstory.org/maps/edit?layer=geonode:isil_expansion_62f979fa&mode=edit](https://beta.mapstory.org/maps/edit?layer=geonode:isil_expansion_62f979fa&mode=edit)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 800

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by emilyashley** [comment]
Does this also tie in as a sub-example of #419 ?
