### ISSUE TITLE
Reduce date fields presented to only those needed (we think its the _xd)

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#868]
**Sender**: nitingadia@mapstory.org
[Open #208 in Usersnap Dashboard](https://usersnap.com/a/#/mapstory-beta/p/mapstory-beta-abc33389/208)
**Notes**:
The attribute editor form exposes additional time fields to the user that may be just for developer purposes. Should these be exposed at all?

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-04/21-01/b137ea7e-abf4-42dd-8c63-4bd711c62b62.png'>![Usersnap Feedback - What is all this extra stuff?? Was told it has to do with enabling negativ(...)](https://usersnappublic.s3.amazonaws.com/2017-07-04/21-01/5c3959a5-a327-491a-bca3-ded2f2d99858.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-04/21-01/b137ea7e-abf4-42dd-8c63-4bd711c62b62.png'>Download original image</a>

**Browser**: Chrome 59 (Windows 10)
**Referer**: [https://mapstory.org/maps/edit?layer=geonode:ames_buildings_1_19_2017_1&mode=edit](https://mapstory.org/maps/edit?layer=geonode:ames_buildings_1_19_2017_1&mode=edit)
**Screen size**: 1920 x 1080 **Browser size**: 1536 x 779

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by emilyashley** [comment]
connecting some other notes here: https://github.com/MapStory/mapstory/issues/1047
