### ISSUE TITLE
Common layer editing error: "TypeError: Cannot read property of null"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#869]
**Comment**: Users are frequently getting a layer editing error that looks like the screenshot below. In this example, the user had selected a point in 2015, and then moved the time cursor back in time. After, there was an error that prompted on screen.  

Our hypothesis is that Maploom may not like it when layers have empty cells. Perhaps importer is successfully importing data with missing cells, but maploom doesn't like it. So, once a layer is edited Maploom throws errors. 

[Open #193 in Usersnap Dashboard](https://usersnap.com/a/#/mapstory-beta/p/mapstory-beta-abc33389/193)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-21/17-06/333d8d26-b9d7-4555-a8af-3e379a6af66b.png'>![Usersnap Feedback - I had selected a point in 2015, and then moved the time cursor back in tim(...)](https://usersnappublic.s3.amazonaws.com/2017-06-21/17-06/ea108b40-59e0-407c-9eda-d02822238e88.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-21/17-06/333d8d26-b9d7-4555-a8af-3e379a6af66b.png'>Download original image</a>

**Browser**: Chrome 58 (macOS Sierra)
**Referer**: [https://beta.mapstory.org/maps/edit?layer=geonode:south_sudan_acled_master_993f6ceb&mode=edit](https://beta.mapstory.org/maps/edit?layer=geonode:south_sudan_acled_master_993f6ceb&mode=edit)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 780

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by emilyashley** [comment]
Addressed w/ https://github.com/MapStory/MapLoom/commit/9be3aa607973a5a91ce53a2fedc382f76867c9a4

pretty sure this catches what y'all are encountering but there’s a variety of issues that could give that same error display so lets keep an eye on it
