### ISSUE TITLE
Tell the user whether the edit attributes form is expecting a date, text or number for each attribute field

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#871]
**Sender**: nitingadia@mapstory.org
[Open #208 in Usersnap Dashboard](https://usersnap.com/a/#/mapstory-beta/p/mapstory-beta-abc33389/208)
**Notes**:
It is impossible for the user to know when editing whether the edit attributes form is expecting a number, text or a date. Not knowing this causes alot of unnecessary errors.

In the "Create Layer" form we ask the user to select whether each attribute will be a date, text or string, so presumably we know this information about our layers. Would their be a way to tell the user in the edit attribute form what is expected?

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-04/21-01/b137ea7e-abf4-42dd-8c63-4bd711c62b62.png'>![Usersnap Feedback - What is all this extra stuff?? Was told it has to do with enabling negativ(...)](https://usersnappublic.s3.amazonaws.com/2017-07-04/21-01/5c3959a5-a327-491a-bca3-ded2f2d99858.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-04/21-01/b137ea7e-abf4-42dd-8c63-4bd711c62b62.png'>Download original image</a>

**Browser**: Chrome 59 (Windows 10)
**Referer**: [https://mapstory.org/maps/edit?layer=geonode:ames_buildings_1_19_2017_1&mode=edit](https://mapstory.org/maps/edit?layer=geonode:ames_buildings_1_19_2017_1&mode=edit)
**Screen size**: 1920 x 1080 **Browser size**: 1536 x 779

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by emilyashley** [comment]
connecting some other notes here: #1047
