### ISSUE TITLE
Identify system requirements

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#875]
in the case of a VM providing the Unix system prerequisite, there are a few missing pieces required to make this work and document expected outcome.

first, statement along the lines of "Docker is used to create a running executable on this system, so a Unix VM running docker, or a physical machine running Unix is required. The docker container gets its disk and memory allocation from (presumably this Unix environment????)"

Need to include specifics such as:

disk space required 
memory required
networking requirements

(the ability to connect a browser via the http://docker seems relevant only to the case where the Unix environment supports a graphics console - so how do you test a deployment on a headless server/vm)

**Comment by Coop56** [comment]
See https://github.com/MapStory/mapstory/issues/790#issuecomment-318187689

**Comment by rob-metalinkage** [comment]
Still need to identify minimum system requirements for both dev and production installs 

Also See #790 (comment)
