### ISSUE TITLE
Survey Styling Components and Plan Refactor

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#886]
Study layer styling in MapLoom and decide the best course of action for refactoring and adding new features.

**Comment by cuttlefish** [comment]
There was talk of using Mapbox styles. Is that still on the table?

**Comment by emilyashley** [comment]
Hopping on this one, too if that's cool.

Re: mapbox style spec, we were looking into it w/ geoserver but I'm not certain if that's gonna work within this timeframe.

**Comment by trepagnier** [comment]
NTS: pick survey back up here: https://github.com/MapStory/MapLoom/blob/feature/composer-wip/src/common/map/MapService.js#L379
