### ISSUE TITLE
Layer preview breaks if Community Editing turned Off

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#897]
clean build, code up to date , american_civil_war example, works if defaults chosen, but if you turn off community editing during import then layer preview throws JS error and thumbnail is broken.  @Coop56 confirms behaviour.

http://errors.angularjs.org/1.3.15/ng/areq?p0=geogigController&p1=not%20a%20function%2C%20got%20undefined
   at vendor-assets-min.js:17
   at Rb (vendor-assets-min.js:30)
   at sb (vendor-assets-min.js:31)

**Comment by emilyashley** [comment]
On it.  Good catch! 
I can't guarantee the broken thumbnail is related, but I'm tackling the layer preview error. 
Thanks, @rob-metalinkage .

**Comment by rob-metalinkage** [comment]
bit more information - i was looking at layer metadata trying to get a handle on it all and what might have changed..
I tried two different data sets with community editing off - all broke, and american_civil_war again with community editing on, which worked..

osgeo_importer_uploadlayer has three entries for the three attempts
layers_layer has only two - the two american_civil_war - one which works and one which fails

whatever else - this is leaving a mess around - i will raise a separate issue.
