### ISSUE TITLE
Smooth scrolling for parallax images

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory#9]
The home page now supports the parallax effect, however, if you scroll down the index page, it doesn't scroll very smoothly as compared to the homepage on MapStoryOrg repo . I'm not sure if that is an issue with the Smoothscroll.js file.

**Comment by glynnis** [comment]
Closing this given the redesign work underway and the age of this issue. Please reopen and include more detail about what is desired here from a feature standpoint if this is still relevant.
