### ISSUE TITLE
Review post-conditions for layer load failure - orphaned data

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#918]
On failing to successfully load data,  layer references appear in both osgeo_importer_uploadlayer and (potentially a subset of layers) in layers_layer.

Review what should happen and implement test cases to make sure expected behaviour does happen reliably.  should cover bad data and failure in long running tasks, possibly user cancellation of tasks - whatever system behaviours should leave data in a known state and not proliferate orphaned data.  

Restarting load process may mean we want to keep things around - in which case there needs to be UI support for finding, fixing and cleaning, and system admin support for expiring failed layers.

**Comment by emilyashley** [comment]
What's the status on these failed layers say in osegeo importer uploadlayer?

It's worth noting that "Uploading" a layer and "Importing" a layer are different actions called different things. Which one are you talking about? (or both?)
