### ISSUE TITLE
Storybox time form fields shrink too much 

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#919]
When compressed by screen size the start and end time fields in story box edit  get shrunk too much
they have to coexist on a line with the time (which may not be useful at all and shows spurious detail) and also calendar and time picker icons which are fixed, so the most important info not shown.

**Comment by emilyashley** [comment]
hey @rob-metalinkage do you have a screenshot of this for clarification? We currently don't address responsive design in composer, however If it's a hard blocker for creating stories I can try and address this quickly in MapLoom. 

Also, for future reference, tho it might be a minute before it's released, here's the most up to date mockups for the Storybox / StoryFrame selection in MapStories moving forward. So excited! https://github.com/MapStory/mapstory-assets/blob/master/design_assets/2016_11_02%20-%20MapStory%20Composer/storyframesArtboard%201.png
