### ISSUE TITLE
No obvious way to access profile and drafts from Explore view

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#920]
(on beta) Was looking for a draft - can access from my profile page - but i cant access profile (anywhere obvious) from home or explore pages - the only place i have been able to see this is in the lop left or the composer after i've started editing a new story.

**Comment by rob-metalinkage** [comment]
ahh- have found it hidden under the avatar icon - looked like a label not an actionable link - and no clue thats where it was going.   this needs a rethink can we add a "my activity" link - and maybe under explore make an obvious link, and under create add an option to view and edit drafts? And on compose when a draft saved, show popup where profile can be accessed?

**Comment by emilyashley** [comment]
In the works.

You'll find the mockups here: https://github.com/MapStory/mapstory/issues/726#issuecomment-305320435

**Comment by rob-metalinkage** [comment]
sweet - where is the user flow design documentation (and similar things) stored?
