### ISSUE TITLE
Composer: adding storylayer to a chapter via mini-explore fails via geoserver GetCapabilities

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#921]
If you enter layer_preview and compose a mapstory, it works fine - but if you go to create/compose story
then it reports layer failed to load.  Reopening as a draft shows the same result.  (there is also no diagnostics about the failure - is it reported/tracked anywhere?)

adding a new story layer to the successfully composed story from the layer preview also fails.

**Comment by emilyashley** [comment]
Oh hey good eye, was just mentioning this to @Coop56 cause I've been experiencing it locally too 

To clarify on this bug report:

the url `/story/new?layer=points_nospace_d59edf51` (or whatever your layer name is) creates a mapstory and populates the first chapter with this layer successfully

however from the url `story/new?tour#add-layer-dialog` or `/story/17/draft#add-layer-dialog `,
adding a layer through the interface gets a 404 on `/geoserver/freespeechdata_9b70d7a3/undefined/wms?request=GetCapabilities` (or whatever your layer name is)

note to self: that undefined looks fishy check on link generation in miniexplore

updating title to "Adding storylayer to a chapter via mini-explore fails"

**Comment by rob-metalinkage** [comment]
is about layer naming assumptions i.e. - #903 #922 and only well-worn parts of the code getting updated? How do layer ids, uploadedlayers,  data tables, layer metadata ids, URLs and geoserver WMS layers and WFS features all interrelate ?

**Comment by emilyashley** [comment]
This is addressed in https://github.com/MapStory/MapLoom/commit/a6391a111b0a2180a73c548a8323a742be4e53ee#diff-6938e64f5577eb4f940a88095fca7874 and should be making it into the mapstory maploom build shortly via Jenkins.

Thanks @davisc 

As follow up we may need to determine why elastic doesn't include the workspace in the name.
