### ISSUE TITLE
Journal header area with gray background is abnormally tall.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#927]
**Sender**: jonpmarino@gmail.com
**Comment**: Journal header area with gray background is abnormally tall. Height should be reduced.
[Open #261 in Usersnap Dashboard](https://usersnap.com/a/#/mapstory-beta/p/mapstory-beta-abc33389/261)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-09/00-18/f0eadc36-5022-4722-903a-9c8865bb3624.png'>![Usersnap Feedback - Journal header area with gray background is abnormally tall. Height should (...)](https://usersnappublic.s3.amazonaws.com/2017-08-09/00-18/0bbdbc40-e4ca-400e-bf06-eeee2a02d9b1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-09/00-18/f0eadc36-5022-4722-903a-9c8865bb3624.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [https://beta.mapstory.org/journal/#](https://beta.mapstory.org/journal/#)
**Screen size**: 1440 x 900 **Browser size**: 1381 x 752

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by emilyashley** [comment]
Do you have an image you would like to be there? This was formally done via parallax in the admin panel but I can double check if that's changed.

**Comment by jonpmarino** [comment]
I can provide an image. 

Not ure where in the admin panel it was done. I assume under Parallax Images. Is there a specific naming convention for that image area?

Not super high priority given current backlog...
