### ISSUE TITLE
Footer area height should be reduced

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#929]
**Sender**: jonpmarino@gmail.com
**Comment**: Footer area is abnormally tall. Height should be reduced to just a bit below end of content area.
[Open #262 in Usersnap Dashboard](https://usersnap.com/a/#/mapstory-beta/p/mapstory-beta-abc33389/262)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-09/00-21/24738b9f-6c3e-437c-9e21-53f60749065b.png'>![Usersnap Feedback - Footer area is abnormally tall. Height should be reduced to just a bit bel(...)](https://usersnappublic.s3.amazonaws.com/2017-08-09/00-21/e0e6ac71-eb90-499b-baeb-d551e72c9dc5.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-09/00-21/24738b9f-6c3e-437c-9e21-53f60749065b.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [https://beta.mapstory.org/](https://beta.mapstory.org/)
**Screen size**: 1440 x 900 **Browser size**: 1381 x 752

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by emilyashley** [comment]
Yes, this came as a known side-effect from PR #822 . I mentioned that height for footer background might overcompensate, but shouldn't end up too small on mobile or tablet devices. It seemed like an insignificant side-effect given the backlog at the time.

**Comment by jonpmarino** [comment]
yes, def low priority for the backlog
