### ISSUE TITLE
Build JAR and inject into our GeoServer WAR

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#933]
This is a follow-on issue based on @smithkm work on #439 - making layer bounding boxes scale as new features are added/appended.

The plugin to do this is done: https://github.com/smithkm/ms-gs-plugins

**Comment by cuttlefish** [comment]
I've created a repo in the MapStory GitHub for this
https://github.com/MapStory/ms-gs-plugins

**Comment by cuttlefish** [comment]
@smithkm I've updated the build for GeoServer 2.11.2

Can you verify that it's working as expected on https://beta.mapstory.org ?
