### ISSUE TITLE
Add filter in django-admin for stories that are "featured"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#940]
In Stories section of Django-admin there is an option to set a story as "featured". Currently there is no way to simply filter to see all stories that are featured. An Admin must go into each story individually to see if it is featured.

As a user (admin) I want to filter stories in django-admin by those that are "featured" to see all featured stories in one table at the same time.

**Comment by Coop56** [comment]
Closed by https://github.com/MapStory/mapstory/pull/1022
