### ISSUE TITLE
Hitting "Exit" from layer editor throws an error

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#941]
Tested as of 8:19pm on Beta.mapstory.org using Chrome browser.

To reproduce:

1. Go to any layer detail page
2. Click "Edit features"
3. Click "Exit" button
4. Get this error page:

![screen shot 2017-08-09 at 8 20 10 pm](https://user-images.githubusercontent.com/2573761/29150433-307350ec-7d40-11e7-8e96-fafeac3b58cc.jpg)

**Comment by lhcramer** [comment]
Confirmed, should just be removing `geonode:LayerName` from button redirect link: 

- XPath:` //*[@id="editSingleStoryLayer"]/ng-include/button[6]` 
- From `<button class="btn-storylayer ng-scope" ng-click="openLink('/layers/geonode:' + storyService.active_layer.get('metadata').name, '_self')"><i class="fa fa-sign-out"></i>Exit</button>` 
- To `<button class="btn-storylayer ng-scope" ng-click="openLink('/layers/' + storyService.active_layer.get('metadata').name, '_self')"><i class="fa fa-sign-out"></i>Exit</button>`

**Comment by Coop56** [comment]
This has been resolved, and is live on Beta.
