### ISSUE TITLE
Setting the title during import doesn't work

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#944]
I'm not sure if this is a duplicate issue or not.

Setting title during import:
![image](https://user-images.githubusercontent.com/1152120/29192930-26efeae2-7dd8-11e7-8c61-0274b5ad6a87.png)

After import:
![image](https://user-images.githubusercontent.com/1152120/29192940-332b6912-7dd8-11e7-9bb4-61a0dfcbbadc.png)

GeoServer Layers page:
![image](https://user-images.githubusercontent.com/1152120/29193008-74ce4416-7dd8-11e7-9460-33149edd8662.png)

So it seems that setting the title in the import sets the store name, but not the title.

**Comment by cuttlefish** [comment]
By my reckoning we need at least three different names.
Title: Human readable title.
slug_title: URL safe version of the title. It should update when the user changes the title (or not?).
geoserver_title: The name used for setting the layer name and store name in GeoServer. Set to the initial slug_title, but it won't change when the user changes the title (there's probably a way to rename layers and stores, but that seems unnecessary).

**Comment by jonpmarino** [comment]
confirmed this issue on beta. Set title in importer. Doesn't persist to layer detail page.

**Comment by Coop56** [comment]
PR is open for this at https://github.com/GeoNode/django-osgeo-importer/pull/171
