### ISSUE TITLE
Create feature popups

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#945]
When you click on a feature on the map, a popup should appear.

**Comment by jonpmarino** [comment]
Darin, not sure if this addresses this current issue, https://github.com/MapStory/mapstory/issues/947

Or if you're working on something different and separate specific to new composer.

If the former, I'll close the issue I just made.

**Comment by trepagnier** [comment]
NTS: feature service functionality lives here: https://github.com/MapStory/story-tools/blob/master/lib/ng/core/ogc/services.js#L18

**Comment by trepagnier** [comment]
NTS: May be a projection issue? Run docker container, log feature point coords  on viewer.

**Comment by trepagnier** [comment]
NTS: troubleshoot again w new ol.css file
