### ISSUE TITLE
Beta users can no longer click on features to see the Feature attribute info

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#947]
On Prod, when I view a layer I can click on a feature to see its attribute information. For example, this is the pop-up on a feature of a Chinese Mystery Snail layer on prod:

![screen shot 2017-08-11 at 9 45 28 am](https://user-images.githubusercontent.com/2573761/29218353-2f4eb798-7e7a-11e7-80b7-f2ffa0ab5255.jpg)

On Beta it doesn't appear the user can click on features to see attribute information on the layer detail page anymore:

![screen shot 2017-08-11 at 9 46 05 am](https://user-images.githubusercontent.com/2573761/29218365-379fc702-7e7a-11e7-9007-8c9694dc4a9f.jpg)

As a user, I expect when viewing a layer on the layer detail page that I will be able to learn more about a feature by clicking on the feature to see Attribute information.

**Comment by lhcramer** [comment]
I believe this issue persists through to the layer editor. Reference UserSnap issue # 270 
![US270](https://usersnappublic.s3.amazonaws.com/2017-08-23/17-20/12cb3e78-6cd5-438a-a759-9fb107a1aecd.png)

**Comment by lhcramer** [comment]
As of 10:45PM PST on Wed 30 Aug on beta, I am able to select features in the _MapStory Viewer_ but not Editor, Composer or _StoryLayer_ viewer.

**Comment by jonpmarino** [comment]
based on testing at 1pm CST on August 31 on beta.mapstory.org, it looks like i can click on polygon features. Points it seems I can only click when they are in a published story state. Can't click them on layer detail page or editing interface See: https://beta.mapstory.org/story/139/
![screen shot 2017-08-31 at 12 57 13 pm](https://user-images.githubusercontent.com/2573761/29937736-2e0e1018-8e4c-11e7-8ea7-9b21ff4435c8.jpg)

**Comment by jonpmarino** [comment]
note - only on layer viewer

**Comment by davisc** [comment]
For some layers, geoserver is returning the following.. and appears to be limited to point layers.. and affects both MapLoom and StoryTools

<img width="1600" alt="screen shot 2017-09-13 at 4 56 42 pm" src="https://user-images.githubusercontent.com/947403/30402811-9c4bcd9c-98a4-11e7-9332-263fdf624f21.png">

**Comment by davisc** [comment]
@lhcramer also confirmed that the OpenLayers preview in GeoServer fails to display the feature info for the points layer but successfully displays the feature info for the polygon Layer. This is not a MapLoom or Storytools issue. This issue the result of the default style that's applied to the point layers. By changing the default style of this layer to a style that only contained the definition for Points, I'm able to successfully display the feature info popup in composer and viewer.

**Comment by davisc** [comment]
Should also investigate why MultiPoint is used as the Geom Type
<img width="376" alt="screen shot 2017-09-13 at 5 49 01 pm" src="https://user-images.githubusercontent.com/947403/30405420-5b01f96c-98b1-11e7-8097-99ad3dc06196.png">

**Comment by emilyashley** [comment]
Gotcha. Thanks, @davisc.

Is there a way to see which point layers have the 'default' style in geoserver and change 'em over so we can have as much interactivity as possible on beta? 

Can we prevent this from happening in future imports & layer creations?

**Comment by Coop56** [comment]
The style isn't actually called default, but it's correctly assigning the point style to point layers.  The issue is that the point style for some reason contains additional geom types and isn't meant for just points.  Anytime I load up a new environment this is what the point style looks like:

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<StyledLayerDescriptor version="1.0.0" 
                       xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" 
                       xmlns="http://www.opengis.net/sld" 
                       xmlns:ogc="http://www.opengis.net/ogc" 
                       xmlns:xlink="http://www.w3.org/1999/xlink" 
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NamedLayer>
    <Name>generic</Name>
    <UserStyle>
      <Title>Generic</Title>
      <Abstract>Generic style</Abstract>
      <FeatureTypeStyle>
        <Rule>
          <Name>Polygon</Name>
          <Title>Polygon</Title>
          <ogc:Filter>
            <ogc:PropertyIsEqualTo>
              <ogc:Function name="dimension">
                <ogc:Function name="geometry"/>
              </ogc:Function>
              <ogc:Literal>2</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <PolygonSymbolizer>
            <Fill>
              <CssParameter name="fill">#f59620</CssParameter>
              <CssParameter name="fill-opacity">.5</CssParameter>
            </Fill>
            <Stroke>     
              <CssParameter name="stroke">#000000</CssParameter>
              <CssParameter name="stroke-opacity">.8</CssParameter>
            </Stroke>
          </PolygonSymbolizer>
        </Rule>
        <Rule>
          <Name>Line</Name>
          <Title>Line</Title>
          <ogc:Filter>
            <ogc:PropertyIsEqualTo>
              <ogc:Function name="dimension">
                <ogc:Function name="geometry"/>
              </ogc:Function>
              <ogc:Literal>1</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <LineSymbolizer>
            <Stroke>
              <CssParameter name="stroke">#000000</CssParameter>
              <CssParameter name="stroke-opacity">.8</CssParameter>
            </Stroke>
          </LineSymbolizer>
        </Rule>
        <Rule>
          <Name>point</Name>
          <Title>Point</Title>
          <ElseFilter/>
          <PointSymbolizer>
            <Graphic>
              <Mark>
                <WellKnownName>circle</WellKnownName>
                <Fill>
                  <CssParameter name="fill">#f59620</CssParameter>
                  <CssParameter name="fill-opacity">.5</CssParameter>
                </Fill>
                <Stroke>
                  <CssParameter name="stroke">#000000</CssParameter>
                  <CssParameter name="stroke-opacity">.8</CssParameter>
                </Stroke>
              </Mark>
              <Size>10</Size>
            </Graphic>
          </PointSymbolizer>
        </Rule>
        <VendorOption name="ruleEvaluation">first</VendorOption>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
```

If I change that style in Geoserver like @davisc said to something that only has points classified in it (I grabbed the one from beta) it works fine.  How can we change the default style that Geoserver comes with and keep it that way instead of having to change it every time?  Also why is this even the default for Geoserver?  I would think the default point style would only contain styling for points.

**Comment by davisc** [comment]
@Coop56 In the ansible days, we would do this https://github.com/MapStory/mapstory/blob/011da970d0280a43827e930d89e89b94540ccd54/scripts/provision/roles/geo/tasks/main.yml#L93
