### ISSUE TITLE
Get Local MapLoom Dev Env Working

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory#974]

**Comment by davisc** [comment]
Add this to the Dockerfile: 
this will symlink the maploom files to the MapLoom repository which in the submodule deps directory. If submodule is not desired, you could mount a dir to sibling (maploom repo) directory outside of the container.

Note: Make sure the paths are correct.

RUN rm -rf /usr/local/lib/python2.7/site-packages/maploom/static/maploom && \
    ln -s $APP_PATH/deps/maploom/build /env/lib/python2.7/site-packages/maploom/static/maploom && \
    rm /usr/local/lib/python2.7/site-packages/maploom/templates/maps/maploom.html && \
    ln -s $APP_PATH/deps/maploom/build/maploom.html /usr/local/lib/python2.7/site-packages/maploom/templates/maps/maploom.html

**Comment by Coop56** [comment]
@cuttlefish got a working MapLoom deployment with Docker up and running.  Closing this issue.
