### ISSUE TITLE
Update addLayer directive to display layer name

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#975]
Criteria:
- Display layer.title in search form
- List max 10 search results in form
- Pass layer.typename to addLayer so that it can construct the correct wms request

In order to add the layer using the typename while still displaying the title, it will be necessary to build an index of search results containing both attributes.

**Comment by darinacosta** [comment]
Resolved: https://github.com/MapStory/story-tools-composer/commit/f976cc427e847a98f9c2c0af200dfdfd7ff605a3

**Comment by trepagnier** [comment]
Resolved: https://github.com/MapStory/story-tools-composer/commit/0996a133b0278404983138976fd010650761052d
Now refactor the code (#976)
