### ISSUE TITLE
Fix ui-tooltip warnings in Story-tools

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#979]
Story-tools is generating a lot of ui-bootstrap warnings. Fix that!

**Comment by goudine** [comment]
Closing ticket with PR's:
   - https://github.com/MapStory/story-tools/pull/299
  - https://github.com/MapStory/story-tools-composer/pull/195
  - https://github.com/MapStory/mapstory/pull/1372
and this commit:
  - https://github.com/MapStory/story-tools/commit/766e4c907ca22ae6a3f6b29e2c6c5585e84d18b0

Out of the four story-tools warnings present originally:
![viewer_warnings.png](https://images.zenhubusercontent.com/5ad50c3a4b5806bc2bcf5770/b6e8d483-5abc-45a3-9cdc-214db79cfe04)

3 were resolved:
![less_warnings.png](https://images.zenhubusercontent.com/5ad50c3a4b5806bc2bcf5770/f8e17ce2-3d24-477b-b99a-3432ea68f0e9)

Remaining tooltip warning appears to be coming from `deps/maploom` and `/django-maploom`.
