### ISSUE TITLE
SSL cert error on local deploy

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#982]
Django is throwing an error when attempting to download the append schema.

`SSLError at /layers/download-append-shp
HTTPSConnectionPool(host='docker', port=443): Max retries exceeded with url: /geoserver/wfs?format_options=charset%3AUTF-8&typename=american_civil_war_7a0c548c&outputFormat=SHAPE-ZIP&version=1.0.0&service=WFS&request=GetFeature&featureID=fakeID&propertyName=result,totalcasua,wkb_geometry,battlefiel,battlename,state,battletype,begindate,enddate,theatercod (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))`

**Comment by Coop56** [comment]
This has been resolved.  Closing.
