### ISSUE TITLE
Usersnap Feedback - Layer append failed, however, the `id` column became `male symbol d`

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#985]
**Sender**: cramer@mapstory.org
[Open #277 in Usersnap Dashboard](https://usersnap.com/a/#/mapstory-beta/p/mapstory-beta-abc33389/277)
**Notes**:
 - (1) Layer append failed, however, the `id` column became `male symbol d`

<a href='https://usersnappublic.s3.amazonaws.com/2017-09-01/00-15/ef13aa87-69ab-449d-93b5-8044bdd50097.png'>![Usersnap Feedback - Layer append failed, however, the `id` column became `male symbol d`](https://usersnappublic.s3.amazonaws.com/2017-09-01/00-15/9f3b6115-538e-402c-8886-62cd9aafce48.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-09-01/00-15/ef13aa87-69ab-449d-93b5-8044bdd50097.png'>Download original image</a>

**Browser**: Chrome 60 (Linux)
**Referer**: [https://beta.mapstory.org/layers/poly_test_set_f196d1a3](https://beta.mapstory.org/layers/poly_test_set_f196d1a3)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 623

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by lhcramer** [comment]
![screenshot from 2017-08-31 15-19-31](https://user-images.githubusercontent.com/5894255/29948223-83802aac-8e62-11e7-9276-38e22594a09c.png)
