### ISSUE TITLE
StoryTools: time slider and playback controls requirements

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#995]
Document desired requirements for time-slider playback controls. 

Time Domain

Playback Options:
 Scale
 Rate
 Duration

Make sure to expect:
Range-enabled entities
Mixed and Uniform Precision

**Comment by rob-metalinkage** [comment]
Hi Em. whats the story with this task? Lets talk sometime about era handling and time sliders.. am starting to work again on eras module - and i'd like to embed a timeslider as a viewer for the era definitions themselves.
